import { Company } from '@/types';

export const companiesBatchC6: Company[] = [
  {
    id: '776',
    slug: 'leadpages-affiliate',
    name: 'Leadpages Affiliate Program',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'Minneapolis, MN, USA',
    website: 'https://www.leadpages.com/affiliate',
    products_summary: 'Landing page builder and conversion optimization platform with drag-and-drop editor, A/B testing, and lead capture tools for digital marketers.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['Recurring 30% commissions', 'Popular landing page tool', 'Generous 90-day cookie', 'Quality marketing materials'],
    cons: ['Competitive niche', 'Higher price point to sell', 'Requires technical audience'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': '30% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Landing pages'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Earn recurring commissions promoting landing page software',
    faq: [
      { question: 'How much can I earn per sale?', answer: 'You earn 30% recurring commissions on all customer payments, which typically ranges from $11-$74+ per month depending on the plan.' },
      { question: 'Is this a one-time or recurring commission?', answer: 'Recurring - you earn 30% every month as long as your referral remains a paying customer.' }
    ]
  },
  {
    id: '777',
    slug: 'unbounce-affiliate',
    name: 'Unbounce Affiliate Program',
    category: 'affiliate',
    founded_year: 2009,
    hq_location: 'Vancouver, BC, Canada',
    website: 'https://unbounce.com/partners/affiliate/',
    products_summary: 'AI-powered landing page platform with Smart Traffic optimization, conversion intelligence, and no-code builder for agencies and marketers.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.8,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['20% lifetime recurring', 'Enterprise-grade product', 'High customer retention', 'Excellent affiliate support'],
    cons: ['Premium pricing only', 'Smaller brand than competitors', 'Requires marketing knowledge'],
    quick_facts: {
      'Founded': '2009',
      'Commission Rate': '20% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Impact'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Lifetime 20% commissions on AI landing page software',
    faq: [
      { question: 'What is the commission structure?', answer: '20% recurring commission on all monthly or annual plan payments for the lifetime of the customer.' },
      { question: 'What are typical customer values?', answer: 'Plans range from $99 to $625+ per month, so monthly commissions range from $20 to $125+.' }
    ]
  },
  {
    id: '778',
    slug: 'instapage-affiliate',
    name: 'Instapage Affiliate Program',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://instapage.com/affiliate',
    products_summary: 'Enterprise landing page platform with advanced personalization, heatmaps, experimentation tools, and collaboration features for marketing teams.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.7,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['Premium product quality', '30% first-year commission', 'Strong conversion rates', 'Dedicated affiliate manager'],
    cons: ['Only first year recurring', 'Enterprise focus limits audience', 'Higher barrier to entry'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': '30% first year',
      'Cookie Duration': '90 days',
      'Platform': 'Landing pages'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Earn 30% promoting enterprise landing page software',
    faq: [
      { question: 'How long do I earn commissions?', answer: 'You earn 30% recurring commissions for the first 12 months of each customer subscription.' },
      { question: 'What is the average sale value?', answer: 'Plans start at $199/month, so your monthly commission starts at approximately $60 per customer.' }
    ]
  },
  {
    id: '779',
    slug: 'swipe-pages-affiliate',
    name: 'Swipe Pages Affiliate Program',
    category: 'affiliate',
    founded_year: 2018,
    hq_location: 'Remote',
    website: 'https://swipepages.com/affiliate',
    products_summary: 'Fast-loading mobile-first landing page builder with AMP technology, optimized for speed and mobile conversions.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['30% recurring lifetime', 'Unique AMP technology', 'Modern user interface', 'Growing platform'],
    cons: ['Newer brand', 'Smaller market share', 'Limited brand recognition'],
    quick_facts: {
      'Founded': '2018',
      'Commission Rate': '30% lifetime',
      'Cookie Duration': '60 days',
      'Platform': 'AMP landing pages'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Promote fast-loading AMP landing pages with 30% recurring',
    faq: [
      { question: 'What makes Swipe Pages different?', answer: 'They specialize in AMP (Accelerated Mobile Pages) technology for ultra-fast mobile landing pages.' },
      { question: 'What are the commission rates?', answer: '30% recurring commission for the lifetime of the customer on all paid plans.' }
    ]
  },
  {
    id: '780',
    slug: 'gohighlevel-affiliate',
    name: 'GoHighLevel Affiliate Program',
    category: 'affiliate',
    founded_year: 2018,
    hq_location: 'Dallas, TX, USA',
    website: 'https://www.gohighlevel.com/affiliates',
    products_summary: 'All-in-one white-label marketing platform for agencies with CRM, funnel builder, email/SMS marketing, appointment scheduling, and automation.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['40% recurring commissions', 'Sticky agency platform', 'Active community support', 'High customer LTV'],
    cons: ['Complex platform to explain', 'Agency-focused limits audience', 'Steep learning curve'],
    quick_facts: {
      'Founded': '2018',
      'Commission Rate': '40% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Agency CRM'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Earn 40% recurring on all-in-one agency platform',
    faq: [
      { question: 'How much can I earn per referral?', answer: 'With plans at $97-$297/month, you can earn $39-$119+ monthly recurring per customer.' },
      { question: 'Who is the ideal customer?', answer: 'Digital marketing agencies, consultants, and service providers who manage multiple clients.' }
    ]
  },
  {
    id: '781',
    slug: 'systeme-io-affiliate',
    name: 'Systeme.io Affiliate Program',
    category: 'affiliate',
    founded_year: 2018,
    hq_location: 'Paris, France',
    website: 'https://systeme.io/affiliate',
    products_summary: 'All-in-one business platform with sales funnels, email marketing, course hosting, affiliate management, and automation at budget-friendly pricing.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.8,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['60% lifetime recurring', 'Affordable for beginners', 'All-in-one solution', 'Strong value proposition'],
    cons: ['Lower price points', 'Less polished than competitors', 'Smaller brand name'],
    quick_facts: {
      'Founded': '2018',
      'Commission Rate': '60% lifetime',
      'Cookie Duration': '90 days',
      'Free Plan': 'Yes'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Massive 60% recurring commissions on all-in-one platform',
    faq: [
      { question: 'Why is the commission rate so high?', answer: 'Systeme.io focuses on volume and word-of-mouth growth, offering industry-leading 60% recurring commissions.' },
      { question: 'What are typical earnings per customer?', answer: 'Plans range from $27-$97/month, earning you $16-$58+ monthly per customer for life.' }
    ]
  },
  {
    id: '782',
    slug: 'podia-affiliate',
    name: 'Podia Affiliate Program',
    category: 'affiliate',
    founded_year: 2014,
    hq_location: 'New York, NY, USA',
    website: 'https://www.podia.com/affiliates',
    products_summary: 'Creator platform for online courses, digital downloads, memberships, and webinars with email marketing and no transaction fees.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.8,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['30% recurring lifetime', 'No transaction fees USP', 'Simple creator-friendly', 'Clean interface'],
    cons: ['Mid-tier pricing limits earnings', 'Competitive creator space', 'Smaller feature set'],
    quick_facts: {
      'Founded': '2014',
      'Commission Rate': '30% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Creator tools'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Promote simple course platform with 30% lifetime recurring',
    faq: [
      { question: 'What makes Podia attractive to customers?', answer: 'Zero transaction fees on all plans, unlimited products, and simple all-in-one platform for creators.' },
      { question: 'What are the earnings?', answer: 'Plans at $39-$89/month mean $12-$27+ monthly recurring commission per customer.' }
    ]
  },
  {
    id: '783',
    slug: 'circle-so-affiliate',
    name: 'Circle.so Affiliate Program',
    category: 'affiliate',
    founded_year: 2019,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://circle.so/affiliates',
    products_summary: 'Modern community platform combining discussions, courses, live streams, and events with powerful integrations and member management.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.8,
    residual_rating: 4.0,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['30% recurring commission', 'Fast-growing platform', 'Strong creator community', 'Modern design'],
    cons: ['Higher pricing tiers', 'Newer platform', 'Learning curve for features'],
    quick_facts: {
      'Founded': '2019',
      'Commission Rate': '30% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Community'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Earn 30% recurring on modern community platform',
    faq: [
      { question: 'What is Circle.so best for?', answer: 'Creators and businesses building engaged communities with courses, events, and discussion forums in one place.' },
      { question: 'What are typical commissions?', answer: 'Plans from $89-$360/month mean earning $27-$108+ monthly recurring per community.' }
    ]
  },
  {
    id: '784',
    slug: 'mighty-networks-affiliate',
    name: 'Mighty Networks Affiliate Program',
    category: 'affiliate',
    founded_year: 2017,
    hq_location: 'Palo Alto, CA, USA',
    website: 'https://www.mightynetworks.com/affiliates',
    products_summary: 'Community platform with courses, memberships, events, and native mobile apps for building branded social networks.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.7,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['Native mobile apps included', '30% first year recurring', 'Strong community features', 'Brand building focus'],
    cons: ['Only first year commission', 'Premium pricing', 'Complex for beginners'],
    quick_facts: {
      'Founded': '2017',
      'Commission Rate': '30% first year',
      'Cookie Duration': '90 days',
      'Platform': 'Community + Apps'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Promote community platform with native apps',
    faq: [
      { question: 'How long do commissions last?', answer: 'You earn 30% recurring commissions for the first 12 months of each customer subscription.' },
      { question: 'What sets Mighty Networks apart?', answer: 'Native iOS and Android apps included with Business plan, plus course hosting and community features.' }
    ]
  },
  {
    id: '785',
    slug: 'tribe-community-affiliate',
    name: 'Tribe Community Platform Affiliate',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'Remote',
    website: 'https://tribe.so/affiliates',
    products_summary: 'White-label community platform with customizable spaces, Q&A forums, moderation tools, and API for embedding communities.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['20% recurring lifetime', 'White-label capabilities', 'API and embeddable', 'Flexible pricing tiers'],
    cons: ['Smaller brand recognition', 'Technical setup required', 'Competitive space'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': '20% lifetime',
      'Cookie Duration': '60 days',
      'Platform': 'Community'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'White-label community software with 20% recurring',
    faq: [
      { question: 'What is the commission structure?', answer: '20% recurring commission for the lifetime of each customer on all paid plans.' },
      { question: 'Who uses Tribe?', answer: 'SaaS companies, agencies, and businesses embedding branded communities into their products.' }
    ]
  },
  {
    id: '786',
    slug: 'memberful-affiliate',
    name: 'Memberful Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'Minneapolis, MN, USA',
    website: 'https://memberful.com/affiliates/',
    products_summary: 'Membership software for WordPress and custom sites with payment processing, content restriction, and member management (owned by Patreon).',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.7,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% first year recurring', 'Patreon backing', 'WordPress integration', 'Clean setup process'],
    cons: ['WordPress-focused limits reach', 'Only first year commissions', 'Transaction fees on basic'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': '30% first year',
      'Cookie Duration': '90 days',
      'Platform': 'Membership'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'WordPress membership software with 30% commissions',
    faq: [
      { question: 'How does Memberful pricing work?', answer: 'Free to start with 10% transaction fee, or $25/month for 4.9% fee plus premium features.' },
      { question: 'What are typical earnings?', answer: 'Most customers use Pro plan at $25-100/month, earning you $7.50-$30/month for first year.' }
    ]
  },
  {
    id: '787',
    slug: 'memberpress-affiliate',
    name: 'MemberPress Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'Park City, UT, USA',
    website: 'https://memberpress.com/affiliates/',
    products_summary: 'WordPress membership plugin for creating subscription sites, courses, paywalls, and member communities with powerful content dripping.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% commission on sales', 'Popular WordPress plugin', 'Strong conversion rates', 'Reputable brand'],
    cons: ['One-time only (no recurring)', 'Annual renewals not commissioned', 'WordPress only'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': '30% one-time',
      'Cookie Duration': '90 days',
      'Platform': 'WordPress'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Popular WordPress membership plugin affiliate program',
    faq: [
      { question: 'Is this recurring commission?', answer: 'No, you earn 30% on initial sale only. Renewals are not commissioned.' },
      { question: 'What are typical earnings per sale?', answer: 'Licenses range from $179-$599/year, so you earn $54-$180 per sale.' }
    ]
  },
  {
    id: '788',
    slug: 'paid-memberships-pro-affiliate',
    name: 'Paid Memberships Pro Affiliate',
    category: 'affiliate',
    founded_year: 2011,
    hq_location: 'Philadelphia, PA, USA',
    website: 'https://www.paidmembershipspro.com/affiliates/',
    products_summary: 'Free WordPress membership plugin with premium add-ons for member levels, payment gateways, content restriction, and subscriptions.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.4,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['Free core plugin', '20% recurring on add-ons', 'Large WordPress community', 'Flexible system'],
    cons: ['Lower commission rate', 'Freemium model', 'Smaller average order value'],
    quick_facts: {
      'Founded': '2011',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '60 days',
      'Platform': 'WordPress'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Free WordPress membership plugin with paid add-ons',
    faq: [
      { question: 'What do you earn commission on?', answer: '20% recurring commission on Plus membership ($297/year) and add-on purchases.' },
      { question: 'Why promote a free plugin?', answer: 'Large user base upgrades to premium features, support, and add-ons for advanced functionality.' }
    ]
  },
  {
    id: '789',
    slug: 'wishlist-member-affiliate',
    name: 'WishList Member Affiliate Program',
    category: 'affiliate',
    founded_year: 2008,
    hq_location: 'Vancouver, BC, Canada',
    website: 'https://wishlistmember.com/affiliates/',
    products_summary: 'WordPress membership plugin with content protection, membership tiers, sequential content dripping, and integration with major payment processors.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% commission rate', 'Established brand', 'Strong reputation', 'Quality marketing materials'],
    cons: ['One-time commissions only', 'WordPress limitation', 'No renewal commissions'],
    quick_facts: {
      'Founded': '2008',
      'Commission Rate': '30% one-time',
      'Cookie Duration': '90 days',
      'Platform': 'WordPress'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Established WordPress membership solution affiliate',
    faq: [
      { question: 'What are the commission details?', answer: 'Earn 30% one-time commission on sales. No commission on annual renewals.' },
      { question: 'What is a typical sale worth?', answer: 'Single site license is $147/year (earn $44) and unlimited sites is $297/year (earn $89).' }
    ]
  },
  {
    id: '790',
    slug: 'accessally-affiliate',
    name: 'AccessAlly Affiliate Program',
    category: 'affiliate',
    founded_year: 2015,
    hq_location: 'Vancouver, BC, Canada',
    website: 'https://accessally.com/affiliates/',
    products_summary: 'Premium WordPress plugin for membership sites, online courses, and customer journey automation with advanced gamification features.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% recurring lifetime', 'Premium positioning', 'Advanced features', 'Excellent support'],
    cons: ['High price point to sell', 'Smaller market than competitors', 'Complex for beginners'],
    quick_facts: {
      'Founded': '2015',
      'Commission Rate': '30% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'WordPress'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Premium WordPress course plugin with 30% recurring',
    faq: [
      { question: 'What makes AccessAlly premium?', answer: 'Advanced automation, gamification, customer journey mapping, and white-glove support for course creators.' },
      { question: 'What are earnings per customer?', answer: 'Plans at $99-$399/month mean earning $30-$120+ monthly recurring per customer.' }
    ]
  },
  {
    id: '791',
    slug: 'lifter-lms-affiliate',
    name: 'LifterLMS Affiliate Program',
    category: 'affiliate',
    founded_year: 2015,
    hq_location: 'San Diego, CA, USA',
    website: 'https://lifterlms.com/affiliates/',
    products_summary: 'WordPress LMS plugin for creating, selling, and protecting online courses with quizzes, certificates, memberships, and advanced reporting.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['20% commission on all sales', 'Free core plugin', 'Strong WordPress community', 'Good documentation'],
    cons: ['One-time commissions', 'Lower rate than competitors', 'No renewal commissions'],
    quick_facts: {
      'Founded': '2015',
      'Commission Rate': '20% one-time',
      'Cookie Duration': '60 days',
      'Platform': 'WordPress LMS'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'WordPress LMS plugin affiliate program',
    faq: [
      { question: 'What products earn commission?', answer: 'All purchases including bundles, add-ons, and annual subscriptions earn 20% one-time commission.' },
      { question: 'What are typical earnings?', answer: 'Universe Bundle at $999/year earns $200, individual add-ons $9.99-$99/year earn $2-$20.' }
    ]
  },
  {
    id: '792',
    slug: 'learndash-affiliate',
    name: 'LearnDash Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'Remote',
    website: 'https://www.learndash.com/affiliates/',
    products_summary: 'WordPress LMS plugin trusted by Fortune 500 companies, universities, and training organizations with advanced course building and reporting.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['Market leader in WordPress LMS', '30% commission rate', 'High conversion rates', 'Brand recognition'],
    cons: ['One-time only', 'No recurring income', 'Annual renewal not commissioned'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': '30% one-time',
      'Cookie Duration': '90 days',
      'Platform': 'WordPress LMS'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Leading WordPress LMS with 30% commissions',
    faq: [
      { question: 'Why is LearnDash popular?', answer: 'Most trusted WordPress LMS used by Fortune 500s, with robust features and excellent support.' },
      { question: 'What can I earn per sale?', answer: 'Licenses at $199-$799/year mean earning $60-$240 per sale.' }
    ]
  },
  {
    id: '793',
    slug: 'tutor-lms-affiliate',
    name: 'Tutor LMS Affiliate Program',
    category: 'affiliate',
    founded_year: 2019,
    hq_location: 'Dhaka, Bangladesh',
    website: 'https://www.themeum.com/affiliates/',
    products_summary: 'Modern WordPress LMS with frontend course builder, interactive video, advanced quizzes, and Zoom integration for live classes.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.4,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['Free core version', '25% commission rate', 'Modern interface', 'Growing platform'],
    cons: ['Newer brand', 'One-time commissions', 'Smaller community'],
    quick_facts: {
      'Founded': '2019',
      'Commission Rate': '25% one-time',
      'Cookie Duration': '60 days',
      'Platform': 'WordPress LMS'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Modern WordPress LMS affiliate program',
    faq: [
      { question: 'What is the commission structure?', answer: 'Earn 25% one-time commission on all Tutor LMS Pro purchases and renewals.' },
      { question: 'What are typical sales values?', answer: 'Pro plans range from $149-$399/year, earning $37-$100 per sale.' }
    ]
  },
  {
    id: '794',
    slug: 'sensei-lms-affiliate',
    name: 'Sensei LMS Affiliate',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://senseilms.com/affiliates/',
    products_summary: 'WordPress course plugin by WooCommerce creators, seamlessly integrating courses with eCommerce and content management.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['WooCommerce integration', '25% commission', 'Trusted brand', 'Simple setup'],
    cons: ['One-time commissions only', 'Smaller feature set', 'Limited to WordPress'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': '25% one-time',
      'Cookie Duration': '90 days',
      'Platform': 'WordPress'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'WooCommerce-powered course plugin affiliate',
    faq: [
      { question: 'What makes Sensei different?', answer: 'Built by WooCommerce team for seamless integration between courses and eCommerce.' },
      { question: 'What are earnings?', answer: 'Annual plans at $129-$299/year earn $32-$75 per sale with 25% commission.' }
    ]
  },
  {
    id: '795',
    slug: 'academy-of-mine-affiliate',
    name: 'Academy of Mine Affiliate Program',
    category: 'affiliate',
    founded_year: 2014,
    hq_location: 'Seattle, WA, USA',
    website: 'https://www.academyofmine.com/affiliates/',
    products_summary: 'Enterprise LMS platform for associations, certification programs, and training organizations with advanced compliance tracking.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['20% recurring commission', 'Enterprise clients', 'High contract values', 'Niche positioning'],
    cons: ['Long sales cycles', 'Small target audience', 'Enterprise focus only'],
    quick_facts: {
      'Founded': '2014',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Enterprise LMS'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Enterprise LMS for associations with 20% recurring',
    faq: [
      { question: 'Who is the ideal customer?', answer: 'Professional associations, certification bodies, and compliance training organizations.' },
      { question: 'What are typical deal sizes?', answer: 'Enterprise contracts range from $500-$2,000+/month, earning $100-$400+ monthly recurring.' }
    ]
  },
  {
    id: '796',
    slug: 'ruzuku-affiliate',
    name: 'Ruzuku Affiliate Program',
    category: 'affiliate',
    founded_year: 2010,
    hq_location: 'Asheville, NC, USA',
    website: 'https://www.ruzuku.com/affiliates',
    products_summary: 'Simple online course platform focused on engagement and completion with live courses, cohorts, and community features.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.4,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['30% recurring lifetime', 'Simple platform', 'Focus on completion', 'Personal support'],
    cons: ['Smaller brand', 'Limited marketing reach', 'Fewer integrations'],
    quick_facts: {
      'Founded': '2010',
      'Commission Rate': '30% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Course hosting'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Simple course platform with 30% lifetime recurring',
    faq: [
      { question: 'What makes Ruzuku unique?', answer: 'Focus on live cohort-based courses with high completion rates and personal instructor support.' },
      { question: 'What are typical earnings?', answer: 'Plans at $74.75-$124.75/month earn $22-$37+ monthly recurring per customer.' }
    ]
  },
  {
    id: '797',
    slug: 'simplero-affiliate',
    name: 'Simplero Affiliate Program',
    category: 'affiliate',
    founded_year: 2010,
    hq_location: 'Asheville, NC, USA',
    website: 'https://simplero.com/affiliates',
    products_summary: 'All-in-one platform for courses, memberships, email marketing, CRM, and landing pages built by course creators for creators.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['25% lifetime recurring', 'All-in-one solution', 'Built by creators', 'Strong value proposition'],
    cons: ['Smaller market presence', 'Learning curve', 'Niche audience'],
    quick_facts: {
      'Founded': '2010',
      'Commission Rate': '25% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'All-in-one'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'All-in-one creator platform with 25% recurring',
    faq: [
      { question: 'What does Simplero include?', answer: 'Courses, memberships, email marketing, automation, website builder, CRM, and payment processing.' },
      { question: 'What can affiliates earn?', answer: 'Plans from $79-$349/month mean $20-$87+ monthly recurring per customer for life.' }
    ]
  },
  {
    id: '798',
    slug: 'new-zenler-affiliate',
    name: 'New Zenler Affiliate Program',
    category: 'affiliate',
    founded_year: 2020,
    hq_location: 'Remote',
    website: 'https://newzenler.com/affiliates',
    products_summary: 'All-in-one course platform with website builder, marketing automation, live classes, communities, and webinars at competitive pricing.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.4,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 4.0,
    pros: ['50% recurring lifetime', 'All-in-one platform', 'Competitive pricing', 'Unlimited everything'],
    cons: ['Very new platform', 'Limited track record', 'Brand building needed'],
    quick_facts: {
      'Founded': '2020',
      'Commission Rate': '50% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'All-in-one'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'New all-in-one platform with massive 50% recurring',
    faq: [
      { question: 'Why such high commissions?', answer: 'As a newer platform, New Zenler invests heavily in affiliate marketing for growth and word-of-mouth.' },
      { question: 'What are typical earnings?', answer: 'Plans at $47-$67/month mean $23.50-$33.50 monthly recurring per customer for life.' }
    ]
  },
  {
    id: '799',
    slug: 'xperiencify-affiliate',
    name: 'Xperiencify Affiliate Program',
    category: 'affiliate',
    founded_year: 2019,
    hq_location: 'Remote',
    website: 'https://xperiencify.com/affiliates',
    products_summary: 'Gamified course platform using behavioral psychology to increase completion rates with points, levels, achievements, and social features.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['40% recurring lifetime', 'Unique gamification', 'High engagement rates', 'Strong positioning'],
    cons: ['Higher price point', 'Newer platform', 'Niche feature set'],
    quick_facts: {
      'Founded': '2019',
      'Commission Rate': '40% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Gamified courses'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Gamified course platform with 40% lifetime recurring',
    faq: [
      { question: 'What makes Xperiencify different?', answer: 'Uses game mechanics and behavioral psychology to achieve 10x higher course completion rates.' },
      { question: 'What are the earnings?', answer: 'Plans at $99-$299/month earn $40-$120+ monthly recurring per customer for life.' }
    ]
  },
  {
    id: '800',
    slug: 'coassemble-affiliate',
    name: 'Coassemble Affiliate Program',
    category: 'affiliate',
    founded_year: 2015,
    hq_location: 'Brisbane, Australia',
    website: 'https://www.coassemble.com/affiliates',
    products_summary: 'Cloud-based LMS and course authoring platform for creating engaging interactive training with templates and collaborative tools.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['20% recurring commission', 'Modern interface', 'Team collaboration', 'Good templates'],
    cons: ['Australian company (timezone)', 'Smaller global presence', 'Mid-tier pricing'],
    quick_facts: {
      'Founded': '2015',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'LMS + Authoring'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Modern LMS with course authoring and 20% recurring',
    faq: [
      { question: 'Who uses Coassemble?', answer: 'Corporate training teams, L&D departments, and businesses creating internal training programs.' },
      { question: 'What are typical commissions?', answer: 'Plans from $99-$499/month earn $20-$100+ monthly recurring per customer.' }
    ]
  },
  {
    id: '801',
    slug: 'talentlms-affiliate',
    name: 'TalentLMS Affiliate Program',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://www.talentlms.com/affiliates',
    products_summary: 'Cloud LMS for training teams to create courses, manage users, and deliver training with mobile apps and integrations.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% recurring commission', 'Easy to use', 'Scalable pricing', 'Free starter plan'],
    cons: ['Corporate focus', 'Lower average sale value', 'Competitive space'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': '30% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Cloud LMS'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Simple cloud LMS with 30% recurring commissions',
    faq: [
      { question: 'What is the ideal customer?', answer: 'Small to medium businesses, training companies, and HR teams needing employee training solutions.' },
      { question: 'What can I earn?', answer: 'Paid plans from $69-$429/month earn $21-$129+ monthly recurring per customer.' }
    ]
  },
  {
    id: '802',
    slug: 'docebo-affiliate',
    name: 'Docebo Affiliate Program',
    category: 'affiliate',
    founded_year: 2005,
    hq_location: 'Toronto, ON, Canada',
    website: 'https://www.docebo.com/partners/affiliate/',
    products_summary: 'Enterprise AI-powered learning platform for customer education, partner training, and employee development at scale.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.7,
    residual_rating: 4.0,
    simplicity_rating: 3.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Enterprise contract values', 'Public company (NASDAQ)', 'AI-powered features', 'Strong brand'],
    cons: ['Long sales cycles', 'Enterprise only', 'Complex implementation'],
    quick_facts: {
      'Founded': '2005',
      'Commission Rate': 'Negotiable',
      'Cookie Duration': '90 days',
      'Platform': 'Enterprise LMS'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Enterprise AI learning platform affiliate program',
    faq: [
      { question: 'What are commission rates?', answer: 'Enterprise affiliate commissions are typically negotiated based on deal size and partnership level.' },
      { question: 'Who is Docebo for?', answer: 'Large enterprises, franchises, and companies with 1,000+ employees needing scalable learning.' }
    ]
  },
  {
    id: '803',
    slug: 'absorb-lms-affiliate',
    name: 'Absorb LMS Affiliate Program',
    category: 'affiliate',
    founded_year: 2003,
    hq_location: 'Calgary, AB, Canada',
    website: 'https://www.absorblms.com/partners',
    products_summary: 'Enterprise learning management system for employee training, compliance, and extended enterprise with AI recommendations.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Enterprise clients', 'High deal values', 'Established platform', 'AI features'],
    cons: ['Enterprise sales cycle', 'Requires connections', 'Complex product'],
    quick_facts: {
      'Founded': '2003',
      'Commission Rate': 'Partnership-based',
      'Cookie Duration': 'Varies',
      'Platform': 'Enterprise LMS'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Enterprise LMS partner program with high values',
    faq: [
      { question: 'How does the partner program work?', answer: 'Referral and reseller partnerships available with custom commission structures for enterprise deals.' },
      { question: 'What are typical contract sizes?', answer: 'Enterprise LMS contracts range from $10,000-$100,000+ annually depending on user count.' }
    ]
  },
  {
    id: '804',
    slug: 'litmos-affiliate',
    name: 'Litmos Affiliate Program',
    category: 'affiliate',
    founded_year: 2007,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://www.litmos.com/partners',
    products_summary: 'Corporate LMS with extensive course library, mobile learning, and gamification for employee and customer training.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['SAP owned (stability)', 'Large course library', 'Corporate market', 'Global presence'],
    cons: ['Partner program not traditional affiliate', 'Enterprise focus', 'Longer sales process'],
    quick_facts: {
      'Founded': '2007',
      'Commission Rate': 'Partner-based',
      'Cookie Duration': 'Varies',
      'Platform': 'Corporate LMS'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'SAP-owned corporate LMS partner program',
    faq: [
      { question: 'What is the partner program?', answer: 'Referral and reseller partnerships for corporate training solutions with commission structures by deal.' },
      { question: 'Who uses Litmos?', answer: 'Mid to large enterprises, franchises, and companies needing compliance and skills training.' }
    ]
  },
  {
    id: '805',
    slug: 'ispring-affiliate',
    name: 'iSpring Affiliate Program',
    category: 'affiliate',
    founded_year: 2001,
    hq_location: 'Remote',
    website: 'https://www.ispringsolutions.com/affiliates',
    products_summary: 'eLearning authoring toolkit and LMS with PowerPoint-based course creation, quizzes, simulations, and video lectures.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['25% recurring commission', 'PowerPoint integration', 'Authoring + LMS bundle', 'Affordable pricing'],
    cons: ['Windows-focused tools', 'Corporate market', 'Smaller brand in US'],
    quick_facts: {
      'Founded': '2001',
      'Commission Rate': '25% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Authoring + LMS'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'PowerPoint-based course authoring with 25% recurring',
    faq: [
      { question: 'What makes iSpring unique?', answer: 'Convert PowerPoint presentations into interactive eLearning courses with quizzes and tracking.' },
      { question: 'What are typical earnings?', answer: 'Subscriptions from $370-$970/year earn $92-$242 annually, paid monthly as recurring.' }
    ]
  },
  {
    id: '806',
    slug: 'articulate-affiliate',
    name: 'Articulate Affiliate Program',
    category: 'affiliate',
    founded_year: 2002,
    hq_location: 'New York, NY, USA',
    website: 'https://articulate.com/partners',
    products_summary: 'Industry-leading eLearning authoring tools Storyline and Rise for creating interactive courses without programming.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.7,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['Market leader', 'Strong brand recognition', 'Excellent product', 'Large community'],
    cons: ['Limited affiliate structure', 'No public commission rates', 'Application required'],
    quick_facts: {
      'Founded': '2002',
      'Commission Rate': 'Partner-negotiated',
      'Cookie Duration': 'Varies',
      'Platform': 'Authoring tools'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Industry-leading eLearning authoring tool partner',
    faq: [
      { question: 'Does Articulate have an affiliate program?', answer: 'They have a partner program for resellers and solution providers, not traditional affiliate marketing.' },
      { question: 'What are Articulate products?', answer: 'Articulate 360 includes Storyline, Rise, and other tools for $1,299/year per user.' }
    ]
  },
  {
    id: '807',
    slug: 'camtasia-affiliate',
    name: 'Camtasia Affiliate Program',
    category: 'affiliate',
    founded_year: 2002,
    hq_location: 'Okemos, MI, USA',
    website: 'https://www.techsmith.com/affiliates.html',
    products_summary: 'Screen recording and video editing software for creating tutorials, courses, and presentations with annotations and effects.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['20% commission rate', 'Popular screen recorder', 'Widely used tool', 'Quality product'],
    cons: ['One-time purchase model', 'Software not SaaS', 'Lower renewal commissions'],
    quick_facts: {
      'Founded': '2002',
      'Commission Rate': '20% one-time',
      'Cookie Duration': '45 days',
      'Platform': 'Impact'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Popular screen recording software affiliate program',
    faq: [
      { question: 'What products are included?', answer: 'Camtasia, Snagit, and other TechSmith products earn 20% commission on purchases.' },
      { question: 'What are typical earnings?', answer: 'Camtasia at $249 earns $50, Snagit at $49.99 earns $10 per sale.' }
    ]
  },
  {
    id: '808',
    slug: 'screenflow-affiliate',
    name: 'ScreenFlow Affiliate Program',
    category: 'affiliate',
    founded_year: 2008,
    hq_location: 'Woodland Hills, CA, USA',
    website: 'https://www.telestream.net/screenflow/affiliates.htm',
    products_summary: 'Mac screen recording and video editing software for creating professional tutorials, demos, and training videos.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.4,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['25% commission', 'Premium Mac software', 'Professional quality', 'Loyal user base'],
    cons: ['Mac only limits audience', 'One-time purchase', 'Smaller market than Camtasia'],
    quick_facts: {
      'Founded': '2008',
      'Commission Rate': '25% one-time',
      'Cookie Duration': '60 days',
      'Platform': 'Mac only'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Premium Mac screen recording with 25% commissions',
    faq: [
      { question: 'What is the commission structure?', answer: '25% one-time commission on ScreenFlow purchases and upgrades.' },
      { question: 'What can I earn per sale?', answer: 'ScreenFlow costs $169, earning $42.25 per sale.' }
    ]
  },
  {
    id: '809',
    slug: 'riverside-fm-affiliate',
    name: 'Riverside.fm Affiliate Program',
    category: 'affiliate',
    founded_year: 2020,
    hq_location: 'Tel Aviv, Israel',
    website: 'https://riverside.fm/affiliates',
    products_summary: 'High-quality podcast and video recording platform with local recording, studio-quality audio, and multi-track editing.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.8,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['30% recurring lifetime', 'Fast-growing platform', 'Quality differentiator', 'Strong podcaster community'],
    cons: ['Competitive podcast space', 'Newer company', 'Premium pricing'],
    quick_facts: {
      'Founded': '2020',
      'Commission Rate': '30% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Podcast/Video'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Studio-quality podcast recording with 30% recurring',
    faq: [
      { question: 'What makes Riverside different?', answer: 'Records locally on each participant\'s device for studio-quality 4K video and 48kHz audio, even with poor internet.' },
      { question: 'What can I earn?', answer: 'Plans from $19-$79/month earn $5.70-$23.70+ monthly recurring per customer for life.' }
    ]
  },
  {
    id: '810',
    slug: 'restream-affiliate',
    name: 'Restream Affiliate Program',
    category: 'affiliate',
    founded_year: 2015,
    hq_location: 'Austin, TX, USA',
    website: 'https://restream.io/affiliates',
    products_summary: 'Multi-streaming platform for broadcasting live to 30+ platforms simultaneously including YouTube, Facebook, Twitch, and LinkedIn.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.7,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['25% recurring lifetime', 'Clear use case', 'Free tier available', 'Growing live streaming'],
    cons: ['Competitive streaming market', 'Platform dependency', 'Mid-range pricing'],
    quick_facts: {
      'Founded': '2015',
      'Commission Rate': '25% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Multi-streaming'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Multi-stream to 30+ platforms with 25% recurring',
    faq: [
      { question: 'What is multi-streaming?', answer: 'Broadcast your live stream simultaneously to multiple platforms like YouTube, Facebook, Twitch, LinkedIn, etc.' },
      { question: 'What are typical earnings?', answer: 'Plans from $19-$199/month earn $4.75-$49.75+ monthly recurring per customer.' }
    ]
  },
  {
    id: '811',
    slug: 'streamyard-affiliate',
    name: 'StreamYard Affiliate Program',
    category: 'affiliate',
    founded_year: 2018,
    hq_location: 'Remote',
    website: 'https://streamyard.com/affiliates',
    products_summary: 'Browser-based live streaming studio for interviews, webinars, and broadcasts with guests, overlays, and multi-destination streaming.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.8,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['25% recurring lifetime', 'No download required', 'Easy for guests', 'Popular with creators'],
    cons: ['Browser limitations', 'Competitive market', 'Mid-tier pricing'],
    quick_facts: {
      'Founded': '2018',
      'Commission Rate': '25% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Browser streaming'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Browser-based live streaming with 25% recurring',
    faq: [
      { question: 'Why is StreamYard popular?', answer: 'Works entirely in browser with no downloads, making it incredibly easy for guests to join your stream.' },
      { question: 'What can I earn?', answer: 'Plans from $20-$149/month earn $5-$37.25+ monthly recurring per customer for life.' }
    ]
  },
  {
    id: '812',
    slug: 'ecamm-affiliate',
    name: 'Ecamm Affiliate Program',
    category: 'affiliate',
    founded_year: 2002,
    hq_location: 'Ashland, NH, USA',
    website: 'https://www.ecamm.com/affiliates/',
    products_summary: 'Mac live streaming software for Facebook, YouTube, and more with professional features, interviews, and screen sharing.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% commission', 'Premium Mac software', 'Strong features', 'Loyal community'],
    cons: ['Mac only', 'One-time purchase', 'Limited to Apple users'],
    quick_facts: {
      'Founded': '2002',
      'Commission Rate': '30% one-time',
      'Cookie Duration': '90 days',
      'Platform': 'Mac only'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Premium Mac live streaming with 30% commissions',
    faq: [
      { question: 'What is the pricing model?', answer: 'One-time purchase at $169, or monthly subscription at $20/month ($240/year).' },
      { question: 'What can I earn?', answer: 'One-time purchase earns $50.70, annual subscriptions earn $72 per sale.' }
    ]
  },
  {
    id: '813',
    slug: 'obs-studio-support',
    name: 'OBS Studio',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'Remote (Open Source)',
    website: 'https://obsproject.com/',
    products_summary: 'Free and open-source streaming and recording software for Windows, Mac, and Linux with unlimited scenes and sources.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'No affiliate program (free/open-source)',
    overall_rating: 4.0,
    residual_rating: 0,
    simplicity_rating: 3.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['Completely free', 'Open source', 'Powerful features', 'Large community'],
    cons: ['No affiliate program', 'Steeper learning curve', 'No official support'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': 'N/A',
      'Cost': 'Free',
      'Platform': 'Cross-platform'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Free open-source streaming software (no affiliate)',
    faq: [
      { question: 'Can I earn from promoting OBS?', answer: 'No direct commissions, but you can monetize tutorials, courses, or services around OBS Studio.' },
      { question: 'Why include OBS here?', answer: 'Important to know as alternative to paid tools - creates opportunities for education and services.' }
    ]
  },
  {
    id: '814',
    slug: 'wirecast-affiliate',
    name: 'Wirecast Affiliate Program',
    category: 'affiliate',
    founded_year: 2007,
    hq_location: 'Woodland Hills, CA, USA',
    website: 'https://www.telestream.net/affiliates/',
    products_summary: 'Professional live streaming production software with multi-camera support, graphics, transitions, and encoding for broadcasts.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 3.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Professional software', '20% commission', 'High price points', 'Broadcast quality'],
    cons: ['One-time purchase', 'Professional market only', 'Higher barrier to entry'],
    quick_facts: {
      'Founded': '2007',
      'Commission Rate': '20% one-time',
      'Cookie Duration': '60 days',
      'Platform': 'Professional'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Professional broadcast software affiliate program',
    faq: [
      { question: 'What are Wirecast prices?', answer: 'Wirecast Studio at $599 and Wirecast Pro at $799 for perpetual licenses.' },
      { question: 'What can I earn?', answer: '20% commission means $120 for Studio and $160 for Pro sales.' }
    ]
  },
  {
    id: '815',
    slug: 'vmix-affiliate',
    name: 'vMix Affiliate Program',
    category: 'affiliate',
    founded_year: 2010,
    hq_location: 'Perth, Australia',
    website: 'https://www.vmix.com/affiliates/',
    products_summary: 'Live video production software for Windows with mixing, switching, recording, and streaming up to 4K with built-in titles and effects.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'One-time affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.0,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['25% commission rate', 'Competitive pricing', 'Powerful features', 'Free basic version'],
    cons: ['Windows only', 'One-time purchase', 'Australian company'],
    quick_facts: {
      'Founded': '2010',
      'Commission Rate': '25% one-time',
      'Cookie Duration': '90 days',
      'Platform': 'Windows'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Affordable professional live production software',
    faq: [
      { question: 'What are vMix editions?', answer: 'Free Basic, HD $60, 4K $350, Pro $700, and Max $1,200 with increasing capabilities.' },
      { question: 'What can I earn?', answer: '25% commission means $15-$300 per sale depending on edition purchased.' }
    ]
  },
  {
    id: '816',
    slug: 'crowdcast-affiliate',
    name: 'Crowdcast Affiliate Program',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'Remote',
    website: 'https://www.crowdcast.io/affiliates',
    products_summary: 'Live video platform for webinars, Q&As, workshops, and online events with registration, chat, polls, and replay hosting.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['20% recurring lifetime', 'Simple for attendees', 'Good engagement features', 'Growing platform'],
    cons: ['Smaller brand', 'Competitive webinar space', 'Mid-tier pricing'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': '20% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Webinar'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Webinar platform with 20% lifetime recurring',
    faq: [
      { question: 'What makes Crowdcast different?', answer: 'Focus on engagement and simplicity - attendees join in browser without downloads or complicated setup.' },
      { question: 'What are typical earnings?', answer: 'Plans from $29-$99/month earn $5.80-$19.80+ monthly recurring per customer.' }
    ]
  },
  {
    id: '817',
    slug: 'hopin-affiliate',
    name: 'Hopin Affiliate Program',
    category: 'affiliate',
    founded_year: 2019,
    hq_location: 'London, UK',
    website: 'https://hopin.com/partners',
    products_summary: 'Virtual and hybrid event platform with stages, sessions, networking, expo booths, and engagement tools for conferences.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.7,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Major event platform', 'High deal values', 'Enterprise clients', 'Feature-rich'],
    cons: ['Partner not affiliate', 'Complex pricing', 'Event-specific market'],
    quick_facts: {
      'Founded': '2019',
      'Commission Rate': 'Partner-negotiated',
      'Cookie Duration': 'Varies',
      'Platform': 'Virtual events'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Leading virtual event platform partner program',
    faq: [
      { question: 'Does Hopin have an affiliate program?', answer: 'They have a partner program for agencies and consultants, not traditional affiliate marketing.' },
      { question: 'What are typical event costs?', answer: 'Events range from free tier to $1,000s for enterprise conferences with thousands of attendees.' }
    ]
  },
  {
    id: '818',
    slug: 'airmeet-affiliate',
    name: 'Airmeet Affiliate Program',
    category: 'affiliate',
    founded_year: 2019,
    hq_location: 'Bangalore, India',
    website: 'https://www.airmeet.com/affiliates',
    products_summary: 'Virtual event platform for conferences, meetups, and webinars with networking tables, social lounge, and interactive features.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['15% recurring commission', 'Unique networking features', 'Competitive pricing', 'Growing platform'],
    cons: ['Smaller brand recognition', 'Event platform competition', 'Lower commission rate'],
    quick_facts: {
      'Founded': '2019',
      'Commission Rate': '15% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Virtual events'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Virtual events with networking tables and 15% recurring',
    faq: [
      { question: 'What makes Airmeet unique?', answer: 'Social lounge and networking tables that recreate the hallway conversations of in-person events.' },
      { question: 'What are typical earnings?', answer: 'Plans from $99-$999/month earn $14.85-$149.85+ monthly recurring per customer.' }
    ]
  },
  {
    id: '819',
    slug: 'remo-affiliate',
    name: 'Remo Affiliate Program',
    category: 'affiliate',
    founded_year: 2018,
    hq_location: 'Remote',
    website: 'https://remo.co/affiliates/',
    products_summary: 'Virtual event platform with interactive floor plans and tables for networking, workshops, and conferences that feel personal.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['20% recurring commission', 'Unique table concept', 'Interactive networking', 'Intimate events'],
    cons: ['Niche use case', 'Smaller market', 'Learning curve'],
    quick_facts: {
      'Founded': '2018',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Virtual events'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Interactive virtual events with visual tables',
    faq: [
      { question: 'How does Remo work?', answer: 'Visual floor plan with tables where attendees can move around, sit at tables, and have video conversations.' },
      { question: 'What can I earn?', answer: 'Plans from $250-$2,000/month for events earn $50-$400+ monthly recurring per customer.' }
    ]
  },
  {
    id: '820',
    slug: 'gather-town-affiliate',
    name: 'Gather.town Affiliate Program',
    category: 'affiliate',
    founded_year: 2020,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://gather.town/affiliates',
    products_summary: 'Virtual space platform with customizable 2D worlds for remote work, events, and social gatherings with proximity video chat.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['15% recurring commission', 'Unique gaming approach', 'Free tier available', 'Viral potential'],
    cons: ['Niche product', 'Requires buy-in', 'Limited use cases'],
    quick_facts: {
      'Founded': '2020',
      'Commission Rate': '15% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Virtual spaces'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Gamified virtual office with 15% recurring',
    faq: [
      { question: 'What is Gather.town?', answer: 'Create 2D video game-like virtual spaces where proximity video chat activates as you walk near others.' },
      { question: 'What are typical earnings?', answer: 'Business plans from $3-$7 per user/month, so teams of 25-100 earn $11.25-$105+ monthly.' }
    ]
  },
  {
    id: '821',
    slug: 'spatialchat-affiliate',
    name: 'SpatialChat Affiliate Program',
    category: 'affiliate',
    founded_year: 2020,
    hq_location: 'Remote',
    website: 'https://spatial.chat/affiliates',
    products_summary: 'Virtual event platform with spatial audio where video conversations happen based on proximity in a 2D space.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.4,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['20% recurring commission', 'Spatial audio USP', 'Natural networking', 'Free tier'],
    cons: ['Very niche', 'Smaller brand', 'Limited awareness'],
    quick_facts: {
      'Founded': '2020',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Virtual events'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Spatial audio virtual events with 20% recurring',
    faq: [
      { question: 'What is spatial audio?', answer: 'Audio volume and direction changes based on distance and position, creating natural conversation dynamics.' },
      { question: 'What can I earn?', answer: 'Event plans from $50-$500+ per event earn $10-$100+ per customer event.' }
    ]
  },
  {
    id: '822',
    slug: 'around-affiliate',
    name: 'Around Affiliate Program',
    category: 'affiliate',
    founded_year: 2020,
    hq_location: 'Remote',
    website: 'https://www.around.co/affiliates',
    products_summary: 'Video calling designed for collaboration with floating bubble heads, screen sharing, and features that reduce meeting fatigue.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['20% recurring commission', 'Unique design approach', 'Anti-fatigue features', 'Modern interface'],
    cons: ['Competitive video market', 'Zoom dominance', 'Smaller adoption'],
    quick_facts: {
      'Founded': '2020',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Video calling'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Modern video calls with less fatigue and 20% recurring',
    faq: [
      { question: 'What makes Around different?', answer: 'Floating video bubbles, echo cancellation, auto-framing, and design specifically to reduce video call fatigue.' },
      { question: 'What are the earnings?', answer: 'Pro plans at $12/user/month for teams of 5-20 earn $12-$48+ monthly recurring.' }
    ]
  },
  {
    id: '823',
    slug: 'luma-affiliate',
    name: 'Luma Affiliate Program',
    category: 'affiliate',
    founded_year: 2019,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://lu.ma/affiliates',
    products_summary: 'Beautiful event pages and calendar with email marketing, registration, payments, and community features for organizers.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['20% recurring commission', 'Beautiful design', 'Free tier generous', 'Growing community'],
    cons: ['Newer platform', 'Limited advanced features', 'Smaller brand'],
    quick_facts: {
      'Founded': '2019',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Events + Calendar'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Beautiful event pages with 20% recurring',
    faq: [
      { question: 'What is Luma best for?', answer: 'Community events, workshops, meetups, and speaker series with gorgeous event pages and calendar.' },
      { question: 'What can I earn?', answer: 'Pro plans at $49-$149/month for organizers earn $9.80-$29.80+ monthly recurring.' }
    ]
  },
  {
    id: '824',
    slug: 'eventbrite-affiliate',
    name: 'Eventbrite Affiliate Program',
    category: 'affiliate',
    founded_year: 2006,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://www.eventbrite.com/affiliates/',
    products_summary: 'Event management and ticketing platform for creating, promoting, and managing in-person and online events of all sizes.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Revenue share affiliate',
    overall_rating: 3.6,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['Brand recognition', 'Large platform', 'Free events option', 'Wide use cases'],
    cons: ['Lower commission rate', 'Complex tracking', 'Limited to ticket fees'],
    quick_facts: {
      'Founded': '2006',
      'Commission Rate': '10% of fees',
      'Cookie Duration': '30 days',
      'Platform': 'Impact'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Major event ticketing platform affiliate program',
    faq: [
      { question: 'How does commission work?', answer: 'Earn 10% of Eventbrite\'s service fees (not ticket price), so earnings vary by event pricing and volume.' },
      { question: 'What are typical earnings?', answer: 'On $1,000 in ticket sales with 3.5% fee ($35), you earn $3.50 per event created through your link.' }
    ]
  },
  {
    id: '825',
    slug: 'splash-affiliate',
    name: 'Splash Affiliate Program',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'New York, NY, USA',
    website: 'https://splashthat.com/partners',
    products_summary: 'Event marketing platform for creating branded event experiences, managing invites, and tracking attendee engagement.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['Enterprise focus', 'Design-forward', 'Brand integration', 'Marketing automation'],
    cons: ['Partner not affiliate', 'Enterprise pricing', 'Smaller DIY market'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': 'Partner-based',
      'Cookie Duration': 'Varies',
      'Platform': 'Event marketing'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Enterprise event marketing partner program',
    faq: [
      { question: 'Does Splash have affiliates?', answer: 'They have a partner program for agencies and event planners, not traditional affiliate marketing.' },
      { question: 'Who uses Splash?', answer: 'Enterprise brands like Netflix and Uber for creating branded event experiences and field marketing.' }
    ]
  },
  {
    id: '826',
    slug: 'bizzabo-affiliate',
    name: 'Bizzabo Affiliate Program',
    category: 'affiliate',
    founded_year: 2011,
    hq_location: 'New York, NY, USA',
    website: 'https://www.bizzabo.com/partners',
    products_summary: 'Enterprise event management platform for conferences with registration, mobile apps, networking, and analytics.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Enterprise platform', 'High contract values', 'Comprehensive features', 'Strong brand'],
    cons: ['Enterprise only', 'Long sales cycles', 'Partner not affiliate'],
    quick_facts: {
      'Founded': '2011',
      'Commission Rate': 'Partner-negotiated',
      'Cookie Duration': 'Varies',
      'Platform': 'Enterprise events'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Enterprise event platform partner program',
    faq: [
      { question: 'What is the partner program?', answer: 'Referral and reseller partnerships for enterprise event management with custom commission structures.' },
      { question: 'What are typical deal sizes?', answer: 'Enterprise conferences range from $10,000 to $100,000+ annually depending on event size and features.' }
    ]
  },
  {
    id: '827',
    slug: 'cvent-affiliate',
    name: 'Cvent Affiliate Program',
    category: 'affiliate',
    founded_year: 1999,
    hq_location: 'Tysons Corner, VA, USA',
    website: 'https://www.cvent.com/en/partners',
    products_summary: 'Industry-leading event management and venue sourcing platform for enterprise meetings, conferences, and hospitality.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.7,
    residual_rating: 3.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Market leader', 'Public company', 'Massive enterprise market', 'Comprehensive platform'],
    cons: ['Enterprise only', 'Complex sales', 'Partner program not affiliate'],
    quick_facts: {
      'Founded': '1999',
      'Commission Rate': 'Partner-based',
      'Cookie Duration': 'Varies',
      'Platform': 'Enterprise'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Enterprise event leader partner program',
    faq: [
      { question: 'Does Cvent have affiliates?', answer: 'Partner program for resellers and solution providers, not traditional affiliate marketing.' },
      { question: 'Who uses Cvent?', answer: 'Fortune 500 companies, major hotels, convention centers, and large-scale event planners.' }
    ]
  },
  {
    id: '828',
    slug: 'whova-affiliate',
    name: 'Whova Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'San Diego, CA, USA',
    website: 'https://whova.com/pages/whova-affiliates/',
    products_summary: 'Event management and mobile app platform for conferences with networking, agenda, exhibitors, and engagement tools.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['15% recurring commission', 'Conference focused', 'Great mobile app', 'Competitive pricing'],
    cons: ['Event-specific market', 'Lower commission rate', 'Annual events common'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': '15% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Conference + App'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Conference app platform with 15% recurring',
    faq: [
      { question: 'Who uses Whova?', answer: 'Conference organizers, associations, and event planners for attendee engagement and mobile apps.' },
      { question: 'What are typical earnings?', answer: 'Events from $1,000-$10,000+ per conference earn $150-$1,500+ per event created.' }
    ]
  },
  {
    id: '829',
    slug: 'swoogo-affiliate',
    name: 'Swoogo Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'Seattle, WA, USA',
    website: 'https://swoogo.com/partners/',
    products_summary: 'Flexible event management platform for registration, check-in, mobile apps, and analytics for corporate events.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['Flexible platform', 'Corporate events', 'Custom branding', 'Good support'],
    cons: ['Partner not traditional affiliate', 'Mid-market focus', 'Less brand recognition'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': 'Partner-based',
      'Cookie Duration': 'Varies',
      'Platform': 'Corporate events'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Corporate event platform partner program',
    faq: [
      { question: 'What is the partner program?', answer: 'Referral partnerships for agencies and planners managing corporate events and conferences.' },
      { question: 'Who uses Swoogo?', answer: 'Enterprise companies for user conferences, sales kickoffs, and multi-session corporate events.' }
    ]
  },
  {
    id: '830',
    slug: 'hubilo-affiliate',
    name: 'Hubilo Affiliate Program',
    category: 'affiliate',
    founded_year: 2015,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://hubilo.com/partners/',
    products_summary: 'Hybrid event platform for virtual, in-person, and hybrid conferences with engagement tools and networking features.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.6,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Hybrid event capability', 'Growing platform', 'Good engagement tools', 'Modern interface'],
    cons: ['Partner not affiliate', 'Competitive market', 'Newer brand'],
    quick_facts: {
      'Founded': '2015',
      'Commission Rate': 'Partner-based',
      'Cookie Duration': 'Varies',
      'Platform': 'Hybrid events'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Hybrid event platform partner program',
    faq: [
      { question: 'Does Hubilo have affiliates?', answer: 'Partner program for event agencies and planners, not traditional affiliate commissions.' },
      { question: 'What are hybrid events?', answer: 'Events with both in-person and virtual attendance, managed through unified platform.' }
    ]
  },
  {
    id: '831',
    slug: 'accelevents-affiliate',
    name: 'Accelevents Affiliate Program',
    category: 'affiliate',
    founded_year: 2015,
    hq_location: 'San Francisco, CA, USA',
    website: 'https://www.accelevents.com/affiliates',
    products_summary: 'All-in-one virtual and hybrid event platform with registration, mobile apps, networking, and sponsor management.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['20% recurring commission', 'Hybrid capabilities', 'All-in-one platform', 'Competitive pricing'],
    cons: ['Smaller brand', 'Crowded market', 'Event-specific'],
    quick_facts: {
      'Founded': '2015',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '90 days',
      'Platform': 'Hybrid events'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Hybrid event platform with 20% recurring',
    faq: [
      { question: 'What makes Accelevents different?', answer: 'Comprehensive all-in-one platform for registration, mobile apps, virtual event, and sponsor management.' },
      { question: 'What can I earn?', answer: 'Event packages from $500-$5,000+ per event earn $100-$1,000+ per customer event.' }
    ]
  },
  {
    id: '832',
    slug: 'bigmarker-affiliate',
    name: 'BigMarker Affiliate Program',
    category: 'affiliate',
    founded_year: 2011,
    hq_location: 'Remote',
    website: 'https://www.bigmarker.com/affiliates/',
    products_summary: 'Webinar and virtual event platform with custom branding, registration pages, automated webinars, and marketing tools.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.6,
    residual_rating: 4.0,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% recurring lifetime', 'White-label options', 'Automated webinars', 'Strong features'],
    cons: ['Competitive webinar space', 'Mid-tier pricing', 'Brand awareness'],
    quick_facts: {
      'Founded': '2011',
      'Commission Rate': '30% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Webinars + Events'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Webinar platform with 30% lifetime recurring',
    faq: [
      { question: 'What makes BigMarker stand out?', answer: 'Combines live webinars, automated evergreen webinars, virtual conferences, and custom branding in one platform.' },
      { question: 'What are typical earnings?', answer: 'Plans from $79-$399/month earn $23.70-$119.70+ monthly recurring per customer for life.' }
    ]
  },
  {
    id: '833',
    slug: 'gotowebinar-affiliate',
    name: 'GoToWebinar Affiliate Program',
    category: 'affiliate',
    founded_year: 2006,
    hq_location: 'Boston, MA, USA',
    website: 'https://www.goto.com/partners',
    products_summary: 'Enterprise webinar platform from GoTo with polls, Q&A, analytics, and integrations for professional online events.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.7,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Established brand', 'Enterprise trust', 'Reliable platform', 'Strong features'],
    cons: ['Partner not affiliate', 'Premium pricing', 'Older interface'],
    quick_facts: {
      'Founded': '2006',
      'Commission Rate': 'Partner-based',
      'Cookie Duration': 'Varies',
      'Platform': 'GoTo/LogMeIn'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Established enterprise webinar partner program',
    faq: [
      { question: 'Does GoToWebinar have affiliates?', answer: 'Partner program for resellers and agencies, not traditional affiliate marketing structure.' },
      { question: 'Who uses GoToWebinar?', answer: 'Enterprise companies, training organizations, and businesses requiring reliable professional webinars.' }
    ]
  },
  {
    id: '834',
    slug: 'livestorm-affiliate',
    name: 'Livestorm Affiliate Program',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'Paris, France',
    website: 'https://livestorm.co/affiliates',
    products_summary: 'Browser-based webinar and video engagement platform with no downloads required for attendees, automation, and CRM integrations.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Recurring affiliate commissions',
    overall_rating: 3.7,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['30% recurring lifetime', 'No download required', 'Modern platform', 'Great UX'],
    cons: ['European company', 'Newer brand in US', 'Competitive space'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': '30% lifetime',
      'Cookie Duration': '90 days',
      'Platform': 'Browser webinar'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Browser webinar platform with 30% lifetime recurring',
    faq: [
      { question: 'Why choose Livestorm?', answer: 'Completely browser-based with no downloads, making it frictionless for attendees to join webinars.' },
      { question: 'What can I earn?', answer: 'Plans from $89-$399/month earn $26.70-$119.70+ monthly recurring per customer for life.' }
    ]
  },
  {
    id: '835',
    slug: 'webex-affiliate',
    name: 'Webex Affiliate Program',
    category: 'affiliate',
    founded_year: 1995,
    hq_location: 'San Jose, CA, USA',
    website: 'https://www.webex.com/partners.html',
    products_summary: 'Cisco enterprise video conferencing, webinars, and collaboration platform with security and integration for business.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Partner referral program',
    overall_rating: 3.7,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Cisco brand trust', 'Enterprise security', 'Established platform', 'Global presence'],
    cons: ['Partner not affiliate', 'Enterprise complexity', 'Older reputation'],
    quick_facts: {
      'Founded': '1995',
      'Commission Rate': 'Partner-based',
      'Cookie Duration': 'Varies',
      'Platform': 'Cisco enterprise'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Cisco enterprise collaboration partner program',
    faq: [
      { question: 'Does Webex have affiliates?', answer: 'Partner program for resellers and solution providers, not traditional affiliate marketing.' },
      { question: 'Who uses Webex?', answer: 'Large enterprises, government, healthcare, and security-conscious organizations requiring Cisco-grade solutions.' }
    ]
  }
];
