import { Company } from '@/types';

export const companiesBatchC3: Company[] = [
  {
    id: '596',
    slug: 'activecampaign-affiliate',
    name: 'ActiveCampaign Affiliate',
    category: 'affiliate',
    founded_year: 2003,
    hq_location: 'Chicago, Illinois, USA',
    website: 'https://www.activecampaign.com/partner',
    products_summary: 'Email marketing automation platform with CRM, offering recurring commission on customer subscriptions. Partners earn 20-30% monthly recurring revenue for life of customer.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.5,
    residual_rating: 4.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['22 years in business — Chicago', 'Per-customer residual $6-45/mo (20-30% lifetime)', '90-day cookie window', 'High conversion rates'],
    cons: ['Competitive email market', 'Requires marketing knowledge', '$50 payout threshold'],
    quick_facts: {
      'Founded': '2003',
      'Commission Rate': '20-30% recurring',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Recurring commissions on email automation',
    faq: [
      { question: 'How long do I earn commissions?', answer: 'You earn 20-30% monthly recurring commission for as long as your referred customer remains an ActiveCampaign subscriber.' },
      { question: 'What is the minimum payout?', answer: 'The minimum payout threshold is $50, paid monthly via PayPal or bank transfer.' }
    ]
  },
  {
    id: '597',
    slug: 'getresponse-affiliate',
    name: 'GetResponse Affiliate',
    category: 'affiliate',
    founded_year: 1998,
    hq_location: 'Gdansk, Poland',
    website: 'https://www.getresponse.com/affiliate',
    products_summary: 'Email marketing and marketing automation platform offering both one-time and recurring commission structures for affiliates.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['27 years in business — Poland', 'Per-customer residual $8-60/mo (40-60% for 12mo)', '120-day cookie', 'Dedicated affiliate manager'],
    cons: ['12-month commission limit', 'Must choose commission type', 'International payment delays'],
    quick_facts: {
      'Founded': '1998',
      'Commission Rate': '$100 flat or 33% recurring',
      'Cookie Duration': '120 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Flexible commission structure for marketers',
    faq: [
      { question: 'Can I switch commission types?', answer: 'You must choose between one-time $100 commission or 33% recurring when you join. This choice cannot be changed later.' },
      { question: 'How are payments made?', answer: 'Payments are made via PayPal, wire transfer, or Payoneer once you reach the $50 minimum threshold.' }
    ]
  },
  {
    id: '598',
    slug: 'aweber-affiliate',
    name: 'AWeber Affiliate',
    category: 'affiliate',
    founded_year: 1998,
    hq_location: 'Chalfont, Pennsylvania, USA',
    website: 'https://www.aweber.com/affiliate.htm',
    products_summary: 'Email marketing platform for small businesses with 30% recurring commission program for affiliates promoting landing pages and email tools.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['27 years in business — Pennsylvania', 'Per-customer residual $6-40/mo (30-50% lifetime)', '365-day cookie — industry leading', 'Easy to promote'],
    cons: ['Declining market share', 'ConvertKit/Beehiiv competition', 'Limited advanced features'],
    quick_facts: {
      'Founded': '1998',
      'Commission Rate': '30% recurring',
      'Cookie Duration': '365 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Year-long cookie with recurring income',
    faq: [
      { question: 'How long does the cookie last?', answer: 'AWeber offers an industry-leading 365-day cookie duration, giving you a full year to earn credit for referrals.' },
      { question: 'When do I get paid?', answer: 'Commissions are paid monthly via PayPal once you reach the $30 minimum threshold.' }
    ]
  },
  {
    id: '599',
    slug: 'mailchimp-partner',
    name: 'Mailchimp Partner Program',
    category: 'affiliate',
    founded_year: 2001,
    hq_location: 'Atlanta, Georgia, USA',
    website: 'https://mailchimp.com/partners/',
    products_summary: 'Email and marketing automation platform with tiered partner program offering revenue share for agencies and consultants who refer clients.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.0,
    residual_rating: 3.0,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.0,
    pros: ['Recognized brand name', 'Good free tier for referrals', 'Marketing resources', 'Agency-focused support'],
    cons: ['No public commission rates', 'Requires approval', 'Lower payouts than competitors'],
    quick_facts: {
      'Founded': '2001',
      'Commission Rate': 'Varies by tier',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Partner program for agencies and consultants',
    faq: [
      { question: 'Is this open to individual affiliates?', answer: 'Mailchimp focuses on agency partners and consultants rather than traditional affiliates. Individual marketers may find limited opportunities.' },
      { question: 'What are the commission rates?', answer: 'Commission rates are not publicly disclosed and vary based on partner tier and client volume.' }
    ]
  },
  {
    id: '600',
    slug: 'hubspot-affiliate',
    name: 'HubSpot Affiliate Program',
    category: 'affiliate',
    founded_year: 2006,
    hq_location: 'Cambridge, Massachusetts, USA',
    website: 'https://www.hubspot.com/partners/affiliates',
    products_summary: 'CRM and inbound marketing platform offering 30% recurring commission for 12 months on customer subscriptions, plus bonus tiers for volume.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['19 years in business — Cambridge', 'Per-customer residual $15-240/mo (30% for 12mo)', 'High-ticket CRM commissions', 'Strong brand recognition'],
    cons: ['12-month commission limit', 'Competitive approval process', 'Complex product to explain'],
    quick_facts: {
      'Founded': '2006',
      'Commission Rate': '30% for 12 months',
      'Cookie Duration': '180 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'High-value CRM commissions with volume bonuses',
    faq: [
      { question: 'How long do commissions last?', answer: 'You earn 30% commission for the first 12 months of each customer subscription, with potential volume bonuses.' },
      { question: 'What is the average commission?', answer: 'With HubSpot plans ranging from $50-$3,200/month, affiliates can earn $15-$960 per month per customer for 12 months.' }
    ]
  },
  {
    id: '601',
    slug: 'salesforce-partner',
    name: 'Salesforce Partner Program',
    category: 'affiliate',
    founded_year: 1999,
    hq_location: 'San Francisco, California, USA',
    website: 'https://partners.salesforce.com/',
    products_summary: 'Enterprise CRM platform with referral and reseller partner programs, offering revenue share on large enterprise deals and ongoing subscriptions.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['High-value enterprise deals', 'Strong brand leader', 'Extensive training', 'Multiple partner tiers'],
    cons: ['Complex partner structure', 'Requires business credentials', 'Long sales cycles'],
    quick_facts: {
      'Founded': '1999',
      'Commission Rate': 'Varies by partner tier',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Enterprise CRM partnership opportunities',
    faq: [
      { question: 'Who can become a Salesforce partner?', answer: 'Salesforce partners are typically agencies, consultants, and resellers with established businesses, not individual affiliates.' },
      { question: 'What are the requirements?', answer: 'Partners must complete training, demonstrate expertise, and often need existing client relationships to qualify for the program.' }
    ]
  },
  {
    id: '602',
    slug: 'monday-affiliate',
    name: 'Monday.com Affiliate',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'Tel Aviv, Israel',
    website: 'https://monday.com/p/affiliate-program',
    products_summary: 'Work operating system and project management platform offering generous recurring commissions for referring teams and organizations.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['High conversion rates', 'Professional dashboards', 'Growing market demand', 'Multi-seat opportunities'],
    cons: ['Competitive space', 'Requires B2B audience', '30-day cookie only'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': 'Up to $250 per sale',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Project management with multi-seat commissions',
    faq: [
      { question: 'How much can I earn per referral?', answer: 'Commissions range from $50 to $250+ per sale depending on the plan and number of seats purchased by your referral.' },
      { question: 'Is this recurring?', answer: 'Monday.com typically offers one-time commissions per sale rather than ongoing recurring payments.' }
    ]
  },
  {
    id: '603',
    slug: 'notion-affiliate',
    name: 'Notion Affiliate Program',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.notion.so/affiliates',
    products_summary: 'All-in-one workspace combining notes, tasks, wikis, and databases with affiliate program offering $10 per paying customer plus credit bonuses.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 3.0,
    pros: ['9 years in business — San Francisco', 'Per-customer residual $5-50/mo (50% for 12mo)', 'Viral product growth', 'Free tier drives conversions'],
    cons: ['12-month commission limit', 'Many users stay on free tier', 'Competitive workspace market'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': '$10 per customer',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Popular workspace tool with growing community',
    faq: [
      { question: 'Is the commission recurring?', answer: 'No, Notion pays a one-time $10 commission per new paying customer, not recurring monthly payments.' },
      { question: 'What about Notion credits?', answer: 'Affiliates also earn $5 in Notion credits for each paying customer referred, which can be used for your own subscription.' }
    ]
  },
  {
    id: '604',
    slug: 'airtable-affiliate',
    name: 'Airtable Affiliate Program',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'San Francisco, California, USA',
    website: 'https://airtable.com/partners/affiliates',
    products_summary: 'Cloud collaboration platform combining spreadsheet and database functionality, offering commission on paid plan referrals for teams and enterprises.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Strong product-market fit', 'Professional brand', 'Team-based pricing', 'No-code movement appeal'],
    cons: ['Limited public commission info', 'Short cookie window', 'Competitive approval'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': 'Undisclosed',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'No-code database platform for teams',
    faq: [
      { question: 'What are the commission rates?', answer: 'Airtable does not publicly disclose affiliate commission rates. Approved affiliates receive detailed information in their partner dashboard.' },
      { question: 'Who is eligible?', answer: 'The program is selective and typically accepts content creators, educators, and consultants with relevant audiences.' }
    ]
  },
  {
    id: '605',
    slug: 'clickup-affiliate',
    name: 'ClickUp Affiliate Program',
    category: 'affiliate',
    founded_year: 2017,
    hq_location: 'San Diego, California, USA',
    website: 'https://clickup.com/affiliates',
    products_summary: 'All-in-one productivity platform combining tasks, docs, goals, and chat with competitive recurring affiliate commissions for workspace referrals.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['Recurring commissions', 'Fast-growing brand', 'Generous free tier', 'High engagement rates'],
    cons: ['Newer platform', 'Feature complexity', 'Competitive market'],
    quick_facts: {
      'Founded': '2017',
      'Commission Rate': '25% recurring',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Fast-growing productivity platform with recurring pay',
    faq: [
      { question: 'How long do I earn commissions?', answer: 'You earn 25% recurring commission for the lifetime of each customer subscription you refer.' },
      { question: 'What is the minimum payout?', answer: 'The minimum payout threshold is $50, with payments processed monthly via PayPal or bank transfer.' }
    ]
  },
  {
    id: '606',
    slug: 'zapier-affiliate',
    name: 'Zapier Affiliate Program',
    category: 'affiliate',
    founded_year: 2011,
    hq_location: 'San Francisco, California, USA',
    website: 'https://zapier.com/platform/partner-program',
    products_summary: 'Automation platform connecting apps and workflows, offering partner revenue share for referring customers to paid automation plans.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['Market leader in automation', 'Strong conversion rates', 'Wide integration ecosystem', 'Professional support'],
    cons: ['Selective approval process', 'Limited commission transparency', 'Technical audience needed'],
    quick_facts: {
      'Founded': '2011',
      'Commission Rate': 'Undisclosed revenue share',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Automation leader with integration ecosystem',
    faq: [
      { question: 'What kind of partners does Zapier accept?', answer: 'Zapier partners include app developers, consultants, agencies, and content creators focused on business automation and productivity.' },
      { question: 'How do commissions work?', answer: 'Commission structure varies by partner type and is shared upon acceptance to the program.' }
    ]
  },
  {
    id: '607',
    slug: 'make-integromat-affiliate',
    name: 'Make (Integromat) Affiliate',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'Prague, Czech Republic',
    website: 'https://www.make.com/en/partners/affiliates',
    products_summary: 'Visual automation platform (formerly Integromat) offering 20% recurring commission for referring users to paid automation scenarios and workflows.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 4.0,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['20% recurring lifetime', 'Visual workflow builder', 'Growing market share', 'Good conversion tools'],
    cons: ['Less known than Zapier', 'Technical learning curve', 'Smaller community'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Visual automation with lifetime recurring commissions',
    faq: [
      { question: 'How does Make differ from Zapier?', answer: 'Make offers more advanced visual automation capabilities with better pricing for power users, making it attractive for technical audiences.' },
      { question: 'When do I get paid?', answer: 'Commissions are paid monthly once you reach the $100 minimum threshold, via PayPal or bank transfer.' }
    ]
  },
  {
    id: '608',
    slug: 'webflow-affiliate',
    name: 'Webflow Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'San Francisco, California, USA',
    website: 'https://webflow.com/affiliates',
    products_summary: 'Visual web design platform combining design, CMS, and hosting with 50% commission on first 12 months of customer subscriptions.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['12 years in business — San Francisco', 'Per-customer residual $6-50/mo (50% for 12mo)', 'Designer-focused audience', 'Strong community'],
    cons: ['12-month commission limit', 'Technical product — learning curve', 'Designer niche limits audience'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': '50% for 12 months',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: '50% commission on designer-favorite web platform',
    faq: [
      { question: 'What can I earn per customer?', answer: 'With Webflow plans ranging from $14-$212/month, you can earn $7-$106 per month per customer for 12 months.' },
      { question: 'Are hosting plans included?', answer: 'Yes, commissions apply to both site plans and account plans including CMS and e-commerce hosting.' }
    ]
  },
  {
    id: '609',
    slug: 'squarespace-affiliate',
    name: 'Squarespace Affiliate',
    category: 'affiliate',
    founded_year: 2003,
    hq_location: 'New York, New York, USA',
    website: 'https://www.squarespace.com/affiliates',
    products_summary: 'Website builder and hosting platform offering $200 per sale for annual plans or $100 per monthly subscription through affiliate referrals.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['22 years in business — NYC', 'Zero residual ($100-200 one-time)', 'Well-known brand', 'Good conversion rates'],
    cons: ['No recurring — one-time only', 'Competitive website builder market', 'Premium pricing limits audience'],
    quick_facts: {
      'Founded': '2003',
      'Commission Rate': '$100-200 per sale',
      'Cookie Duration': '45 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Premium website builder with high payouts',
    faq: [
      { question: 'Are commissions recurring?', answer: 'No, Squarespace pays one-time commissions: $200 for annual plan purchases or $100 for monthly subscriptions.' },
      { question: 'When do I get paid?', answer: 'Payments are processed monthly via PayPal or direct deposit once you reach the $100 minimum threshold.' }
    ]
  },
  {
    id: '610',
    slug: 'wix-affiliate',
    name: 'Wix Affiliate Program',
    category: 'affiliate',
    founded_year: 2006,
    hq_location: 'Tel Aviv, Israel',
    website: 'https://www.wix.com/about/affiliates',
    products_summary: 'Website builder platform with drag-and-drop editor offering $100 per premium plan sale through their affiliate program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['19 years in business — Tel Aviv', 'Zero residual ($100 one-time)', 'Massive brand recognition', 'Free tier converts well'],
    cons: ['No recurring — one-time only', 'Very competitive market', '$300 minimum payout'],
    quick_facts: {
      'Founded': '2006',
      'Commission Rate': '$100 per premium sale',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Global website builder with flat commissions',
    faq: [
      { question: 'What qualifies as a premium sale?', answer: 'You earn $100 when a user you refer purchases any premium Wix plan, including website, business, or e-commerce subscriptions.' },
      { question: 'How long is the cookie?', answer: 'Wix uses a 30-day cookie window to track referrals and attribute commissions to your account.' }
    ]
  },
  {
    id: '611',
    slug: 'bigcommerce-affiliate',
    name: 'BigCommerce Affiliate',
    category: 'affiliate',
    founded_year: 2009,
    hq_location: 'Austin, Texas, USA',
    website: 'https://www.bigcommerce.com/partners/',
    products_summary: 'E-commerce platform offering 200% of first month payment (average $300-600) plus $1,500 for enterprise referrals through partner program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 3.0,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['High commission payouts', 'Enterprise bonus opportunities', 'Growing e-commerce market', 'Strong merchant support'],
    cons: ['No recurring after first month', 'Requires e-commerce audience', 'Competitive onboarding'],
    quick_facts: {
      'Founded': '2009',
      'Commission Rate': '200% first month',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'E-commerce platform with enterprise opportunities',
    faq: [
      { question: 'How much is the average commission?', answer: 'Standard plans range $29-$299/month, so 200% of first month means $58-$598 per referral, with $1,500 bonuses for enterprise.' },
      { question: 'Are there ongoing commissions?', answer: 'No, you receive 200% of the customer\'s first monthly payment only, not recurring commissions.' }
    ]
  },
  {
    id: '612',
    slug: 'woocommerce-affiliate',
    name: 'WooCommerce Affiliate',
    category: 'affiliate',
    founded_year: 2011,
    hq_location: 'San Francisco, California, USA',
    website: 'https://woocommerce.com/affiliates/',
    products_summary: 'WordPress e-commerce plugin offering 20% commission on extensions, themes, and hosting referrals through their affiliate program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['WordPress ecosystem', '20% on all products', 'Large extension marketplace', 'Active community'],
    cons: ['Core plugin is free', 'Extension-dependent', 'One-time commissions'],
    quick_facts: {
      'Founded': '2011',
      'Commission Rate': '20% per sale',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'WordPress e-commerce with extension ecosystem',
    faq: [
      { question: 'What products earn commission?', answer: 'You earn 20% on WooCommerce extensions, themes, WooCommerce Payments, and WooCommerce-branded hosting products.' },
      { question: 'Is WooCommerce free?', answer: 'The core WooCommerce plugin is free, but most users purchase premium extensions, themes, or hosting where you earn commissions.' }
    ]
  },
  {
    id: '613',
    slug: 'prestashop-affiliate',
    name: 'PrestaShop Affiliate',
    category: 'affiliate',
    founded_year: 2007,
    hq_location: 'Paris, France',
    website: 'https://www.prestashop.com/en/become-partner',
    products_summary: 'Open-source e-commerce platform with partner program offering commissions on hosting, modules, and theme sales for referred merchants.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.0,
    residual_rating: 2.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.0,
    community_rating: 3.0,
    value_rating: 3.0,
    pros: ['European market strong', 'Module marketplace', 'Free core software', 'Agency partnerships'],
    cons: ['Limited US presence', 'Lower commission rates', 'Smaller ecosystem'],
    quick_facts: {
      'Founded': '2007',
      'Commission Rate': 'Varies by product',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'European e-commerce platform with modules',
    faq: [
      { question: 'Where is PrestaShop most popular?', answer: 'PrestaShop has strong market share in Europe, particularly France, Spain, and Italy, with growing presence in Latin America.' },
      { question: 'What are commission rates?', answer: 'Rates vary by product category and partner tier, typically ranging from 10-25% on marketplace items and hosting.' }
    ]
  },
  {
    id: '614',
    slug: 'thrivecart-affiliate',
    name: 'ThriveCart Affiliate',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'Remote',
    website: 'https://thrivecart.com/affiliates/',
    products_summary: 'Shopping cart platform with one-time lifetime deal offering 40% recurring commission on lifetime license sales and subscription renewals.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['40% commission rate', 'High-ticket product ($495+)', 'Lifetime deal appeal', 'Strong conversions'],
    cons: ['One-time purchase model', 'Limited recurring revenue', 'Niche audience'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': '40% per sale',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: '40% on high-ticket cart platform lifetime deals',
    faq: [
      { question: 'How much can I earn per sale?', answer: 'ThriveCart licenses typically sell for $495-$690, meaning you earn $198-$276 per referral at 40% commission.' },
      { question: 'Is this recurring?', answer: 'ThriveCart sells primarily lifetime licenses (one-time), though they occasionally offer payment plans which provide limited recurring revenue.' }
    ]
  },
  {
    id: '615',
    slug: 'samcart-affiliate',
    name: 'SamCart Affiliate',
    category: 'affiliate',
    founded_year: 2014,
    hq_location: 'Austin, Texas, USA',
    website: 'https://www.samcart.com/affiliate-program/',
    products_summary: 'E-commerce checkout platform for digital products offering 40% recurring monthly commission for referring online course creators and coaches.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['40% recurring lifetime', 'Online course boom', 'High engagement audience', 'Quality marketing materials'],
    cons: ['Niche market focus', 'Competitive alternatives', '$50 minimum payout'],
    quick_facts: {
      'Founded': '2014',
      'Commission Rate': '40% recurring',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: '40% recurring on course creator checkout platform',
    faq: [
      { question: 'How long do I earn commissions?', answer: 'You earn 40% recurring commission for the entire lifetime of each customer subscription you refer.' },
      { question: 'What is the average commission?', answer: 'SamCart plans range from $79-$199/month, so you earn $31.60-$79.60 per month per customer.' }
    ]
  },
  {
    id: '616',
    slug: 'deadline-funnel-affiliate',
    name: 'Deadline Funnel Affiliate',
    category: 'affiliate',
    founded_year: 2015,
    hq_location: 'Remote',
    website: 'https://www.deadlinefunnel.com/affiliates',
    products_summary: 'Scarcity and urgency marketing platform offering 30% recurring commission on authentic countdown timer software for marketers.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['10 years in business', 'Per-customer residual $15-66/mo (33% for 24mo)', 'Niche marketing tool', 'High retention'],
    cons: ['24-month cap (need 1 ref/6mo to extend)', 'Narrow audience', 'Some ethical concerns'],
    quick_facts: {
      'Founded': '2015',
      'Commission Rate': '30% recurring',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Marketing scarcity tool with recurring commissions',
    faq: [
      { question: 'What does Deadline Funnel do?', answer: 'It creates authentic, personalized countdown timers for marketing campaigns to create urgency without fake scarcity.' },
      { question: 'How much can I earn?', answer: 'Plans range from $49-$199/month, earning you $14.70-$59.70 per month per customer at 30% commission.' }
    ]
  },
  {
    id: '617',
    slug: 'everwebinar-affiliate',
    name: 'EverWebinar Affiliate',
    category: 'affiliate',
    founded_year: 2014,
    hq_location: 'New York, New York, USA',
    website: 'https://home.everwebinar.com/affiliates/',
    products_summary: 'Automated webinar platform offering 40% recurring commission on software that simulates live webinars for evergreen marketing funnels.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['11 years in business', 'Per-customer residual $33-200/yr (40% recurring)', 'High-ticket product', 'Evergreen marketing appeal'],
    cons: ['Controversial automation ethics', 'Premium pricing', 'Requires marketing savvy'],
    quick_facts: {
      'Founded': '2014',
      'Commission Rate': '40% recurring',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Automated webinar platform with 40% recurring',
    faq: [
      { question: 'What are EverWebinar commissions?', answer: 'Plans start at $499/year or $83/month, earning you approximately $200/year or $33/month per customer at 40%.' },
      { question: 'How does automated webinar work?', answer: 'EverWebinar plays pre-recorded webinars on a schedule that appears live, with automated chat and registration sequences.' }
    ]
  },
  {
    id: '618',
    slug: 'webinarjam-affiliate',
    name: 'WebinarJam Affiliate',
    category: 'affiliate',
    founded_year: 2014,
    hq_location: 'New York, New York, USA',
    website: 'https://home.webinarjam.com/affiliates/',
    products_summary: 'Live webinar hosting platform offering 40% recurring commission on browser-based webinar software for marketers and educators.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['11 years in business', 'Per-customer residual $200-400/yr (40% recurring)', 'Live webinar demand', 'Same company as EverWebinar'],
    cons: ['Competitive webinar market', 'Premium pricing', 'Technical support needed'],
    quick_facts: {
      'Founded': '2014',
      'Commission Rate': '40% recurring',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Live webinar platform with generous recurring pay',
    faq: [
      { question: 'How much can I earn?', answer: 'WebinarJam plans range from $499-$999/year, earning you $200-$400 per year per customer at 40% commission.' },
      { question: 'What\'s the difference from Zoom?', answer: 'WebinarJam is specifically designed for marketing webinars with built-in registration pages, email automation, and conversion tracking.' }
    ]
  },
  {
    id: '619',
    slug: 'demio-affiliate',
    name: 'Demio Affiliate Program',
    category: 'affiliate',
    founded_year: 2014,
    hq_location: 'Remote',
    website: 'https://demio.com/affiliates',
    products_summary: 'Browser-based webinar platform offering 30% recurring commission on modern, no-download webinar software for marketers and SaaS companies.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['11 years in business', 'Per-customer residual $18-70/mo (30% lifetime)', 'Modern UI/UX — no downloads', 'Growing SaaS market'],
    cons: ['Lower rate than competitors', 'Competitive space', 'Mid-tier pricing'],
    quick_facts: {
      'Founded': '2014',
      'Commission Rate': '30% recurring',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Modern webinar platform with lifetime commissions',
    faq: [
      { question: 'How much are typical commissions?', answer: 'Demio plans range from $59-$234/month, earning you $17.70-$70.20 per month per customer at 30%.' },
      { question: 'What makes Demio different?', answer: 'Demio focuses on simplicity and modern design with no downloads required, appealing to SaaS and B2B marketers.' }
    ]
  },
  {
    id: '620',
    slug: 'loom-affiliate',
    name: 'Loom Affiliate Program',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.loom.com/affiliates',
    products_summary: 'Async video messaging platform offering commission on paid plans for screen and camera recording software used by remote teams.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['Viral product growth', 'Remote work trend', 'Easy to demonstrate', 'Strong free tier'],
    cons: ['Limited public commission info', 'Many free users', 'Competitive approval'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': 'Undisclosed',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Viral async video tool for remote teams',
    faq: [
      { question: 'What are the commission rates?', answer: 'Loom does not publicly disclose affiliate commission rates. Approved affiliates receive program details in their partner portal.' },
      { question: 'Who should promote Loom?', answer: 'Best for content creators, productivity educators, and remote work advocates with engaged professional audiences.' }
    ]
  },
  {
    id: '621',
    slug: 'descript-affiliate',
    name: 'Descript Affiliate Program',
    category: 'affiliate',
    founded_year: 2017,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.descript.com/affiliates',
    products_summary: 'Audio and video editing platform offering 25% commission on text-based editing software popular with podcasters and video creators.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['25% recurring commission', 'Creator economy growth', 'Innovative product', 'Good retention'],
    cons: ['Niche audience', 'Learning curve', 'Premium pricing'],
    quick_facts: {
      'Founded': '2017',
      'Commission Rate': '25% recurring',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Innovative editing tool for creator economy',
    faq: [
      { question: 'What is Descript\'s unique feature?', answer: 'Descript allows editing audio and video by editing the transcript text, making it much faster for podcasters and video creators.' },
      { question: 'How much can I earn?', answer: 'Descript plans range from $12-$24/month per user, earning you $3-$6 per user per month at 25% commission.' }
    ]
  },
  {
    id: '622',
    slug: 'canva-affiliate',
    name: 'Canva Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'Sydney, Australia',
    website: 'https://www.canva.com/affiliates/',
    products_summary: 'Graphic design platform offering $36 per Canva Pro referral for the popular drag-and-drop design tool used by millions globally.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['12 years in business — Sydney', 'Zero residual ($36 one-time)', 'Massive brand awareness', 'Free tier converts well'],
    cons: ['No recurring — one-time $36', 'Shifted to Canvassador program', 'Very competitive'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': '$36 per Pro sale',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Global design platform with easy conversions',
    faq: [
      { question: 'Is this recurring?', answer: 'No, Canva pays a one-time $36 commission per Canva Pro or Teams subscription, not recurring monthly payments.' },
      { question: 'What qualifies?', answer: 'You earn when someone signs up for Canva Pro ($12.99/month) or Canva Teams through your affiliate link.' }
    ]
  },
  {
    id: '623',
    slug: 'figma-partner',
    name: 'Figma Partner Program',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.figma.com/partners/',
    products_summary: 'Collaborative design platform with partner program for agencies, consultants, and educators referring teams to interface design software.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 3.5,
    transparency_rating: 3.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['Industry-leading design tool', 'Strong designer community', 'Team-based pricing', 'Professional network'],
    cons: ['Partner-focused not affiliate', 'No public commission rates', 'Requires design audience'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': 'Undisclosed',
      'Cookie Duration': 'N/A'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Design industry leader with partner network',
    faq: [
      { question: 'Is this a traditional affiliate program?', answer: 'No, Figma\'s partner program focuses on agencies, consultants, and educators rather than traditional affiliate marketers.' },
      { question: 'What are the benefits?', answer: 'Partners receive training, certification, community access, and potential referral arrangements based on partnership tier.' }
    ]
  },
  {
    id: '624',
    slug: 'adobe-affiliate',
    name: 'Adobe Affiliate Program',
    category: 'affiliate',
    founded_year: 1982,
    hq_location: 'San Jose, California, USA',
    website: 'https://www.adobe.com/affiliates.html',
    products_summary: 'Creative software suite offering 85% of first month commission on Creative Cloud, Acrobat, and other Adobe subscription products.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 2.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['Huge brand recognition', 'High-value products', 'Professional market', 'Good conversion materials'],
    cons: ['Only first month 85%', 'No ongoing recurring', 'Premium pricing barrier'],
    quick_facts: {
      'Founded': '1982',
      'Commission Rate': '85% of first month',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Industry-standard creative software commissions',
    faq: [
      { question: 'How much can I earn per referral?', answer: 'Creative Cloud plans range from $9.99-$79.99/month, earning you $8.49-$67.99 per referral (85% of first month only).' },
      { question: 'Are commissions recurring?', answer: 'No, you receive 85% of the customer\'s first monthly payment only, not ongoing monthly commissions.' }
    ]
  },
  {
    id: '625',
    slug: 'envato-affiliate',
    name: 'Envato Affiliate Program',
    category: 'affiliate',
    founded_year: 2006,
    hq_location: 'Melbourne, Australia',
    website: 'https://www.envato.com/affiliates/',
    products_summary: 'Digital marketplace for themes, graphics, and templates offering 30% commission on Envato Elements subscriptions and marketplace purchases.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% on subscriptions', 'Huge product catalog', 'Designer/developer audience', 'Both one-time and recurring'],
    cons: ['Variable commission rates', 'Competitive marketplace', 'Cookie only 90 days'],
    quick_facts: {
      'Founded': '2006',
      'Commission Rate': '30% recurring + marketplace',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Creative marketplace with subscription and products',
    faq: [
      { question: 'What products earn commission?', answer: 'You earn 30% on Envato Elements subscriptions ($16.50/month) and varying rates on ThemeForest, CodeCanyon, and marketplace purchases.' },
      { question: 'Are Elements commissions recurring?', answer: 'Yes, you earn 30% monthly recurring commission on Envato Elements subscriptions for the lifetime of the customer.' }
    ]
  },
  {
    id: '626',
    slug: 'elegant-themes-affiliate',
    name: 'Elegant Themes Affiliate',
    category: 'affiliate',
    founded_year: 2008,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.elegantthemes.com/affiliates/',
    products_summary: 'WordPress theme and Divi builder offering 50% commission on memberships, known for popular Divi page builder used on millions of sites.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.5,
    residual_rating: 2.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['17 years in business — SF', 'Per-sale $45-125 (50% one-time)', 'Popular Divi builder', 'Strong WordPress community'],
    cons: ['Annual license — no recurring', 'One-time per renewal cycle', 'Competitive market'],
    quick_facts: {
      'Founded': '2008',
      'Commission Rate': '50% per sale',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Popular Divi builder with 50% commissions',
    faq: [
      { question: 'How much can I earn?', answer: 'Elegant Themes pricing is $89/year or $249 lifetime, earning you $44.50 or $124.50 per sale at 50% commission.' },
      { question: 'Why is Divi popular?', answer: 'Divi is one of the most popular WordPress page builders with drag-and-drop editing, used on over 1 million websites.' }
    ]
  },
  {
    id: '627',
    slug: 'elementor-affiliate',
    name: 'Elementor Affiliate Program',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'Tel Aviv, Israel',
    website: 'https://elementor.com/affiliates/',
    products_summary: 'WordPress page builder offering 50% commission on Pro subscriptions, the fastest-growing page builder with millions of active installations.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.5,
    residual_rating: 2.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['9 years in business — Tel Aviv', 'Per-sale ~$30-200 (45-50% one-time)', 'Market leader — high conversions', 'Active community'],
    cons: ['Annual license — no monthly recurring', 'One-time per renewal cycle', 'Very competitive'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': '50% per sale',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Leading WordPress builder with 50% payouts',
    faq: [
      { question: 'What are typical earnings?', answer: 'Elementor Pro ranges from $59-$999/year, earning you $29.50-$499.50 per sale at 50% commission.' },
      { question: 'Is Elementor the market leader?', answer: 'Yes, Elementor is the most popular WordPress page builder with over 5 million active installations and rapid growth.' }
    ]
  },
  {
    id: '628',
    slug: 'divi-affiliate',
    name: 'Divi Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.elegantthemes.com/affiliates/',
    products_summary: 'WordPress theme and page builder (same as Elegant Themes) offering 50% commission on Divi theme and builder memberships.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.5,
    residual_rating: 2.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['12 years in business', 'Per-sale $45-125 (50% one-time)', 'Visual builder popularity', 'Lifetime license option'],
    cons: ['Same as Elegant Themes', 'One-time payments', 'Annual focus'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': '50% per sale',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Visual WordPress builder with generous splits',
    faq: [
      { question: 'Is Divi the same as Elegant Themes?', answer: 'Yes, Divi is the flagship product from Elegant Themes. The affiliate program covers all Elegant Themes products including Divi.' },
      { question: 'What makes Divi different?', answer: 'Divi offers both a theme and standalone builder with visual editing, pre-made layouts, and a large user community.' }
    ]
  },
  {
    id: '629',
    slug: 'beaver-builder-affiliate',
    name: 'Beaver Builder Affiliate',
    category: 'affiliate',
    founded_year: 2014,
    hq_location: 'Remote',
    website: 'https://www.wpbeaverbuilder.com/affiliates/',
    products_summary: 'WordPress page builder plugin offering 25% commission on license sales, known for clean code and developer-friendly approach.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.5,
    residual_rating: 2.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['11 years in business', 'Per-sale $25-100 (25% one-time)', 'Clean code reputation', 'Developer-focused'],
    cons: ['Annual license — no recurring', 'Smaller market share', 'Lower commission'],
    quick_facts: {
      'Founded': '2014',
      'Commission Rate': '25% per sale',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Developer-friendly builder with quality focus',
    faq: [
      { question: 'How does Beaver Builder compare?', answer: 'Beaver Builder is known for clean, standards-compliant code making it popular with developers and agencies focused on performance.' },
      { question: 'What are the earnings?', answer: 'Licenses range from $99-$399/year, earning you $24.75-$99.75 per sale at 25% commission.' }
    ]
  },
  {
    id: '630',
    slug: 'oxygen-builder-affiliate',
    name: 'Oxygen Builder Affiliate',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'Remote',
    website: 'https://oxygenbuilder.com/affiliates/',
    products_summary: 'WordPress visual site builder offering 25% commission on licenses, positioned as bloat-free alternative for performance-focused developers.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.5,
    residual_rating: 2.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['9 years in business', 'Per-sale $25-100 (25% one-time)', 'Performance-focused', 'Lifetime license option'],
    cons: ['Annual license — no recurring', 'Niche audience', 'Steeper learning curve'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': '25% per sale',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Performance-focused builder for developers',
    faq: [
      { question: 'What makes Oxygen different?', answer: 'Oxygen focuses on performance by replacing the WordPress theme entirely, generating minimal code for faster page loads.' },
      { question: 'What are the commissions?', answer: 'Oxygen pricing ranges from $129-$399 for lifetime licenses, earning you $32.25-$99.75 per sale at 25%.' }
    ]
  },
  {
    id: '631',
    slug: 'cloudways-affiliate',
    name: 'Cloudways Affiliate',
    category: 'affiliate',
    founded_year: 2011,
    hq_location: 'Valletta, Malta',
    website: 'https://www.cloudways.com/en/affiliate.php',
    products_summary: 'Managed cloud hosting platform offering up to $125 per referral with hybrid commission structure for DigitalOcean, AWS, and Google Cloud hosting.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.0,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['14 years in business — Malta', 'Per-customer ~$50-125 bounty + 7% recurring', 'Hybrid model', 'Growing cloud market'],
    cons: ['Limited recurring portion', 'Complex commission tiers', 'Technical audience'],
    quick_facts: {
      'Founded': '2011',
      'Commission Rate': '$50-125 + revenue share',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Managed cloud hosting with hybrid commissions',
    faq: [
      { question: 'How does the hybrid model work?', answer: 'You earn a one-time payment of $50-125 per customer plus 7% revenue share for up to 90 days depending on performance tier.' },
      { question: 'What hosting do they offer?', answer: 'Cloudways provides managed hosting on DigitalOcean, AWS, Google Cloud, Vultr, and Linode infrastructure.' }
    ]
  },
  {
    id: '632',
    slug: 'kinsta-affiliate',
    name: 'Kinsta Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'Los Angeles, California, USA',
    website: 'https://kinsta.com/affiliates/',
    products_summary: 'Premium WordPress hosting offering up to $500 per referral plus 10% recurring, powered by Google Cloud Platform infrastructure.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 4.0,
    residual_rating: 4.0,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['$500 per enterprise referral', '10% recurring lifetime', 'Premium positioning', 'Excellent support reputation'],
    cons: ['High customer pricing', 'Requires WordPress audience', 'Minimum $50-100 referrals'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': '$50-500 + 10% recurring',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Premium WordPress hosting with enterprise payouts',
    faq: [
      { question: 'How much can I earn per referral?', answer: 'Standard plans earn $50-100 one-time plus 10% monthly recurring. Enterprise plans can earn up to $500 plus ongoing commission.' },
      { question: 'What makes Kinsta premium?', answer: 'Kinsta uses Google Cloud Platform, offers expert WordPress support, automatic backups, and performance optimization.' }
    ]
  },
  {
    id: '633',
    slug: 'flywheel-affiliate',
    name: 'Flywheel Affiliate Program',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'Omaha, Nebraska, USA',
    website: 'https://getflywheel.com/affiliates/',
    products_summary: 'WordPress hosting for designers and agencies offering $300 per referral on premium managed hosting with focus on creative professionals.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['13 years in business — Omaha', 'Zero residual ($300 one-time)', 'Designer-focused brand', 'Agency-friendly'],
    cons: ['No recurring — one-time only', 'Now owned by WP Engine', 'Premium pricing'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': '$300 per referral',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Designer-focused hosting with flat payouts',
    faq: [
      { question: 'Is this recurring?', answer: 'No, Flywheel pays a one-time $300 commission per qualified referral, not ongoing recurring payments.' },
      { question: 'What happened to Flywheel?', answer: 'Flywheel was acquired by WP Engine in 2019 but maintains its designer-focused brand and separate hosting platform.' }
    ]
  },
  {
    id: '634',
    slug: 'siteground-affiliate',
    name: 'SiteGround Affiliate',
    category: 'affiliate',
    founded_year: 2004,
    hq_location: 'Sofia, Bulgaria',
    website: 'https://www.siteground.com/affiliates',
    products_summary: 'Web hosting offering $50-100 per sale with volume bonuses, known for WordPress optimization and officially recommended by WordPress.org.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 4.0,
    pros: ['21 years in business — Bulgaria', 'Zero residual ($50-125 one-time)', 'WordPress.org recommended', 'Volume bonuses'],
    cons: ['No recurring — one-time only', 'Competitive hosting market', 'Lower initial rate ($50)'],
    quick_facts: {
      'Founded': '2004',
      'Commission Rate': '$50-100 per sale',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'WordPress-recommended hosting with volume bonuses',
    faq: [
      { question: 'How do volume bonuses work?', answer: 'Start at $50 per sale, increasing to $75 at 6-10 sales/month and $100 at 11+ sales per month.' },
      { question: 'Why is SiteGround recommended?', answer: 'SiteGround is one of three officially recommended hosts on WordPress.org due to performance, security, and WordPress-specific optimization.' }
    ]
  },
  {
    id: '635',
    slug: 'a2-hosting-affiliate',
    name: 'A2 Hosting Affiliate',
    category: 'affiliate',
    founded_year: 2001,
    hq_location: 'Ann Arbor, Michigan, USA',
    website: 'https://www.a2hosting.com/affiliates',
    products_summary: 'Web hosting offering $85-140 per sale with focus on speed and developer tools, known for Turbo servers and WordPress optimization.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['24 years in business — Michigan', 'Zero residual ($85-140 one-time)', 'Performance-focused', 'Developer-friendly'],
    cons: ['No recurring — one-time only', 'Competitive market', 'Smaller brand'],
    quick_facts: {
      'Founded': '2001',
      'Commission Rate': '$85-140 per sale',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Speed-focused hosting with competitive payouts',
    faq: [
      { question: 'What are Turbo servers?', answer: 'A2 Hosting\'s Turbo servers use LiteSpeed, HTTP/2, and caching technology for up to 20x faster page loads than standard hosting.' },
      { question: 'How much can I earn?', answer: 'Earn $85 per shared hosting sale and up to $140 per VPS or dedicated server referral.' }
    ]
  },
  {
    id: '636',
    slug: 'liquid-web-affiliate',
    name: 'Liquid Web Affiliate',
    category: 'affiliate',
    founded_year: 1997,
    hq_location: 'Lansing, Michigan, USA',
    website: 'https://www.liquidweb.com/partners/affiliate-program/',
    products_summary: 'Managed hosting for agencies and enterprises offering 150% of first month payment on VPS, dedicated, and cloud hosting referrals.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.5,
    residual_rating: 2.5,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 4.0,
    pros: ['28 years in business — Michigan', 'Zero residual (150% first month bounty)', 'High-ticket $37-750 per sale', 'Enterprise-level'],
    cons: ['No recurring — one-time only', 'Requires enterprise audience', 'Technical knowledge needed'],
    quick_facts: {
      'Founded': '1997',
      'Commission Rate': '150% of first month',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Enterprise hosting with 150% first month payouts',
    faq: [
      { question: 'How much are typical commissions?', answer: 'VPS hosting starts at $25/month (earning $37.50), while dedicated servers range $100-500/month (earning $150-750 per sale).' },
      { question: 'What is Liquid Web known for?', answer: 'Liquid Web specializes in managed hosting for agencies and businesses with 24/7 support and "Heroic Support" guarantee.' }
    ]
  },
  {
    id: '637',
    slug: 'namecheap-affiliate',
    name: 'Namecheap Affiliate',
    category: 'affiliate',
    founded_year: 2000,
    hq_location: 'Phoenix, Arizona, USA',
    website: 'https://www.namecheap.com/affiliates/',
    products_summary: 'Domain registrar and hosting offering up to $100 per sale on domains, SSL certificates, and hosting with volume-based commission tiers.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['25 years in business — Phoenix', 'Zero residual ($15-100 one-time)', 'Multiple product categories', 'Brand recognition'],
    cons: ['No recurring — one-time only', 'Low per-domain commissions', 'Requires high volume'],
    quick_facts: {
      'Founded': '2000',
      'Commission Rate': '$15-100 per sale',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Domain and hosting with tiered commissions',
    faq: [
      { question: 'What are the commission rates?', answer: 'Earn $15-30 per domain/SSL, $50-70 per shared hosting, and up to $100 per server/VPS sale depending on volume tier.' },
      { question: 'How do volume tiers work?', answer: 'Higher monthly sales volume unlocks better commission rates across all product categories.' }
    ]
  },
  {
    id: '638',
    slug: 'godaddy-affiliate',
    name: 'GoDaddy Affiliate Program',
    category: 'affiliate',
    founded_year: 1997,
    hq_location: 'Scottsdale, Arizona, USA',
    website: 'https://www.godaddy.com/affiliate-programs',
    products_summary: 'Domain and hosting giant offering percentage-based commissions on domains, hosting, and website builder sales through CJ Affiliate network.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 3.5,
    transparency_rating: 3.0,
    community_rating: 3.0,
    value_rating: 3.0,
    pros: ['28 years in business — Scottsdale', 'Zero residual (10-20% one-time)', 'Massive brand awareness', 'High conversion rates'],
    cons: ['No recurring — one-time only', 'Lower commission rates', 'Brand perception issues'],
    quick_facts: {
      'Founded': '1997',
      'Commission Rate': '10-20% per sale',
      'Cookie Duration': '45 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Industry giant with massive brand recognition',
    faq: [
      { question: 'What are typical earnings?', answer: 'Commissions range from $1-2 per domain registration to $10-30 for hosting plans depending on the product and current promotions.' },
      { question: 'Why are commissions lower?', answer: 'GoDaddy focuses on volume and brand recognition rather than high affiliate payouts, relying on massive marketing spend.' }
    ]
  },
  {
    id: '639',
    slug: 'hover-affiliate',
    name: 'Hover Affiliate Program',
    category: 'affiliate',
    founded_year: 2008,
    hq_location: 'Toronto, Canada',
    website: 'https://www.hover.com/affiliates',
    products_summary: 'Domain registrar offering $2-15 per domain registration with focus on clean interface and privacy, targeting professionals and creators.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.0,
    value_rating: 3.0,
    pros: ['17 years in business — Toronto', 'Zero residual ($2-15 one-time)', 'Privacy-focused brand', 'Clean user experience'],
    cons: ['No recurring — one-time only', 'Low per-domain earnings', 'Limited product range'],
    quick_facts: {
      'Founded': '2008',
      'Commission Rate': '$2-15 per domain',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Privacy-focused domains with simple interface',
    faq: [
      { question: 'What makes Hover different?', answer: 'Hover focuses on simplicity and privacy with no upsells, clean interface, and free WHOIS privacy included with every domain.' },
      { question: 'How much can I earn?', answer: 'Earn $2 per .com domain registration, with higher payouts ($5-15) for premium extensions like .io, .ai, or .design.' }
    ]
  },
  {
    id: '640',
    slug: 'porkbun-affiliate',
    name: 'Porkbun Affiliate Program',
    category: 'affiliate',
    founded_year: 2014,
    hq_location: 'Portland, Oregon, USA',
    website: 'https://porkbun.com/affiliates',
    products_summary: 'Domain registrar offering 20% commission on domain registrations with transparent pricing and free SSL, popular with developers.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 2.0,
    residual_rating: 2.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.0,
    pros: ['20% commission rate', 'Transparent pricing', 'Free SSL and privacy', 'Developer-friendly'],
    cons: ['Low domain prices mean low payouts', 'Smaller brand', 'Limited products'],
    quick_facts: {
      'Founded': '2014',
      'Commission Rate': '20% per sale',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Transparent domain pricing with 20% commission',
    faq: [
      { question: 'How much can I earn per domain?', answer: 'With .com domains at $10.98, you earn about $2.20 per registration. Premium extensions earn more at 20%.' },
      { question: 'Why choose Porkbun?', answer: 'Porkbun offers transparent pricing, free SSL, free WHOIS privacy, and no hidden fees, appealing to technical users.' }
    ]
  },
  {
    id: '641',
    slug: 'cloudflare-partner',
    name: 'Cloudflare Partner Program',
    category: 'affiliate',
    founded_year: 2009,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.cloudflare.com/partners/',
    products_summary: 'CDN and security platform with partner program for agencies and resellers, offering revenue share on enterprise plans and add-on services.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['Industry-leading CDN', 'Enterprise revenue share', 'Strong brand trust', 'Growing product suite'],
    cons: ['Partner-focused not affiliate', 'Free tier limits commissions', 'Complex product line'],
    quick_facts: {
      'Founded': '2009',
      'Commission Rate': 'Varies by partnership',
      'Cookie Duration': 'N/A'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'CDN and security leader with partner network',
    faq: [
      { question: 'Is this a traditional affiliate program?', answer: 'No, Cloudflare focuses on agency, reseller, and technology partnerships rather than individual affiliate marketers.' },
      { question: 'What opportunities exist?', answer: 'Partners can earn revenue share on Enterprise plan referrals, resell Cloudflare services, or integrate Cloudflare into their products.' }
    ]
  },
  {
    id: '642',
    slug: 'sucuri-affiliate',
    name: 'Sucuri Affiliate Program',
    category: 'affiliate',
    founded_year: 2010,
    hq_location: 'Remote',
    website: 'https://sucuri.net/partners/affiliates/',
    products_summary: 'Website security and malware removal offering 30% recurring commission on firewall, monitoring, and cleanup services for WordPress sites.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% recurring lifetime', 'Security is essential', 'WordPress focus', 'Good customer retention'],
    cons: ['Niche security market', 'Requires trust building', 'Technical product'],
    quick_facts: {
      'Founded': '2010',
      'Commission Rate': '30% recurring',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Website security with lifetime recurring income',
    faq: [
      { question: 'What does Sucuri offer?', answer: 'Sucuri provides website firewalls, malware scanning, hack cleanup, and security monitoring primarily for WordPress sites.' },
      { question: 'How much can I earn?', answer: 'Plans range from $199-$499/year, earning you $59.70-$149.70 per year per customer at 30% recurring.' }
    ]
  },
  {
    id: '643',
    slug: 'malcare-affiliate',
    name: 'MalCare Affiliate Program',
    category: 'affiliate',
    founded_year: 2017,
    hq_location: 'Remote',
    website: 'https://www.malcare.com/affiliate-program/',
    products_summary: 'WordPress security plugin offering 30% recurring commission on malware scanning, firewall, and automated cleanup service subscriptions.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['30% recurring lifetime', 'WordPress-specific', 'Automated features', 'Easy to explain'],
    cons: ['Newer brand', 'Competitive security market', 'Plugin competition'],
    quick_facts: {
      'Founded': '2017',
      'Commission Rate': '30% recurring',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'WordPress security with automated cleanup',
    faq: [
      { question: 'How is MalCare different?', answer: 'MalCare offers one-click automated malware removal without manual intervention, faster than traditional security plugins.' },
      { question: 'What are the earnings?', answer: 'Plans range from $99-$299/year, earning you $29.70-$89.70 per year per customer at 30% recurring commission.' }
    ]
  },
  {
    id: '644',
    slug: 'wordfence-affiliate',
    name: 'Wordfence Affiliate',
    category: 'affiliate',
    founded_year: 2011,
    hq_location: 'Seattle, Washington, USA',
    website: 'https://www.wordfence.com/affiliates/',
    products_summary: 'WordPress security plugin offering 20% commission on premium firewall and security subscriptions, used on over 4 million sites.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['Market-leading plugin', '4M+ installations', 'Free version drives upgrades', 'Strong brand trust'],
    cons: ['Only 20% commission', 'Competitive freemium model', 'One-time annual payments'],
    quick_facts: {
      'Founded': '2011',
      'Commission Rate': '20% per sale',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Leading WordPress security with 4M+ sites',
    faq: [
      { question: 'What are typical commissions?', answer: 'Wordfence Premium is $119/year for 1 site, earning you $23.80 per sale. Multi-site licenses earn proportionally more.' },
      { question: 'Why is Wordfence popular?', answer: 'Wordfence offers robust free features including firewall and malware scanning, making premium upgrades an easy sell.' }
    ]
  },
  {
    id: '645',
    slug: 'gravity-forms-affiliate',
    name: 'Gravity Forms Affiliate',
    category: 'affiliate',
    founded_year: 2008,
    hq_location: 'Remote',
    website: 'https://www.gravityforms.com/affiliates/',
    products_summary: 'WordPress form builder offering 20% commission on license sales, the premium standard for advanced forms and integrations.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['Premium form standard', 'Developer favorite', 'Strong add-on ecosystem', 'High renewal rates'],
    cons: ['Only 20% commission', 'Annual licenses', 'Premium pricing limits market'],
    quick_facts: {
      'Founded': '2008',
      'Commission Rate': '20% per sale',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Premium WordPress forms with developer trust',
    faq: [
      { question: 'How much can I earn?', answer: 'Gravity Forms licenses range from $59-$259/year, earning you $11.80-$51.80 per sale at 20% commission.' },
      { question: 'Why choose Gravity Forms?', answer: 'Gravity Forms is the premium standard for advanced WordPress forms with conditional logic, payment integration, and extensive add-ons.' }
    ]
  },
  {
    id: '646',
    slug: 'wpforms-affiliate',
    name: 'WPForms Affiliate Program',
    category: 'affiliate',
    founded_year: 2016,
    hq_location: 'Remote',
    website: 'https://wpforms.com/affiliates/',
    products_summary: 'WordPress form builder offering 20% recurring commission on beginner-friendly drag-and-drop form plugin with payment integration.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['20% recurring commission', 'User-friendly product', '5M+ active installs', 'Good conversion rates'],
    cons: ['Annual billing cycle', 'Lower than competitors', 'Competitive form market'],
    quick_facts: {
      'Founded': '2016',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Beginner-friendly forms with recurring income',
    faq: [
      { question: 'Is this recurring?', answer: 'Yes, you earn 20% recurring commission on annual renewals for the lifetime of each customer subscription.' },
      { question: 'What are the earnings?', answer: 'WPForms plans range from $49.50-$299.50/year, earning you $9.90-$59.90 per year per customer.' }
    ]
  },
  {
    id: '647',
    slug: 'formidable-forms-affiliate',
    name: 'Formidable Forms Affiliate',
    category: 'affiliate',
    founded_year: 2011,
    hq_location: 'Remote',
    website: 'https://formidableforms.com/affiliates/',
    products_summary: 'Advanced WordPress form builder offering 25% commission on licenses with application builder capabilities and view features.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 3.5,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['25% commission rate', 'Advanced features', 'Application builder niche', 'Views functionality'],
    cons: ['More complex product', 'Smaller market share', 'Annual payments'],
    quick_facts: {
      'Founded': '2011',
      'Commission Rate': '25% per sale',
      'Cookie Duration': '60 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Advanced forms with application builder features',
    faq: [
      { question: 'What makes Formidable different?', answer: 'Formidable Forms offers advanced features like front-end data display (Views) and can build complete applications within WordPress.' },
      { question: 'What are typical earnings?', answer: 'Licenses range from $49.50-$399.50/year, earning you $12.38-$99.88 per sale at 25% commission.' }
    ]
  },
  {
    id: '648',
    slug: 'typeform-affiliate',
    name: 'Typeform Affiliate Program',
    category: 'affiliate',
    founded_year: 2012,
    hq_location: 'Barcelona, Spain',
    website: 'https://www.typeform.com/partners/',
    products_summary: 'Conversational form builder offering commission on subscriptions with unique one-question-at-a-time interface for better engagement.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Unique conversational UI', 'High engagement rates', 'Beautiful design', 'Strong brand'],
    cons: ['Limited public commission info', 'Partner program focus', 'Premium pricing'],
    quick_facts: {
      'Founded': '2012',
      'Commission Rate': 'Undisclosed',
      'Cookie Duration': 'Varies'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Conversational forms with unique engagement',
    faq: [
      { question: 'What is conversational form design?', answer: 'Typeform shows one question at a time in a full-screen, beautiful interface that feels like a conversation, boosting completion rates.' },
      { question: 'How do I join the program?', answer: 'Typeform operates a partner program rather than traditional affiliate program. Apply through their partner portal for commission details.' }
    ]
  },
  {
    id: '649',
    slug: 'jotform-affiliate',
    name: 'Jotform Affiliate Program',
    category: 'affiliate',
    founded_year: 2006,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.jotform.com/affiliates/',
    products_summary: 'Online form builder offering 30% commission on premium subscriptions with 10M+ users and extensive template library.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['30% commission rate', '10M+ user base', 'Extensive templates', 'Free tier converts'],
    cons: ['Competitive market', 'Mid-tier pricing', 'Many free users'],
    quick_facts: {
      'Founded': '2006',
      'Commission Rate': '30% per sale',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Established form builder with 30% commissions',
    faq: [
      { question: 'How much can I earn?', answer: 'Jotform pricing ranges from $34-$99/month, earning you $10.20-$29.70 per month per customer at 30%.' },
      { question: 'What makes Jotform competitive?', answer: 'Jotform offers 10,000+ templates, payment integration, workflow automation, and mobile app form building.' }
    ]
  },
  {
    id: '650',
    slug: 'calendly-affiliate',
    name: 'Calendly Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'Atlanta, Georgia, USA',
    website: 'https://calendly.com/pages/affiliates',
    products_summary: 'Scheduling automation platform offering commission on paid plans for eliminating back-and-forth email scheduling.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Viral product growth', 'Free tier drives upgrades', 'Business necessity', 'Easy to demonstrate'],
    cons: ['Limited public commission info', 'Many free users', 'Competitive space'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': 'Undisclosed',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Scheduling automation with viral growth',
    faq: [
      { question: 'What are commission rates?', answer: 'Calendly does not publicly disclose affiliate commission rates. Approved affiliates receive program details in their dashboard.' },
      { question: 'Why is Calendly popular?', answer: 'Calendly eliminates email back-and-forth by letting people book time directly on your calendar based on your availability.' }
    ]
  },
  {
    id: '651',
    slug: 'acuity-scheduling-affiliate',
    name: 'Acuity Scheduling Affiliate',
    category: 'affiliate',
    founded_year: 2006,
    hq_location: 'New York, New York, USA',
    website: 'https://acuityscheduling.com/affiliates',
    products_summary: 'Appointment scheduling software offering 30% recurring commission, now owned by Squarespace, popular with service businesses.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['30% recurring commission', 'Service business focus', 'Squarespace integration', 'Good feature set'],
    cons: ['Owned by Squarespace', 'Competitive scheduling market', 'Mid-tier pricing'],
    quick_facts: {
      'Founded': '2006',
      'Commission Rate': '30% recurring',
      'Cookie Duration': '45 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Service business scheduling with recurring pay',
    faq: [
      { question: 'How much can I earn?', answer: 'Acuity plans range from $16-$61/month, earning you $4.80-$18.30 per month per customer at 30% recurring.' },
      { question: 'What happened with Squarespace?', answer: 'Squarespace acquired Acuity in 2019 but maintains the separate brand and affiliate program with recurring commissions.' }
    ]
  },
  {
    id: '652',
    slug: 'dubsado-affiliate',
    name: 'Dubsado Affiliate Program',
    category: 'affiliate',
    founded_year: 2015,
    hq_location: 'Remote',
    website: 'https://www.dubsado.com/affiliate-program',
    products_summary: 'Business management platform for creative entrepreneurs offering 20% recurring commission on CRM, contracts, and invoicing for service businesses.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 4.0,
    simplicity_rating: 4.0,
    transparency_rating: 4.0,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['20% recurring lifetime', 'Creative business niche', 'All-in-one platform', 'Strong community'],
    cons: ['Niche audience', 'Lower commission rate', 'Competitive with HoneyBook'],
    quick_facts: {
      'Founded': '2015',
      'Commission Rate': '20% recurring',
      'Cookie Duration': '30 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Creative business CRM with lifetime recurring',
    faq: [
      { question: 'Who uses Dubsado?', answer: 'Dubsado is popular with photographers, designers, consultants, and other service-based creative entrepreneurs.' },
      { question: 'What are the earnings?', answer: 'Dubsado is $40/month (billed annually), earning you $8 per month per customer at 20% recurring commission.' }
    ]
  },
  {
    id: '653',
    slug: 'honeybook-affiliate',
    name: 'HoneyBook Affiliate Program',
    category: 'affiliate',
    founded_year: 2013,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.honeybook.com/partners',
    products_summary: 'Client management platform for creative businesses offering commission on subscriptions for proposals, contracts, invoicing, and scheduling.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 4.0,
    transparency_rating: 3.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['Well-funded startup', 'Creative professional focus', 'Beautiful interface', 'Strong marketing'],
    cons: ['Limited commission info', 'Partner program focus', 'Premium pricing'],
    quick_facts: {
      'Founded': '2013',
      'Commission Rate': 'Undisclosed',
      'Cookie Duration': 'Varies'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Creative business platform with partner program',
    faq: [
      { question: 'Is this a traditional affiliate program?', answer: 'HoneyBook operates a partner program focused on educators and influencers in the creative business space rather than traditional affiliates.' },
      { question: 'What does HoneyBook do?', answer: 'HoneyBook provides all-in-one client management including proposals, contracts, invoicing, scheduling, and payments for service businesses.' }
    ]
  },
  {
    id: '654',
    slug: 'freshworks-affiliate',
    name: 'Freshworks Affiliate Program',
    category: 'affiliate',
    founded_year: 2010,
    hq_location: 'San Mateo, California, USA',
    website: 'https://www.freshworks.com/partners/affiliate-program/',
    products_summary: 'Customer engagement software suite offering commission on CRM, helpdesk, and customer service platform subscriptions.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.5,
    value_rating: 3.5,
    pros: ['Multiple product suite', 'Public company backing', 'SMB focus', 'Good support resources'],
    cons: ['Complex product line', 'Variable commission structure', 'Requires B2B audience'],
    quick_facts: {
      'Founded': '2010',
      'Commission Rate': 'Varies by product',
      'Cookie Duration': '90 days'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Customer engagement suite for SMBs',
    faq: [
      { question: 'What products does Freshworks offer?', answer: 'Freshworks includes Freshdesk (support), Freshsales (CRM), Freshchat (messaging), and other customer engagement tools.' },
      { question: 'What are commission rates?', answer: 'Commission rates vary by product and subscription tier. Contact Freshworks affiliate team for specific rate details.' }
    ]
  },
  {
    id: '655',
    slug: 'intercom-partner',
    name: 'Intercom Partner Program',
    category: 'affiliate',
    founded_year: 2011,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.intercom.com/partners',
    products_summary: 'Customer messaging platform with partner program for agencies referring clients to conversational support, marketing, and engagement tools.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Commission-based affiliate',
    overall_rating: 3.5,
    residual_rating: 3.0,
    simplicity_rating: 3.0,
    transparency_rating: 3.0,
    community_rating: 4.0,
    value_rating: 3.5,
    pros: ['Premium product positioning', 'Strong brand in SaaS', 'High customer values', 'Agency partnerships'],
    cons: ['Partner-focused not affiliate', 'Enterprise pricing', 'No public commission rates'],
    quick_facts: {
      'Founded': '2011',
      'Commission Rate': 'Undisclosed',
      'Cookie Duration': 'N/A'
    },
    last_updated: '2026-01-15T00:00:00.000Z',
    is_featured: false,
    is_published: true,
    created_at: '2026-01-15T00:00:00.000Z',
    tagline: 'Premium customer messaging with partnerships',
    faq: [
      { question: 'Is this a traditional affiliate program?', answer: 'No, Intercom focuses on solution partners, technology partners, and agency partnerships rather than individual affiliate marketers.' },
      { question: 'What does Intercom offer?', answer: 'Intercom provides live chat, chatbots, customer support, product tours, and customer engagement automation for SaaS and digital businesses.' }
    ]
  }
];
