import { Company } from "@/types";

export const companiesBatchC1b: Company[] = [
  {
    id: "180",
    slug: "new-earth",
    name: "New Earth",
    category: "mlm",
    tagline: "Wild-harvested blue-green algae from pristine Klamath Lake",
    founded_year: 1995,
    hq_location: "Klamath Falls, OR",
    website: "https://new-earth.com",
    products_summary:
      "Wild-harvested Aphanizomenon flos-aquae (AFA) blue-green algae supplements, probiotics, enzymes, and whole-food nutrition products sourced from Upper Klamath Lake.",
    monthly_cost_min: 50,
    monthly_cost_max: 200,
    comp_plan_type: "unilevel",
    overall_rating: 2.2,
    residual_rating: 2.0,
    simplicity_rating: 2.3,
    transparency_rating: 2.1,
    community_rating: 2.5,
    value_rating: 2.2,
    pros: [
      "Unique wild-harvested algae product with loyal customer base",
      "Company has operated since 1995 showing longevity",
      "Products focus on whole-food nutrition rather than synthetic vitamins",
      "No monthly autoship requirement to remain active",
    ],
    cons: [
      "Blue-green algae health claims lack strong clinical evidence",
      "Products are expensive compared to similar supplements",
      "Small company with limited brand recognition",
    ],
    quick_facts: {
      "Year Founded": "1995",
      "Headquarters": "Klamath Falls, OR",
      "Product Focus": "Blue-Green Algae",
      "BBB Rating": "Not rated"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What makes New Earth's algae different from other supplements?",
        answer:
          "New Earth harvests Aphanizomenon flos-aquae (AFA) from Upper Klamath Lake in Oregon, claiming unique nutrient density. However, scientific evidence for AFA health benefits remains limited, and similar products exist at lower prices.",
      },
      {
        question: "Can you make money selling New Earth products?",
        answer:
          "As with any MLM, meaningful income requires building a substantial customer base. New Earth does not publish an income disclosure statement.",
      },
    ],
  },
  {
    id: "181",
    slug: "purium",
    name: "Purium Health Products",
    category: "mlm",
    tagline: "Organic superfoods and 10-day transformation cleanse programs",
    founded_year: 1993,
    hq_location: "Santa Monica, CA",
    website: "https://puriumcorp.com",
    products_summary:
      "Organic superfoods, detox cleanse programs, protein powders, and the flagship 10-Day Transformation kit. Features a mobile app for tracking and ordering.",
    monthly_cost_min: 75,
    monthly_cost_max: 300,
    comp_plan_type: "binary",
    overall_rating: 2.5,
    residual_rating: 2.3,
    simplicity_rating: 2.4,
    transparency_rating: 2.5,
    community_rating: 2.8,
    value_rating: 2.5,
    pros: [
      "Certified organic products with transparent ingredient sourcing",
      "10-Day Transformation program has genuine customer following",
      "Modern app makes ordering and tracking convenient",
      "Gift card marketing system is less pushy than typical MLM tactics",
      "Company has operated for over 30 years",
    ],
    cons: [
      "Products are significantly more expensive than comparable organics",
      "Cleanse programs make health claims that lack clinical backing",
      "Binary compensation plan favors early adopters",
    ],
    quick_facts: {
      "Year Founded": "1993",
      "Headquarters": "Santa Monica, CA",
      "Product Focus": "Organic Superfoods",
      "Flagship Product": "10-Day Transformation",
      "Certification": "USDA Organic"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is the Purium 10-Day Transformation worth the cost?",
        answer:
          "The 10-Day Transformation kit costs around $250-300 and includes organic superfoods for a cleanse program. While some users report positive results, similar organic products can be purchased separately for less. The transformation claims are not clinically validated.",
      },
      {
        question: "How does Purium's gift card system work?",
        answer:
          "Purium uses a $50 gift card referral system instead of traditional hard-selling. This approach feels less aggressive than typical MLM tactics, though it still functions as a recruitment-based business model.",
      },
    ],
  },
  {
    id: "182",
    slug: "black-oxygen-organics",
    name: "Black Oxygen Organics",
    category: "mlm",
    tagline: "Fulvic acid 'magic dirt' supplements — shut down by Health Canada",
    founded_year: 2020,
    hq_location: "Ottawa, Canada",
    website: "https://blackoxygenorganics.com (defunct)",
    products_summary:
      "Fulvic acid powder marketed as 'magic dirt' for detoxification. Products were found to contain dangerous levels of lead and arsenic. Company shut down by Health Canada in 2021.",
    monthly_cost_min: 100,
    monthly_cost_max: 200,
    comp_plan_type: "binary",
    overall_rating: 1.0,
    residual_rating: 1.0,
    simplicity_rating: 1.0,
    transparency_rating: 1.0,
    community_rating: 1.5,
    value_rating: 1.0,
    pros: [
      "None — company sold dangerous products and collapsed",
      "Serves as a cautionary tale about MLM health product risks",
      "Illustrates importance of regulatory oversight",
      "Media coverage helped warn potential victims",
    ],
    cons: [
      "Products contained toxic levels of lead and arsenic",
      "Health Canada shut down operations in 2021",
      "Distributors promoted consumption for children and bathing",
      "No refunds given when company collapsed",
    ],
    quick_facts: {
      "Year Founded": "2020",
      "Status": "SHUT DOWN 2021",
      "Shut Down By": "Health Canada",
      "Issue": "Toxic heavy metals in products",
      "Duration": "Less than 2 years"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Why was Black Oxygen Organics shut down?",
        answer:
          "Health Canada shut down BOO in 2021 after testing revealed dangerous levels of lead and arsenic in their fulvic acid products. Distributors had been promoting the 'magic dirt' for consumption, including for children, and for bathing.",
      },
      {
        question: "Did Black Oxygen Organics distributors get refunds?",
        answer:
          "No. When the company collapsed, most distributors lost their inventory investment and received no refunds. This illustrates the financial risk of MLM participation, especially with new companies selling unverified health products.",
      },
    ],
  },
  {
    id: "183",
    slug: "fortune-hi-tech-marketing",
    name: "Fortune Hi-Tech Marketing",
    category: "mlm",
    tagline: "FTC shut down this pyramid scheme disguised as product reselling",
    founded_year: 2001,
    hq_location: "Lexington, KY",
    website: "https://fhtm.com (defunct)",
    products_summary:
      "Marketed mobile phones, satellite TV, and energy services as fronts for recruitment-focused pyramid scheme. FTC and state AGs shut down operations in 2013.",
    monthly_cost_min: 100,
    monthly_cost_max: 400,
    comp_plan_type: "binary",
    overall_rating: 1.0,
    residual_rating: 1.0,
    simplicity_rating: 1.0,
    transparency_rating: 1.0,
    community_rating: 2.0,
    value_rating: 1.0,
    pros: [
      "None — confirmed pyramid scheme shut down by FTC",
      "Case serves as important legal precedent for MLM regulation",
      "Illustrates how product fronts can mask pyramid structures",
      "Demonstrates multi-state AG cooperation on MLM fraud",
    ],
    cons: [
      "FTC determined it operated as illegal pyramid scheme",
      "Vast majority of participants lost money",
      "Products were merely cover for recruitment focus",
      "Founders paid $7.75 million in FTC settlement",
    ],
    quick_facts: {
      "Year Founded": "2001",
      "Status": "FTC SHUTDOWN 2013",
      "FTC Settlement": "$7.75 million",
      "States Involved": "KY, IL, NC + FTC",
      "Finding": "Pyramid scheme",
      "Victims": "Estimated 350,000+"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What happened to Fortune Hi-Tech Marketing?",
        answer:
          "The FTC and attorneys general from Kentucky, Illinois, and North Carolina shut down FHTM in 2013, determining it was an illegal pyramid scheme. The company claimed to sell legitimate services but the FTC found recruitment was the true focus.",
      },
      {
        question: "How much did FHTM participants lose?",
        answer:
          "The FTC found that the vast majority of FHTM's estimated 350,000+ participants lost money. The founders paid a $7.75 million settlement, but this represented only a fraction of total participant losses.",
      },
    ],
  },
  {
    id: "184",
    slug: "wakeupnow",
    name: "WakeUpNow",
    category: "mlm",
    tagline: "Financial tools and shopping discounts MLM that collapsed in 2015",
    founded_year: 2009,
    hq_location: "Provo, UT",
    website: "https://wakeupnow.com (defunct)",
    products_summary:
      "Subscription service bundling financial management tools, energy drinks, and entertainment/shopping discounts. Company collapsed in 2015 after aggressive recruitment couldn't sustain business model.",
    monthly_cost_min: 100,
    monthly_cost_max: 150,
    comp_plan_type: "binary",
    overall_rating: 1.0,
    residual_rating: 1.0,
    simplicity_rating: 1.5,
    transparency_rating: 1.0,
    community_rating: 2.0,
    value_rating: 1.0,
    pros: [
      "None — company collapsed leaving distributors with losses",
      "Demonstrates unsustainability of recruitment-dependent models",
      "Case study in MLM warning signs and red flags",
      "Heavily targeted college students, highlighting predatory tactics",
    ],
    cons: [
      "Company ceased operations in 2015 without warning",
      "Heavily recruited college students with unrealistic income claims",
      "Products offered little value beyond recruitment incentive",
      "Aggressive social media tactics damaged personal relationships",
    ],
    quick_facts: {
      "Year Founded": "2009",
      "Status": "DEFUNCT 2015",
      "Headquarters": "Provo, UT",
      "Target Demographic": "College students",
      "Monthly Fee": "$100+",
      "Collapse Reason": "Unsustainable model"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Why did WakeUpNow fail?",
        answer:
          "WakeUpNow collapsed in 2015 because its business model depended on continuous recruitment rather than genuine product sales. When recruitment slowed, the company couldn't sustain operations and shut down suddenly, leaving distributors with losses.",
      },
      {
        question: "Why did WakeUpNow target college students?",
        answer:
          "WakeUpNow aggressively recruited college students because they had large social networks, were eager for income opportunities, and were often less experienced at recognizing predatory business models. This targeting drew significant criticism.",
      },
    ],
  },
  {
    id: "185",
    slug: "ytb-international",
    name: "YTB International",
    category: "mlm",
    tagline: "Online travel booking MLM that multiple states called a pyramid scheme",
    founded_year: 2001,
    hq_location: "Wood River, IL",
    website: "https://ytb.com (defunct)",
    products_summary:
      "Sold travel agency websites and booking services through MLM structure. Multiple state attorneys general filed pyramid scheme lawsuits before company went defunct in 2013.",
    monthly_cost_min: 50,
    monthly_cost_max: 500,
    comp_plan_type: "unilevel",
    overall_rating: 1.1,
    residual_rating: 1.0,
    simplicity_rating: 1.5,
    transparency_rating: 1.0,
    community_rating: 1.5,
    value_rating: 1.0,
    pros: [
      "None — confirmed pyramid scheme by multiple state AGs",
      "Travel product concept was innovative for its time",
      "Legal cases helped establish MLM regulatory precedents",
      "Illustrates how legitimate products can mask pyramid structures",
    ],
    cons: [
      "California AG called it a 'gigantic pyramid scheme'",
      "Illinois AG reached settlement over deceptive practices",
      "Over 90% of participants lost money according to state findings",
      "Company folded in 2013 after regulatory pressure",
    ],
    quick_facts: {
      "Year Founded": "2001",
      "Status": "DEFUNCT 2013",
      "Legal Issues": "Multiple state AG lawsuits",
      "California AG Finding": "Pyramid scheme",
      "Participant Loss Rate": "Over 90%"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Was YTB International a pyramid scheme?",
        answer:
          "Yes, according to multiple state attorneys general. California's AG explicitly called it a 'gigantic pyramid scheme' and Illinois reached a settlement over deceptive practices. State findings showed over 90% of participants lost money.",
      },
      {
        question: "What happened to YTB International?",
        answer:
          "After facing lawsuits from California, Illinois, and other states, YTB International eventually ceased operations in 2013. The company tried rebranding but couldn't overcome the regulatory and legal pressure.",
      },
    ],
  },
  {
    id: "186",
    slug: "world-ventures",
    name: "World Ventures",
    category: "mlm",
    tagline: "DreamTrips travel MLM (Defunct - Filed Bankruptcy 2020)",
    founded_year: 2005,
    hq_location: "Plano, TX",
    website: "defunct - filed bankruptcy 2020",
    products_summary:
      "DreamTrips travel club membership offering discounted group trips. Filed for bankruptcy in 2020 after years of pyramid scheme allegations in multiple countries.",
    monthly_cost_min: 55,
    monthly_cost_max: 130,
    comp_plan_type: "binary",
    overall_rating: 1.2,
    residual_rating: 1.2,
    simplicity_rating: 1.8,
    transparency_rating: 1.5,
    community_rating: 2.5,
    value_rating: 1.5,
    pros: [
      "15 years before bankruptcy — travel concept",
      "Per-customer residual minimal (membership fees)",
      "No inventory requirements",
      "Social community aspect",
    ],
    cons: [
      "Company no longer operating - filed bankruptcy 2020",
      "Norway determined it was an illegal pyramid scheme (2014)",
      "Travel discounts often available cheaper elsewhere",
      "Monthly membership fees ate into any savings",
      "Heavy focus on recruitment over actual travel bookings",
    ],
    quick_facts: {
      "Status": "DEFUNCT - Filed Bankruptcy 2020",
      "Year Founded": "2005",
      "Headquarters": "Plano, TX",
      "Norway Ruling": "Illegal pyramid 2014",
      "Bankruptcy": "Filed 2020, restructured"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is WorldVentures a pyramid scheme?",
        answer:
          "Norway officially determined WorldVentures was an illegal pyramid scheme in 2014. While the company disputes this and continues operating in other countries, the heavy recruitment focus and membership-based model raise ongoing concerns.",
      },
      {
        question: "Are DreamTrips actually good deals?",
        answer:
          "Often not. While DreamTrips offer fun group experiences, the monthly membership fees plus trip costs frequently exceed what you'd pay booking similar travel independently. The 'discount' claims are often misleading.",
      },
    ],
  },
  {
    id: "187",
    slug: "php-agency",
    name: "PHP Agency",
    category: "mlm",
    tagline: "Life insurance MLM targeting Latino communities",
    founded_year: 2009,
    hq_location: "Addison, TX",
    website: "https://phpagency.com",
    products_summary:
      "Life insurance and financial services sales through MLM structure. Known for targeting Latino and immigrant communities with recruitment-heavy approach.",
    monthly_cost_min: 0,
    monthly_cost_max: 200,
    comp_plan_type: "unilevel",
    overall_rating: 2.6,
    residual_rating: 2.5,
    simplicity_rating: 2.4,
    transparency_rating: 2.3,
    community_rating: 3.2,
    value_rating: 2.6,
    pros: [
      "Sells legitimate licensed insurance products",
      "No inventory or product purchase requirements",
      "Strong community and training culture",
      "Provides path to licensed insurance career",
      "Products (life insurance) have genuine value",
    ],
    cons: [
      "Heavy recruitment focus over policy sales",
      "Targets immigrant communities with aggressive tactics",
      "High agent turnover with most earning little",
      "Encourages selling to friends and family first",
    ],
    quick_facts: {
      "Year Founded": "2009",
      "Headquarters": "Addison, TX",
      "Product": "Life insurance",
      "Licensing": "State insurance license required",
      "Target Market": "Latino communities",
      "Business Model": "MLM-style agent recruitment"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is PHP Agency a legitimate insurance company?",
        answer:
          "PHP Agency is a legitimate licensed insurance agency, and agents must obtain proper state licensing. However, the MLM structure means most agents earn very little while the company profits from their sales and recruitment efforts.",
      },
      {
        question: "Why does PHP Agency target Latino communities?",
        answer:
          "PHP Agency was founded to serve Latino and immigrant communities, which can be underserved by traditional insurance. Critics note the recruitment-heavy approach can exploit community trust and family networks.",
      },
    ],
  },
  {
    id: "188",
    slug: "globe-life",
    name: "Globe Life",
    category: "mlm",
    tagline: "Century-old insurance company with MLM-style agent recruitment",
    founded_year: 1900,
    hq_location: "McKinney, TX",
    website: "https://globelifeinc.com",
    products_summary:
      "Life and health insurance products sold through captive agent force using MLM-style tiered recruitment and override commissions. Includes American Income Life subsidiary.",
    monthly_cost_min: 0,
    monthly_cost_max: 100,
    comp_plan_type: "unilevel",
    overall_rating: 2.8,
    residual_rating: 2.7,
    simplicity_rating: 2.8,
    transparency_rating: 2.6,
    community_rating: 3.0,
    value_rating: 2.9,
    pros: [
      "125+ year company history provides stability",
      "Legitimate licensed insurance products",
      "No inventory or product purchase requirements",
      "Comprehensive training and licensing support",
      "Products genuinely help families with coverage",
    ],
    cons: [
      "High agent turnover typical of insurance MLMs",
      "Override compensation incentivizes heavy recruitment",
      "Aggressive lead generation tactics reported",
      "Income heavily depends on building downline",
    ],
    quick_facts: {
      "Year Founded": "1900",
      "Headquarters": "McKinney, TX",
      "Products": "Life/health insurance",
      "Public Company": "NYSE: GL",
      "Subsidiaries": "American Income Life, others",
      "Agent Turnover": "High industry-typical"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is Globe Life a pyramid scheme?",
        answer:
          "Globe Life is a legitimate public insurance company (NYSE: GL), not a pyramid scheme. However, their agent compensation structure uses MLM-style tiers and overrides that incentivize recruitment alongside policy sales.",
      },
      {
        question: "Can you make good money as a Globe Life agent?",
        answer:
          "Like most insurance sales positions, outcomes vary widely. Some agents build successful careers, but high turnover suggests most don't achieve significant income. Success typically requires both strong sales ability and team building.",
      },
    ],
  },
  {
    id: "189",
    slug: "vestige-marketing",
    name: "Vestige Marketing",
    category: "mlm",
    tagline: "India's largest homegrown MLM selling health and personal care",
    founded_year: 2004,
    hq_location: "New Delhi, India",
    website: "https://myvestige.com",
    products_summary:
      "Health supplements, personal care, homecare, and agricultural products. India's largest domestic MLM company with millions of distributors across Asia.",
    monthly_cost_min: 30,
    monthly_cost_max: 150,
    comp_plan_type: "binary",
    overall_rating: 2.1,
    residual_rating: 2.0,
    simplicity_rating: 2.0,
    transparency_rating: 1.8,
    community_rating: 2.5,
    value_rating: 2.2,
    pros: [
      "Large established company in Indian market",
      "Wide product range beyond just supplements",
      "Low startup costs compared to Western MLMs",
      "Strong brand recognition in India",
    ],
    cons: [
      "Products significantly overpriced versus retail alternatives",
      "Compensation structure requires significant customer base for meaningful income",
      "Heavy focus on recruitment over retail sales",
      "Regulatory scrutiny in India over MLM practices",
    ],
    quick_facts: {
      "Year Founded": "2004",
      "Headquarters": "New Delhi, India",
      "Market": "Primarily India/Asia",
      "Distributors": "Millions claimed",
      "Products": "Health, personal care, home"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is Vestige legal in India?",
        answer:
          "Yes, Vestige operates legally in India, though MLMs face ongoing regulatory scrutiny. The company has defended against pyramid scheme allegations, but critics point to the recruitment-heavy compensation structure.",
      },
      {
        question: "How much do Vestige distributors actually earn?",
        answer:
          "Earnings depend on building and retaining a customer base. As with most MLMs, meaningful income requires significant sales volume. The company promotes success stories of top earners.",
      },
    ],
  },
  {
    id: "190",
    slug: "forevergreen",
    name: "ForeverGreen International",
    category: "mlm",
    tagline: "Food-based supplements MLM that went defunct around 2018",
    founded_year: 2004,
    hq_location: "Orem, UT",
    website: "https://forevergreen.org (defunct)",
    products_summary:
      "SIGRA whole-food supplements, marine phytoplankton products, and PowerStrips topical patches. Company experienced financial difficulties and went defunct around 2018.",
    monthly_cost_min: 75,
    monthly_cost_max: 250,
    comp_plan_type: "binary",
    overall_rating: 1.7,
    residual_rating: 1.5,
    simplicity_rating: 1.8,
    transparency_rating: 1.5,
    community_rating: 2.0,
    value_rating: 1.7,
    pros: [
      "Innovative food-based supplement concepts",
      "PowerStrips had devoted customer following",
      "Products avoided synthetic vitamin controversy",
      "International expansion showed ambition",
    ],
    cons: [
      "Company went defunct leaving distributors stranded",
      "SEC filings showed persistent financial losses",
      "Product health claims lacked clinical evidence",
      "Binary plan heavily favored early adopters",
    ],
    quick_facts: {
      "Year Founded": "2004",
      "Status": "DEFUNCT ~2018",
      "Headquarters": "Orem, UT",
      "Known For": "PowerStrips, marine phytoplankton",
      "SEC Status": "Delisted"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What happened to ForeverGreen?",
        answer:
          "ForeverGreen experienced persistent financial losses despite revenue growth, leading to stock delisting and eventual closure around 2018. Distributors lost their business investments when the company folded.",
      },
      {
        question: "Did ForeverGreen's PowerStrips actually work?",
        answer:
          "PowerStrips were topical patches claimed to provide pain relief and other benefits. While some users reported positive experiences, the health claims lacked clinical validation and the FDA sent warning letters about unsubstantiated claims.",
      },
    ],
  },
  {
    id: "191",
    slug: "max-international",
    name: "Max International",
    category: "mlm",
    tagline: "Glutathione supplements claiming cellular health benefits",
    founded_year: 2006,
    hq_location: "Salt Lake City, UT",
    website: "https://maxinternational.com",
    products_summary:
      "MaxGXL, MaxONE, and Cellgevity glutathione-boosting supplements claiming to support cellular health, detoxification, and anti-aging through the body's master antioxidant.",
    monthly_cost_min: 75,
    monthly_cost_max: 200,
    comp_plan_type: "binary",
    overall_rating: 2.0,
    residual_rating: 1.9,
    simplicity_rating: 2.0,
    transparency_rating: 1.8,
    community_rating: 2.3,
    value_rating: 2.0,
    pros: [
      "Glutathione is a legitimate antioxidant with research backing",
      "Company has operated since 2006",
      "Products focus on single ingredient category",
      "Some published studies on glutathione precursors",
    ],
    cons: [
      "Oral glutathione absorption is scientifically questionable",
      "Products extremely expensive for supplement category",
      "Health claims go beyond established science",
      "Binary compensation heavily favors recruiters",
    ],
    quick_facts: {
      "Year Founded": "2006",
      "Headquarters": "Salt Lake City, UT",
      "Product Focus": "Glutathione supplements",
      "Flagship": "Cellgevity, MaxONE",
      "Price Range": "$60-120/month"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Does Max International's glutathione supplements actually work?",
        answer:
          "While glutathione is a legitimate antioxidant, scientific consensus questions whether oral supplements effectively raise glutathione levels. The body typically breaks down ingested glutathione before absorption. Max's products claim to use precursors instead.",
      },
      {
        question: "Can you make money with Max International?",
        answer:
          "Meaningful income requires building a substantial customer base. As with most MLMs, compensation is tied to sales volume and team building.",
      },
    ],
  },
  {
    id: "192",
    slug: "stemtech",
    name: "Stemtech",
    category: "mlm",
    tagline: "Stem cell nutrition supplements with questionable science",
    founded_year: 2005,
    hq_location: "San Clemente, CA",
    website: "https://stemtech.com",
    products_summary:
      "Supplements claiming to support adult stem cell release and migration, including SE2 and StemFlo products. Based on Aphanizomenon flos-aquae algae and other ingredients.",
    monthly_cost_min: 60,
    monthly_cost_max: 200,
    comp_plan_type: "unilevel",
    overall_rating: 1.9,
    residual_rating: 1.8,
    simplicity_rating: 2.0,
    transparency_rating: 1.6,
    community_rating: 2.0,
    value_rating: 1.8,
    pros: [
      "Unique positioning in stem cell nutrition niche",
      "Company has operated for nearly two decades",
      "Some published research on key ingredients",
      "International presence in multiple countries",
    ],
    cons: [
      "Stem cell nutrition claims lack mainstream scientific acceptance",
      "FTC warned about unsubstantiated health claims",
      "Products extremely expensive for algae supplements",
      "Regulatory scrutiny over marketing claims",
    ],
    quick_facts: {
      "Year Founded": "2005",
      "Headquarters": "San Clemente, CA",
      "Product Focus": "Stem cell nutrition",
      "Key Ingredient": "AFA blue-green algae",
      "Regulatory Issues": "FTC warnings on claims"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Can supplements really support stem cells?",
        answer:
          "The scientific consensus is skeptical. While Stemtech cites studies on their ingredients, mainstream medical opinion does not support the idea that supplements can meaningfully enhance stem cell activity. The FTC has warned the company about unsubstantiated claims.",
      },
      {
        question: "Is Stemtech approved by the FDA?",
        answer:
          "No supplement is 'approved' by the FDA — they're regulated differently than drugs. Stemtech's products are sold as dietary supplements, meaning they cannot legally claim to treat or cure diseases. The company has faced regulatory scrutiny over marketing claims.",
      },
    ],
  },
  {
    id: "193",
    slug: "xooma-worldwide",
    name: "Xooma Worldwide",
    category: "mlm",
    tagline: "Alkaline water sachets claiming pH health benefits",
    founded_year: 2006,
    hq_location: "Celebration, FL",
    website: "https://xooma.com",
    products_summary:
      "X2O mineral sachets that alkalize water, along with nutritional supplements. Based on the alkaline water health trend and pH balance pseudoscience.",
    monthly_cost_min: 40,
    monthly_cost_max: 150,
    comp_plan_type: "unilevel",
    overall_rating: 2.0,
    residual_rating: 1.9,
    simplicity_rating: 2.2,
    transparency_rating: 1.8,
    community_rating: 2.2,
    value_rating: 1.9,
    pros: [
      "Simple product concept easy to demonstrate",
      "Sachets are portable and convenient",
      "Company has operated since 2006",
      "Low monthly cost compared to other MLMs",
    ],
    cons: [
      "Alkaline water health claims are scientifically debunked",
      "Your body automatically regulates pH regardless of what you drink",
      "Similar mineral products available much cheaper",
      "Built on pseudoscientific health trend",
    ],
    quick_facts: {
      "Year Founded": "2006",
      "Headquarters": "Celebration, FL",
      "Product Focus": "Alkaline water sachets",
      "Flagship Product": "X2O",
      "Scientific Basis": "Alkaline diet theory (debunked)"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Does alkaline water actually improve health?",
        answer:
          "No. The alkaline water/alkaline diet theory has been thoroughly debunked by mainstream science. Your body tightly regulates blood pH regardless of what you consume, and stomach acid neutralizes alkaline water immediately. The health claims are pseudoscience.",
      },
      {
        question: "What do X2O sachets actually do?",
        answer:
          "X2O sachets add minerals to water and raise its pH. While the minerals themselves aren't harmful, the claimed health benefits from 'alkalizing' your body are not supported by science. Similar mineral supplements cost far less outside the MLM model.",
      },
    ],
  },
  {
    id: "194",
    slug: "utility-warehouse",
    name: "Utility Warehouse / Telecom Plus",
    category: "mlm",
    tagline: "UK utilities bundle with MLM distribution model",
    founded_year: 1996,
    hq_location: "London, UK",
    website: "https://utilitywarehouse.co.uk",
    products_summary:
      "Bundled home services including gas, electricity, broadband, mobile, and insurance through network marketing distribution. Largest MLM in the UK by revenue.",
    monthly_cost_min: 0,
    monthly_cost_max: 100,
    comp_plan_type: "unilevel",
    overall_rating: 2.8,
    residual_rating: 3.0,
    simplicity_rating: 2.8,
    transparency_rating: 2.7,
    community_rating: 2.8,
    value_rating: 2.9,
    pros: [
      "Products are essential services people already pay for",
      "No inventory or product purchases required",
      "Genuine savings possible through bundling",
      "Public company (LSE: TEP) provides transparency",
      "Residual income from utility bills is sustainable",
    ],
    cons: [
      "Utility prices not always cheapest on market",
      "Still requires recruitment to earn significant income",
      "Lock-in periods for some services",
      "Most distributors earn modest amounts",
    ],
    quick_facts: {
      "Year Founded": "1996",
      "Headquarters": "London, UK",
      "Public Company": "LSE: TEP (Telecom Plus)",
      "Products": "Gas, electric, broadband, mobile",
      "UK Position": "Largest domestic MLM",
      "Customer Retention": "High due to utility nature"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is Utility Warehouse cheaper than other providers?",
        answer:
          "Sometimes, especially for bundled services. However, individual utilities may be cheaper elsewhere. The convenience of a single bill and the cashback program provide value, but always compare prices before switching.",
      },
      {
        question: "How is Utility Warehouse different from other MLMs?",
        answer:
          "Unlike most MLMs selling consumable products, UW sells essential services people already use. This creates more sustainable residual income and higher customer retention. However, significant earnings still require building a team.",
      },
    ],
  },
  {
    id: "195",
    slug: "exp-realty",
    name: "eXp Realty",
    category: "mlm",
    tagline: "Cloud-based real estate brokerage with revenue sharing model",
    founded_year: 2009,
    hq_location: "Bellingham, WA",
    website: "https://exprealty.com",
    products_summary:
      "Cloud-based real estate brokerage offering agents higher commission splits plus revenue sharing and stock options. Uses virtual world technology for training and collaboration.",
    monthly_cost_min: 85,
    monthly_cost_max: 250,
    comp_plan_type: "unilevel",
    overall_rating: 3.5,
    residual_rating: 3.3,
    simplicity_rating: 3.2,
    transparency_rating: 3.5,
    community_rating: 3.8,
    value_rating: 3.6,
    pros: [
      "Higher commission splits than traditional brokerages (80/20)",
      "Revenue sharing creates passive income from recruited agents",
      "Stock options align agent and company interests",
      "Cloud-based model reduces overhead costs",
      "Legitimate real estate transactions, not product inventory",
      "Public company (NASDAQ: EXPI) provides transparency",
    ],
    cons: [
      "Revenue sharing incentivizes recruitment over mentoring",
      "Virtual model may lack hands-on support for new agents",
      "Monthly fees higher than some traditional brokerages",
      "Success still primarily depends on selling real estate",
    ],
    quick_facts: {
      "Year Founded": "2009",
      "Headquarters": "Bellingham, WA",
      "Public Company": "NASDAQ: EXPI",
      "Agent Split": "80/20 with cap",
      "Technology": "Cloud-based virtual world",
      "Revenue Share Levels": "7 tiers",
      "Monthly Fee": "$85-250"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is eXp Realty an MLM or legitimate brokerage?",
        answer:
          "eXp is a legitimate licensed real estate brokerage that uses MLM-style revenue sharing for agent recruitment. Agents earn primarily from selling real estate, with revenue sharing as supplemental income. It's a hybrid model.",
      },
      {
        question: "How does eXp revenue sharing work?",
        answer:
          "eXp pays revenue share from the company dollar (their portion of commissions) for agents you recruit, extending 7 levels deep. This creates incentive to recruit productive agents but doesn't require you to recruit to earn from your own sales.",
      },
    ],
  },
  {
    id: "196",
    slug: "keller-williams",
    name: "Keller Williams",
    category: "mlm",
    tagline: "World's largest real estate franchise with profit sharing model",
    founded_year: 1983,
    hq_location: "Austin, TX",
    website: "https://kellerwilliams.com",
    products_summary:
      "Real estate brokerage franchise with profit sharing system that rewards agents for recruiting productive agents. World's largest real estate company by agent count.",
    monthly_cost_min: 50,
    monthly_cost_max: 300,
    comp_plan_type: "unilevel",
    overall_rating: 3.3,
    residual_rating: 3.0,
    simplicity_rating: 3.2,
    transparency_rating: 3.2,
    community_rating: 3.5,
    value_rating: 3.4,
    pros: [
      "World's largest real estate company provides brand recognition",
      "Profit sharing creates passive income from market center",
      "Extensive training through KW Maps coaching",
      "Strong agent culture and community",
      "Legitimate real estate career path",
    ],
    cons: [
      "Profit sharing depends on market center profitability",
      "Desk fees and royalties can be significant",
      "Recruitment incentives create MLM-like dynamics",
      "Commission splits vary by market center",
    ],
    quick_facts: {
      "Year Founded": "1983",
      "Headquarters": "Austin, TX",
      "Size": "Largest RE company by agent count",
      "Structure": "Franchise model",
      "Training": "KW Maps coaching system",
      "Profit Share": "Based on market center profits"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is Keller Williams an MLM?",
        answer:
          "Keller Williams is a legitimate real estate franchise, not technically an MLM. However, their profit sharing system rewards agents for recruiting productive agents, creating MLM-like dynamics. Income primarily comes from selling real estate.",
      },
      {
        question: "How does Keller Williams profit sharing work?",
        answer:
          "When your market center is profitable, you receive a share based on agents you've attracted and their production. It's funded from company profits, not agent commissions. This differs from MLM override systems.",
      },
    ],
  },
  {
    id: "197",
    slug: "im-mastery-academy",
    name: "IM Mastery Academy",
    category: "mlm",
    tagline: "Forex Education MLM — Regulatory Warnings in Multiple Countries",
    founded_year: 2013,
    hq_location: "Boca Raton, FL",
    website: "https://imarketslive.com",
    products_summary:
      "Forex and cryptocurrency trading education, signals, and tools sold through MLM structure. Formerly iMarketsLive. Multiple regulatory warnings worldwide.",
    monthly_cost_min: 175,
    monthly_cost_max: 325,
    comp_plan_type: "binary",
    overall_rating: 1.6,
    residual_rating: 1.6,
    simplicity_rating: 1.8,
    transparency_rating: 1.5,
    community_rating: 2.5,
    value_rating: 1.6,
    pros: [
      "12 years in business — forex education",
      "Per-customer residual ~$15-25/mo on subscriptions",
      "No physical inventory",
      "Active trading community",
    ],
    cons: [
      "Regulatory warnings from multiple countries (Spain, Belgium, Italy)",
      "Education quality questioned versus cheaper alternatives",
      "Heavy recruitment focus over actual trading education",
      "Most participants lose money while leaders profit from subscriptions",
    ],
    quick_facts: {
      "Year Founded": "2013",
      "Headquarters": "Boca Raton, FL",
      "Former Name": "iMarketsLive",
      "Monthly Cost": "$175-325",
      "Regulatory Warnings": "Spain, Belgium, Italy, others",
      "Focus": "Forex/crypto trading education"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Has IM Mastery Academy received regulatory warnings?",
        answer:
          "Yes. Financial regulators in Spain, Belgium, Italy, and other countries have issued warnings about iMarketsLive/IM Mastery Academy, citing concerns about the compensation structure and educational claims.",
      },
      {
        question: "Can you learn forex trading from IM Academy?",
        answer:
          "The platform does provide forex content, but similar or better education is available for far less money. The high monthly fees primarily fund the MLM structure. Most successful traders recommend lower-cost learning resources.",
      },
    ],
  },
  {
    id: "198",
    slug: "lyoness-myworld",
    name: "Lyoness / myWorld",
    category: "mlm",
    tagline: "Cashback Shopping Network — EU Regulatory Investigations",
    founded_year: 2003,
    hq_location: "Graz, Austria",
    website: "https://myworld-benefits.com",
    products_summary:
      "Cashback loyalty shopping program and membership network. Has faced regulatory investigations in multiple European countries with mixed legal outcomes.",
    monthly_cost_min: 0,
    monthly_cost_max: 3000,
    comp_plan_type: "matrix",
    overall_rating: 1.6,
    residual_rating: 1.5,
    simplicity_rating: 1.5,
    transparency_rating: 1.3,
    community_rating: 1.8,
    value_rating: 1.5,
    pros: [
      "Legitimate partner merchants offer real cashback",
      "No product inventory requirements",
      "Shopping-based concept is easy to understand",
      "Still operating in many countries",
    ],
    cons: [
      "Found to be pyramid scheme by Austrian courts",
      "Complex unit/voucher system obscures true costs",
      "Expensive upfront investments for positioning",
      "Multiple EU countries have investigated or banned",
    ],
    quick_facts: {
      "Year Founded": "2003",
      "Headquarters": "Graz, Austria",
      "Current Name": "myWorld",
      "Legal Status": "Austria court: pyramid scheme",
      "EU Investigations": "Multiple countries",
      "Unit Purchases": "Up to €3000+"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is Lyoness/myWorld a pyramid scheme?",
        answer:
          "Austrian courts have ruled Lyoness operated as a pyramid scheme. The company has faced investigations in multiple EU countries. While it continues operating (rebranded as myWorld), serious legal concerns remain.",
      },
      {
        question: "How does Lyoness make money if shopping is free?",
        answer:
          "While basic shopping cashback is free, the MLM aspect involves purchasing expensive 'units' or voucher packages for position in the matrix. These upfront investments, not shopping, drive the pyramid structure.",
      },
    ],
  },
  {
    id: "199",
    slug: "wakaya-perfection",
    name: "Wakaya Perfection",
    category: "mlm",
    tagline: "Organic Fiji ginger and turmeric from private island paradise",
    founded_year: 2014,
    hq_location: "Wakaya Island, Fiji",
    website: "https://wakayaperfection.com",
    products_summary:
      "Organic ginger, turmeric, kava, and dilo oil products sourced from private Wakaya Island in Fiji. Founded by David Gilmour, owner of the island.",
    monthly_cost_min: 75,
    monthly_cost_max: 250,
    comp_plan_type: "unilevel",
    overall_rating: 1.9,
    residual_rating: 1.8,
    simplicity_rating: 2.0,
    transparency_rating: 1.8,
    community_rating: 2.0,
    value_rating: 1.8,
    pros: [
      "Products come from certified organic island source",
      "Unique origin story and branding",
      "Ginger and turmeric have some research-backed benefits",
      "Low minimum orders compared to other MLMs",
    ],
    cons: [
      "Products extremely expensive for ginger/turmeric",
      "Private island marketing doesn't justify premium pricing",
      "Limited product line reduces customer retention",
      "Small company with limited distributor support",
    ],
    quick_facts: {
      "Year Founded": "2014",
      "Headquarters": "Wakaya Island, Fiji",
      "Founder": "David Gilmour (island owner)",
      "Products": "Organic ginger, turmeric, kava",
      "Certification": "Certified organic"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What makes Wakaya Perfection products special?",
        answer:
          "Products are sourced from Wakaya Island in Fiji and certified organic. While the origin story is unique, ginger and turmeric from any certified organic source would provide similar benefits at lower cost.",
      },
      {
        question: "Is Wakaya Perfection worth the premium price?",
        answer:
          "Probably not for most consumers. The private island sourcing is primarily marketing — equivalent organic ginger and turmeric products cost significantly less. The MLM structure adds substantial markup.",
      },
    ],
  },
  {
    id: "200",
    slug: "ariix",
    name: "ARIIX",
    category: "mlm",
    tagline: "Supplements and water purification MLM merged into NewAge",
    founded_year: 2011,
    hq_location: "Bountiful, UT",
    website: "https://ariix.com (merged)",
    products_summary:
      "Nutrifii supplements, Puritii water filtration, and Slenderiiz weight management products. Company merged with NewAge Inc. which later filed bankruptcy.",
    monthly_cost_min: 75,
    monthly_cost_max: 250,
    comp_plan_type: "binary",
    overall_rating: 1.9,
    residual_rating: 1.8,
    simplicity_rating: 1.9,
    transparency_rating: 1.7,
    community_rating: 2.2,
    value_rating: 1.9,
    pros: [
      "Puritii water filtration was innovative product category",
      "Products had certifications and testing",
      "Multiple product lines provided variety",
      "International presence before merger",
    ],
    cons: [
      "Merged into NewAge which filed bankruptcy in 2022",
      "Products significantly overpriced",
      "Binary plan favored heavy recruiters",
      "Post-merger confusion left distributors uncertain",
    ],
    quick_facts: {
      "Year Founded": "2011",
      "Status": "Merged into NewAge (bankrupt 2022)",
      "Original HQ": "Bountiful, UT",
      "Products": "Nutrifii, Puritii, Slenderiiz",
      "Outcome": "NewAge bankruptcy, now PartnerCo"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What happened to ARIIX?",
        answer:
          "ARIIX merged with NewAge Inc., a publicly traded company that consolidated multiple MLM brands. NewAge subsequently filed bankruptcy in August 2022 and emerged as PartnerCo. ARIIX products and distributors were absorbed into this transition.",
      },
      {
        question: "Can you still buy ARIIX products?",
        answer:
          "ARIIX products may still be available through the PartnerCo successor company, though product lines and availability have changed significantly through the merger and bankruptcy process.",
      },
    ],
  },
  {
    id: "201",
    slug: "bioperformance",
    name: "BioPerformance",
    category: "mlm",
    tagline: "Fake fuel additive pills exposed as fraud by Texas AG",
    founded_year: 2006,
    hq_location: "San Antonio, TX",
    website: "https://bioperformance.com (defunct)",
    products_summary:
      "Gas pills claimed to improve fuel economy when added to gas tank. Texas Attorney General shut down the company in 2007 after testing proved products were worthless.",
    monthly_cost_min: 50,
    monthly_cost_max: 300,
    comp_plan_type: "binary",
    overall_rating: 1.0,
    residual_rating: 1.0,
    simplicity_rating: 1.5,
    transparency_rating: 1.0,
    community_rating: 1.5,
    value_rating: 1.0,
    pros: [
      "None — complete fraud shut down by authorities",
      "Serves as textbook example of MLM pseudoscience",
      "Quick regulatory action protected consumers",
      "Case demonstrates importance of product testing",
    ],
    cons: [
      "Products were completely fake — naphthalene moth balls",
      "Texas AG testing proved zero fuel economy benefit",
      "Founders faced criminal charges",
      "Thousands of distributors lost money to fraud",
    ],
    quick_facts: {
      "Year Founded": "2006",
      "Status": "SHUT DOWN 2007",
      "Shut Down By": "Texas Attorney General",
      "Product Reality": "Naphthalene (moth balls)",
      "Claimed Benefit": "Improved fuel economy",
      "Actual Benefit": "None — complete fraud"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What were BioPerformance gas pills actually made of?",
        answer:
          "Testing by the Texas Attorney General revealed BioPerformance pills were primarily naphthalene — the main ingredient in moth balls. They provided zero fuel economy benefit despite dramatic claims.",
      },
      {
        question: "How did BioPerformance get caught?",
        answer:
          "The Texas AG investigated after complaints and had the pills independently tested. The tests proved the products were worthless, leading to immediate shutdown and legal action against the founders.",
      },
    ],
  },
  {
    id: "202",
    slug: "global-information-network",
    name: "Global Information Network (GIN)",
    category: "mlm",
    tagline: "Kevin Trudeau's 'secret society' wealth club — shut down for fraud",
    founded_year: 2009,
    hq_location: "United States (defunct)",
    website: "https://ginclub.net (defunct)",
    products_summary:
      "Exclusive membership club claiming to share wealth secrets from a 'secret society.' Founder Kevin Trudeau was convicted of fraud and sentenced to prison.",
    monthly_cost_min: 150,
    monthly_cost_max: 1000,
    comp_plan_type: "unilevel",
    overall_rating: 1.0,
    residual_rating: 1.0,
    simplicity_rating: 1.0,
    transparency_rating: 1.0,
    community_rating: 1.5,
    value_rating: 1.0,
    pros: [
      "None — founder convicted of fraud and imprisoned",
      "Demonstrates how charismatic leaders exploit followers",
      "Serves as case study in MLM cult dynamics",
      "FTC action helped warn consumers",
    ],
    cons: [
      "Founder Kevin Trudeau convicted, served 10 years in prison",
      "'Secret society' was fabricated marketing",
      "Expensive memberships provided little value",
      "Members recruited into pyramid structure",
    ],
    quick_facts: {
      "Year Founded": "2009",
      "Status": "DEFUNCT — founder imprisoned",
      "Founder": "Kevin Trudeau",
      "Trudeau Sentence": "10 years federal prison",
      "Conviction": "Criminal contempt of court",
      "Claimed Concept": "Secret society wealth secrets"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What happened to Kevin Trudeau?",
        answer:
          "Kevin Trudeau was convicted of criminal contempt for violating court orders about deceptive infomercials and served approximately 10 years in federal prison. He was released in 2022 but remains subject to over $37 million in FTC judgments.",
      },
      {
        question: "Was there really a secret society behind GIN?",
        answer:
          "No. The 'secret society' was completely fabricated marketing. Trudeau invented the concept to sell expensive memberships. There was no ancient organization sharing wealth secrets — it was a scam.",
      },
    ],
  },
  {
    id: "203",
    slug: "six-figure-mentors",
    name: "Six Figure Mentors",
    category: "mlm",
    tagline: "High-ticket online business education MLM now defunct",
    founded_year: 2010,
    hq_location: "United Kingdom",
    website: "https://thesixfigurementors.com (defunct)",
    products_summary:
      "High-ticket online business and digital marketing education sold through affiliate MLM structure. Promised to teach members how to build six-figure online businesses.",
    monthly_cost_min: 97,
    monthly_cost_max: 2500,
    comp_plan_type: "unilevel",
    overall_rating: 1.5,
    residual_rating: 1.3,
    simplicity_rating: 1.5,
    transparency_rating: 1.3,
    community_rating: 2.0,
    value_rating: 1.4,
    pros: [
      "Provided some legitimate digital marketing education",
      "Community support for online business learners",
      "Training on affiliate marketing fundamentals",
      "Focused on skills rather than physical products",
    ],
    cons: [
      "High-ticket upsells pushed aggressively",
      "Success primarily came from recruiting others into program",
      "Similar education available much cheaper elsewhere",
      "Business model was essentially selling the dream of selling the dream",
    ],
    quick_facts: {
      "Year Founded": "2010",
      "Status": "DEFUNCT ~2019",
      "Headquarters": "United Kingdom",
      "Model": "High-ticket education MLM",
      "Price Range": "$97-2500+ for programs",
      "Promise": "Six-figure online business"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What happened to Six Figure Mentors?",
        answer:
          "SFM appears to have ceased operations around 2019. The high-ticket MLM education space became crowded, and the model of 'teaching people to sell the program that teaches them' proved unsustainable.",
      },
      {
        question: "Was Six Figure Mentors a scam?",
        answer:
          "While SFM provided some legitimate education, the business model was problematic. Success stories primarily came from people who earned commissions recruiting others, not from applying the training to independent businesses.",
      },
    ],
  },
  {
    id: "204",
    slug: "neals-yard-remedies",
    name: "Neal's Yard Remedies Organic",
    category: "mlm",
    tagline: "UK organic beauty brand with network marketing division",
    founded_year: 1981,
    hq_location: "London, UK",
    website: "https://uk.nyrorganic.com",
    products_summary:
      "Organic health, beauty, skincare, and essential oil products. British heritage brand with retail stores plus NYR Organic network marketing arm.",
    monthly_cost_min: 50,
    monthly_cost_max: 200,
    comp_plan_type: "unilevel",
    overall_rating: 2.7,
    residual_rating: 2.5,
    simplicity_rating: 2.8,
    transparency_rating: 2.6,
    community_rating: 2.9,
    value_rating: 2.7,
    pros: [
      "Established 40+ year heritage brand with retail presence",
      "Genuinely certified organic products",
      "Products available through multiple channels, not MLM-only",
      "UK B Corp certification demonstrates ethical commitments",
      "Lower pressure than typical MLM structures",
    ],
    cons: [
      "Products premium priced even for organic category",
      "MLM consultants compete with company's own retail",
      "Essential oil health claims can be overstated",
      "Most consultants earn modest income",
    ],
    quick_facts: {
      "Year Founded": "1981",
      "Headquarters": "London, UK",
      "Certification": "B Corp, Soil Association Organic",
      "Channels": "Retail + MLM (NYR Organic)",
      "Products": "Organic beauty, skincare, oils",
      "Heritage": "40+ years"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is Neal's Yard Remedies the same as NYR Organic?",
        answer:
          "NYR Organic is the network marketing/MLM division of Neal's Yard Remedies. The parent brand sells through retail stores and online, while NYR Organic uses independent consultants. Products are the same.",
      },
      {
        question: "Are Neal's Yard products worth the premium price?",
        answer:
          "The products are genuinely certified organic with quality ingredients. However, similar organic products exist at lower price points. The premium reflects both quality and MLM markup.",
      },
    ],
  },
  {
    id: "205",
    slug: "ctfo",
    name: "CTFO",
    category: "mlm",
    tagline: "Free-to-join CBD hemp oil MLM with no startup cost",
    founded_year: 2015,
    hq_location: "Temecula, CA",
    website: "https://myctfo.com",
    products_summary:
      "CBD hemp oil products including tinctures, topicals, skincare, and pet products. Positions itself as free-to-join MLM with no required purchases.",
    monthly_cost_min: 0,
    monthly_cost_max: 150,
    comp_plan_type: "unilevel",
    overall_rating: 2.3,
    residual_rating: 2.2,
    simplicity_rating: 2.5,
    transparency_rating: 2.2,
    community_rating: 2.4,
    value_rating: 2.3,
    pros: [
      "Genuinely free to join with no required purchases",
      "CBD products have growing consumer acceptance",
      "No autoship requirements to remain active",
      "Lower financial risk than typical MLMs",
      "Product variety includes pet products",
    ],
    cons: [
      "CBD market is crowded with cheaper alternatives",
      "Free-to-join model means saturated distributor base",
      "Product quality varies in unregulated CBD industry",
      "Commission rates lower than MLMs with startup costs",
    ],
    quick_facts: {
      "Year Founded": "2015",
      "Headquarters": "Temecula, CA",
      "Startup Cost": "Free",
      "Products": "CBD oil, topicals, pet products",
      "Required Purchases": "None",
      "CBD Source": "US-grown hemp"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is CTFO really free to join?",
        answer:
          "Yes, CTFO is genuinely free to join with no required purchases or monthly autoship. This lowers financial risk but also means a large, saturated distributor base competing for sales.",
      },
      {
        question: "How does CTFO compare to other CBD brands?",
        answer:
          "CTFO products are mid-range priced for CBD. Many non-MLM CBD brands offer similar or better products at lower prices. The main CTFO advantage is the business opportunity, not product value.",
      },
    ],
  },
  {
    id: "206",
    slug: "cbd-biocare",
    name: "CBD BioCare",
    category: "mlm",
    tagline: "CBD oil MLM with focus on high-quality hemp extracts",
    founded_year: 2016,
    hq_location: "Chandler, AZ",
    website: "https://cbdbiocare.com",
    products_summary:
      "CBD oil tinctures, topicals, capsules, and pet products. Emphasizes third-party testing and high-quality hemp sourcing through MLM distribution.",
    monthly_cost_min: 50,
    monthly_cost_max: 200,
    comp_plan_type: "unilevel",
    overall_rating: 2.2,
    residual_rating: 2.1,
    simplicity_rating: 2.3,
    transparency_rating: 2.2,
    community_rating: 2.3,
    value_rating: 2.1,
    pros: [
      "Third-party lab testing provides transparency",
      "Variety of CBD product formats",
      "No large upfront investment required",
      "Products include popular pet CBD category",
    ],
    cons: [
      "CBD market oversaturated with cheaper options",
      "MLM markup makes products less competitive",
      "Regulatory uncertainty in CBD industry",
      "Most affiliates earn minimal commissions",
    ],
    quick_facts: {
      "Year Founded": "2016",
      "Headquarters": "Chandler, AZ",
      "Products": "CBD oil, topicals, capsules, pet",
      "Testing": "Third-party lab tested",
      "Hemp Source": "US-grown"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Is CBD BioCare's CBD high quality?",
        answer:
          "CBD BioCare does provide third-party lab testing results, which is positive for transparency. However, many non-MLM CBD brands offer similar or higher quality at lower prices without the MLM markup.",
      },
      {
        question: "Can you make money selling CBD BioCare?",
        answer:
          "Like most MLMs, the majority of CBD BioCare affiliates earn minimal income. The saturated CBD market and competition from cheaper alternatives makes it difficult to build substantial sales.",
      },
    ],
  },
  {
    id: "207",
    slug: "noni-by-newage",
    name: "Noni by NewAge",
    category: "mlm",
    tagline: "Tahitian Noni juice company bankrupted with parent NewAge in 2022",
    founded_year: 1996,
    hq_location: "Salt Lake City, UT",
    website: "https://morinda.com (merged/bankrupt)",
    products_summary:
      "Tahitian Noni juice and related products. Originally Morinda, merged into NewAge Inc. which filed bankruptcy in August 2022. Now part of PartnerCo.",
    monthly_cost_min: 75,
    monthly_cost_max: 200,
    comp_plan_type: "unilevel",
    overall_rating: 1.5,
    residual_rating: 1.3,
    simplicity_rating: 1.8,
    transparency_rating: 1.3,
    community_rating: 2.0,
    value_rating: 1.5,
    pros: [
      "Noni fruit has some antioxidant properties",
      "Long history in MLM industry (since 1996)",
      "Products now part of PartnerCo successor company",
      "Loyal customer base for noni juice",
    ],
    cons: [
      "Parent company NewAge filed bankruptcy 2022",
      "Noni health claims lack strong scientific support",
      "Products expensive for fruit juice category",
      "Corporate instability disrupted distributor businesses",
    ],
    quick_facts: {
      "Year Founded": "1996",
      "Original Name": "Morinda",
      "Status": "Parent bankrupt Aug 2022",
      "Current Owner": "PartnerCo",
      "Product": "Tahitian Noni juice",
      "Health Claims": "Limited scientific support"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What happened to Morinda/Noni by NewAge?",
        answer:
          "Morinda rebranded as Noni by NewAge after merging with NewAge Inc. NewAge filed bankruptcy in August 2022 and emerged as PartnerCo. The brand and products continue under new ownership.",
      },
      {
        question: "Does noni juice actually have health benefits?",
        answer:
          "Noni fruit contains some antioxidants and nutrients, but the dramatic health claims made by MLM marketing are not well supported by clinical research. It's fruit juice, not medicine.",
      },
    ],
  },
  {
    id: "208",
    slug: "lifestyles-global",
    name: "Lifestyles by Global",
    category: "mlm",
    tagline: "Canadian nutritional supplements MLM operating since 1994",
    founded_year: 1994,
    hq_location: "Toronto, Canada",
    website: "https://lsgl.com",
    products_summary:
      "Nutritional supplements, weight management, and personal care products. Canadian MLM company with international presence, known for Intra herbal drink.",
    monthly_cost_min: 50,
    monthly_cost_max: 200,
    comp_plan_type: "unilevel",
    overall_rating: 2.0,
    residual_rating: 1.9,
    simplicity_rating: 2.0,
    transparency_rating: 1.8,
    community_rating: 2.2,
    value_rating: 2.0,
    pros: [
      "Company has operated since 1994 showing longevity",
      "Products manufactured in-house for quality control",
      "Intra herbal drink has loyal customer following",
      "International presence in multiple countries",
    ],
    cons: [
      "Products significantly overpriced versus alternatives",
      "Health claims for Intra lack strong clinical support",
      "Limited brand recognition despite 30 years",
      "Most distributors earn minimal income",
    ],
    quick_facts: {
      "Year Founded": "1994",
      "Headquarters": "Toronto, Canada",
      "Flagship Product": "Intra herbal drink",
      "Products": "Supplements, weight loss, personal care",
      "Manufacturing": "In-house facilities",
      "Markets": "Canada, international"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "What is Lifestyles Intra?",
        answer:
          "Intra is a botanical herbal extract drink that's been Lifestyles' flagship product for decades. While it has loyal users, the health claims made for it are not strongly supported by clinical research.",
      },
      {
        question: "Is Lifestyles by Global still in business?",
        answer:
          "Yes, Lifestyles Global (LSGL) continues operating after 30 years. However, the company has remained relatively small compared to major MLMs, and most distributors earn modest to no income.",
      },
    ],
  },
  {
    id: "209",
    slug: "vidafy",
    name: "Vidafy",
    category: "mlm",
    tagline: "Zeolite detox drops MLM claiming to remove toxins",
    founded_year: 2021,
    hq_location: "Austin, TX",
    website: "https://vidafy.com",
    products_summary:
      "Micronized zeolite detox drops and cellular health supplements. Claims zeolite minerals remove toxins and heavy metals from the body.",
    monthly_cost_min: 50,
    monthly_cost_max: 200,
    comp_plan_type: "binary",
    overall_rating: 1.7,
    residual_rating: 1.6,
    simplicity_rating: 1.8,
    transparency_rating: 1.5,
    community_rating: 2.0,
    value_rating: 1.6,
    pros: [
      "Zeolite has some research as mineral supplement",
      "Simple product line easy to understand",
      "Lower startup costs than some MLMs",
      "Detox market has consumer interest",
    ],
    cons: [
      "Detox claims are largely pseudoscience",
      "Your body already detoxifies through liver and kidneys",
      "Zeolite heavy metal claims lack strong evidence",
      "New company (2021) lacks track record",
    ],
    quick_facts: {
      "Year Founded": "2021",
      "Headquarters": "Austin, TX",
      "Products": "Zeolite detox drops",
      "Key Claim": "Removes toxins and heavy metals",
      "Scientific Basis": "Limited evidence"
    },
    last_updated: "2026-03-20",
    is_featured: false,
    is_published: true,
    created_at: "2026-03-20T00:00:00Z",
    faq: [
      {
        question: "Do zeolite drops actually detox your body?",
        answer:
          "The 'detox' concept is largely marketing. Your liver and kidneys already remove toxins effectively. While zeolite has some research in industrial and limited medical applications, claims about oral zeolite supplements removing toxins lack strong clinical evidence.",
      },
      {
        question: "Is Vidafy a legitimate company?",
        answer:
          "Vidafy is a legal MLM company, but being legal doesn't validate the product claims. The zeolite detox market is based on pseudoscientific concepts, and the company is very new (founded 2021) without established track record.",
      },
    ],
  },
];
