import { Company } from '@/types';

export const companiesBatchC5: Company[] = [
  {
    id: '716',
    slug: 'tastefully-simple',
    name: 'Tastefully Simple',
    category: 'direct_sales',
    founded_year: 1995,
    hq_location: 'Alexandria, Minnesota, USA',
    website: 'https://www.tastefullysimple.com',
    products_summary: 'Convenient gourmet food mixes, seasonings, and pantry staples designed for busy families. Products include soup mixes, baking mixes, dips, sauces, and specialty foods.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.8,
    residual_rating: 2.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.0,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Quality food products', 'Well-established brand since 1995', 'Strong party plan model', 'Low monthly requirements'],
    cons: ['Premium pricing on products', 'Competitive direct sales food market', 'Limited residual income potential'],
    quick_facts: {
      'Founded': '1995',
      'Business Model': 'Party plan direct sales',
      'Products': 'Gourmet food mixes and seasonings'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Simple ingredients, simply delicious',
    faq: [
      { question: 'What is the startup cost for Tastefully Simple?', answer: 'Starter kits typically range from $99-$199 with product samples and business materials.' },
      { question: 'How do consultants earn money?', answer: 'Through retail profit on product sales at home parties and online, plus team bonuses for recruiting.' }
    ]
  },
  {
    id: '717',
    slug: 'cocoa-exchange',
    name: 'The Cocoa Exchange',
    category: 'direct_sales',
    founded_year: 2007,
    hq_location: 'Scottsdale, Arizona, USA',
    website: 'https://www.thecocoaexchange.com',
    products_summary: 'Premium chocolate products, gourmet hot chocolate, chocolate bars, truffles, and chocolate-based gifts. Focus on high-quality artisan chocolate.',
    monthly_cost_min: 0,
    monthly_cost_max: 40,
    comp_plan_type: 'Party plan',
    overall_rating: 2.6,
    residual_rating: 2.0,
    simplicity_rating: 3.0,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Unique niche product', 'High-quality artisan chocolate', 'Fun party atmosphere', 'Low overhead costs'],
    cons: ['Very narrow product line', 'Seasonal sales fluctuations', 'High product pricing', 'Limited market appeal'],
    quick_facts: {
      'Founded': '2007',
      'Business Model': 'Party plan direct sales',
      'Products': 'Premium chocolate and cocoa products'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Chocolate parties worth celebrating',
    faq: [
      { question: 'How much do consultants earn per party?', answer: 'Average party sales range from $200-$500 with 20-25% commission rates.' },
      { question: 'Is there a monthly purchase requirement?', answer: 'No mandatory monthly purchases, but staying active requires quarterly sales activity.' }
    ]
  },
  {
    id: '718',
    slug: 'uppercase-living',
    name: 'Uppercase Living',
    category: 'direct_sales',
    founded_year: 2003,
    hq_location: 'Montgomery, Illinois, USA',
    website: 'https://www.uppercaseliving.com',
    products_summary: 'Vinyl wall expressions, home decor, personalized signs, and decorative accessories. Focus on customizable inspirational quotes and designs for home decorating.',
    monthly_cost_min: 0,
    monthly_cost_max: 35,
    comp_plan_type: 'Party plan',
    overall_rating: 2.7,
    residual_rating: 2.0,
    simplicity_rating: 3.0,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 3.0,
    pros: ['Creative product line', 'Customization options appeal to customers', 'Visual party demonstrations work well', 'Reasonable pricing'],
    cons: ['Declining market for vinyl wall decor', 'Competition from mass retailers', 'Trend-dependent sales'],
    quick_facts: {
      'Founded': '2003',
      'Business Model': 'Party plan direct sales',
      'Products': 'Vinyl wall expressions and home decor'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Express yourself on your walls',
    faq: [
      { question: 'What is the cost to join?', answer: 'Starter kits range from $99-$249 depending on the package selected.' },
      { question: 'Can I sell online?', answer: 'Yes, consultants receive a personalized website for online sales in addition to home parties.' }
    ]
  },
  {
    id: '719',
    slug: 'creative-memories',
    name: 'Creative Memories',
    category: 'direct_sales',
    founded_year: 1987,
    hq_location: 'St. Cloud, Minnesota, USA',
    website: 'https://www.creativememories.com',
    products_summary: 'Scrapbooking supplies, photo albums, digital design tools, and memory preservation products. Focus on helping families preserve and share their stories.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.5,
    residual_rating: 2.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Strong brand legacy since 1987', 'Quality archival-safe products', 'Passionate consultant community', 'Helpful training resources'],
    cons: ['Declining scrapbooking market', 'High product costs', 'Digital photography has reduced demand', 'Company filed bankruptcy in 2013 (later revived)'],
    quick_facts: {
      'Founded': '1987',
      'Business Model': 'Party plan direct sales',
      'Products': 'Scrapbooking and memory preservation'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Preserve your memories beautifully',
    faq: [
      { question: 'Did Creative Memories go out of business?', answer: 'The company filed bankruptcy in 2013 but was purchased and relaunched in 2014, continuing operations today.' },
      { question: 'What commission do advisors earn?', answer: 'Commission rates range from 20-30% depending on sales volume and rank.' }
    ]
  },
  {
    id: '720',
    slug: 'close-to-my-heart',
    name: 'Close To My Heart',
    category: 'direct_sales',
    founded_year: 1987,
    hq_location: 'Bluffdale, Utah, USA',
    website: 'https://www.closetomyheart.com',
    products_summary: 'Scrapbooking products, rubber stamps, paper crafting supplies, and memory keeping tools. Offers coordinated collections and seasonal designs.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.6,
    residual_rating: 2.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Quality coordinated product lines', 'Strong consultant community', 'Good training and support', 'Exclusive designs'],
    cons: ['Shrinking scrapbooking market', 'Premium pricing', 'Heavy competition in craft space', 'Requires inventory investment'],
    quick_facts: {
      'Founded': '1987',
      'Business Model': 'Party plan direct sales',
      'Products': 'Scrapbooking and paper crafting supplies'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Celebrate relationships through scrapbooking',
    faq: [
      { question: 'What does it cost to become a consultant?', answer: 'New consultant kits start at around $99 with product samples and business tools.' },
      { question: 'Is there a minimum sales requirement?', answer: 'To remain active, consultants need $300 in sales per quarter.' }
    ]
  },
  {
    id: '721',
    slug: 'stampin-up',
    name: 'Stampin\' Up!',
    category: 'direct_sales',
    founded_year: 1988,
    hq_location: 'Riverton, Utah, USA',
    website: 'https://www.stampinup.com',
    products_summary: 'Rubber stamps, paper crafting supplies, card making materials, inks, embellishments, and creative tools for handmade cards and paper projects.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.9,
    residual_rating: 2.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.0,
    community_rating: 3.5,
    value_rating: 2.5,
    pros: ['Strong brand recognition', 'Quality exclusive products', 'Excellent training and community', 'Creative product releases', 'Better retention than most MLMs'],
    cons: ['Premium pricing on supplies', 'Quarterly minimums required', 'Saturated market in some areas', 'Requires ongoing inventory'],
    quick_facts: {
      'Founded': '1988',
      'Business Model': 'Party plan direct sales',
      'Products': 'Rubber stamps and card making supplies'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Create handmade cards with confidence',
    faq: [
      { question: 'How much does the Stampin\' Up starter kit cost?', answer: 'The starter kit costs $99 and includes $125 worth of products you choose, plus business supplies.' },
      { question: 'What are the ongoing requirements?', answer: 'Demonstrators must have $300 in sales per quarter to remain active and eligible for commissions.' }
    ]
  },
  {
    id: '722',
    slug: 'partylite',
    name: 'PartyLite',
    category: 'direct_sales',
    founded_year: 1973,
    hq_location: 'Plymouth, Massachusetts, USA',
    website: 'https://www.partylite.com',
    products_summary: 'Candles, candle holders, home fragrance products, and decorative accessories. Known for quality scented candles and home ambiance products.',
    monthly_cost_min: 0,
    monthly_cost_max: 40,
    comp_plan_type: 'Party plan',
    overall_rating: 2.7,
    residual_rating: 2.5,
    simplicity_rating: 3.0,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Established brand since 1973', 'Quality candle products', 'Good party demonstrations', 'Seasonal collections drive repeat sales'],
    cons: ['Heavy market saturation', 'Competition from mass-market candles', 'Premium pricing', 'Declining party plan model'],
    quick_facts: {
      'Founded': '1973',
      'Business Model': 'Party plan direct sales',
      'Products': 'Candles and home fragrance'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Light up your home with fragrance',
    faq: [
      { question: 'How much can PartyLite consultants earn?', answer: 'Consultants earn 20-25% commission on sales, with higher rates for recruiting and team building.' },
      { question: 'What is the startup cost?', answer: 'Starter kits range from $99-$199 with candles, holders, and business materials.' }
    ]
  },
  {
    id: '723',
    slug: 'yankee-candle-direct',
    name: 'Yankee Candle (Direct Sales)',
    category: 'direct_sales',
    founded_year: 1969,
    hq_location: 'South Deerfield, Massachusetts, USA',
    website: 'https://www.yankeecandle.com',
    products_summary: 'Premium scented candles, home fragrance products, wax melts, and accessories. Previously operated party plan consultants (program discontinued).',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Discontinued',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.0,
    transparency_rating: 2.0,
    community_rating: 2.0,
    value_rating: 2.5,
    pros: ['Strong brand recognition', 'Quality products', 'Retail stores support brand', 'Wide product variety'],
    cons: ['Direct sales program discontinued', 'No longer active opportunity', 'Retail availability reduces need for consultants', 'Historical reference only'],
    quick_facts: {
      'Founded': '1969',
      'Business Model': 'Former party plan (now retail)',
      'Products': 'Scented candles and home fragrance'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'America\'s favorite candle - now retail only',
    faq: [
      { question: 'Can I still become a Yankee Candle consultant?', answer: 'No, Yankee Candle discontinued their direct sales consultant program and now sells through retail stores and their website.' },
      { question: 'When did the direct sales program end?', answer: 'The party plan consultant program ended in the early 2000s as the company focused on retail expansion.' }
    ]
  },
  {
    id: '724',
    slug: 'bath-body-works-affiliate',
    name: 'Bath & Body Works Affiliate',
    category: 'direct_sales',
    founded_year: 1990,
    hq_location: 'Columbus, Ohio, USA',
    website: 'https://www.bathandbodyworks.com',
    products_summary: 'Personal care products, home fragrance, candles, and body care items. Affiliate program for online promotion (not MLM or party plan).',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.5,
    pros: ['Zero startup cost', 'Strong brand recognition', 'No inventory required', 'Simple commission model', 'Popular products'],
    cons: ['Low commission rates (typically 1-4%)', 'High competition', 'No residual income', 'Retail availability reduces conversions'],
    quick_facts: {
      'Founded': '1990',
      'Business Model': 'Affiliate marketing (retail)',
      'Products': 'Body care and home fragrance'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Affiliate program for America\'s fragrance favorite',
    faq: [
      { question: 'How does the Bath & Body Works affiliate program work?', answer: 'Affiliates share links to products and earn a small commission (1-4%) on qualifying purchases made through their links.' },
      { question: 'Is this the same as a direct sales business?', answer: 'No, this is a traditional affiliate program - you simply promote products online, no parties or recruiting required.' }
    ]
  },
  {
    id: '725',
    slug: 'damsel-in-defense',
    name: 'Damsel in Defense',
    category: 'direct_sales',
    founded_year: 2011,
    hq_location: 'Riverside, California, USA',
    website: 'https://www.damselindefense.net',
    products_summary: 'Personal safety and self-defense products including stun guns, pepper spray, personal alarms, safety keychains, and protective equipment for women.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.4,
    residual_rating: 2.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Unique product niche', 'Mission-driven company', 'Empowering message', 'Growing safety awareness market'],
    cons: ['Limited repeat purchase products', 'Legal restrictions on some products by state', 'Small market size', 'Premium pricing'],
    quick_facts: {
      'Founded': '2011',
      'Business Model': 'Party plan direct sales',
      'Products': 'Personal safety and self-defense'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Equip, Empower, Educate women in self-defense',
    faq: [
      { question: 'What is the cost to join Damsel in Defense?', answer: 'Starter kits range from $99-$299 with product samples and business materials.' },
      { question: 'Are there legal issues selling these products?', answer: 'Some self-defense products have state-specific restrictions. Consultants must comply with local laws regarding stun guns and pepper spray.' }
    ]
  },
  {
    id: '726',
    slug: 'passion-parties-defunct',
    name: 'Passion Parties (Defunct)',
    category: 'direct_sales',
    founded_year: 1994,
    hq_location: 'Las Vegas, Nevada, USA',
    website: 'https://www.passionparties.com',
    products_summary: 'Adult romance products, intimacy enhancement items, and relationship products sold at home parties. Company closed in 2016.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Party plan (defunct)',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.0,
    pros: ['Unique party concept', 'High commission rates historically', 'Strong repeat customers', 'Empowering message for women'],
    cons: ['Company closed in 2016', 'No longer in operation', 'Faced regulatory challenges', 'Market shifted to online retail'],
    quick_facts: {
      'Founded': '1994',
      'Business Model': 'Party plan (defunct 2016)',
      'Products': 'Adult romance and intimacy products'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Former romance party plan company',
    faq: [
      { question: 'Is Passion Parties still in business?', answer: 'No, Passion Parties ceased operations in 2016 after 22 years in business.' },
      { question: 'What happened to Passion Parties?', answer: 'The company faced financial difficulties and regulatory challenges, ultimately closing in 2016.' }
    ]
  },
  {
    id: '727',
    slug: 'slumber-parties-defunct',
    name: 'Slumber Parties (Defunct)',
    category: 'direct_sales',
    founded_year: 1999,
    hq_location: 'McKinney, Texas, USA',
    website: 'https://www.slumberparties.com',
    products_summary: 'Romance products, intimacy items, and adult party products. Similar to Passion Parties, sold through home party model. Company merged and discontinued.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Party plan (defunct)',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.0,
    pros: ['Fun party atmosphere', 'Good commission structure historically', 'Loyal customer base', 'Women-focused business'],
    cons: ['Company no longer operating', 'Merged with competitor then closed', 'Online retailers took market share', 'Regulatory complications'],
    quick_facts: {
      'Founded': '1999',
      'Business Model': 'Party plan (defunct)',
      'Products': 'Romance and intimacy products'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Former romance party company',
    faq: [
      { question: 'Can I still join Slumber Parties?', answer: 'No, Slumber Parties merged with Pure Romance and the Slumber Parties brand was discontinued.' },
      { question: 'When did Slumber Parties close?', answer: 'The company was acquired by Pure Romance in 2014 and the Slumber Parties name was phased out.' }
    ]
  },
  {
    id: '728',
    slug: 'clever-container',
    name: 'Clever Container',
    category: 'direct_sales',
    founded_year: 2007,
    hq_location: 'Wheeling, Illinois, USA',
    website: 'https://www.clevercontainer.com',
    products_summary: 'Home organization products, storage solutions, containers, closet organizers, and space-saving items to help organize homes.',
    monthly_cost_min: 0,
    monthly_cost_max: 40,
    comp_plan_type: 'Party plan',
    overall_rating: 2.6,
    residual_rating: 2.0,
    simplicity_rating: 3.0,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Practical everyday products', 'Good party demonstrations', 'Growing home organization trend', 'Visual product appeal'],
    cons: ['Heavy competition from retailers', 'Premium pricing vs Amazon/Target', 'Limited unique products', 'One-time purchase items'],
    quick_facts: {
      'Founded': '2007',
      'Business Model': 'Party plan direct sales',
      'Products': 'Home organization and storage'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Organize your life with clever solutions',
    faq: [
      { question: 'How much does it cost to start?', answer: 'Starter kits range from $99-$249 with product samples and party supplies.' },
      { question: 'What commission do consultants earn?', answer: 'Consultants earn 20-25% commission on sales plus bonuses for team building.' }
    ]
  },
  {
    id: '729',
    slug: 'epicure',
    name: 'Epicure',
    category: 'direct_sales',
    founded_year: 1997,
    hq_location: 'Montreal, Quebec, Canada',
    website: 'https://www.epicure.com',
    products_summary: 'Health-focused meal solutions, spice blends, cooking tools, and nutritious food products. Focus on clean eating and quick meal preparation.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.7,
    residual_rating: 2.5,
    simplicity_rating: 3.0,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Health-conscious product line', 'Good quality ingredients', 'Growing clean eating market', 'Strong Canadian presence', 'Practical cooking tools'],
    cons: ['Premium pricing', 'Competitive food market', 'Requires ongoing purchases for hosts', 'Limited US presence'],
    quick_facts: {
      'Founded': '1997',
      'Business Model': 'Party plan direct sales',
      'Products': 'Healthy meal solutions and spices'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Good food made easy and healthy',
    faq: [
      { question: 'Is Epicure available in the United States?', answer: 'Yes, Epicure expanded to the US market, though the company is based in Canada.' },
      { question: 'What is the commission structure?', answer: 'Consultants earn 20-33% commission depending on sales volume and rank.' }
    ]
  },
  {
    id: '730',
    slug: 'princess-house',
    name: 'Princess House',
    category: 'direct_sales',
    founded_year: 1963,
    hq_location: 'Taunton, Massachusetts, USA',
    website: 'https://www.princesshouse.com',
    products_summary: 'Crystal, glassware, cookware, cutlery, and kitchenware products. Known for quality entertaining and kitchen products sold through home parties.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.5,
    residual_rating: 2.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Long-established brand since 1963', 'Quality crystal and cookware', 'Lifetime warranty on many products', 'Strong Hispanic market presence'],
    cons: ['Expensive products limit sales', 'Declining formal entertaining market', 'Heavy competition from retailers', 'Requires inventory investment'],
    quick_facts: {
      'Founded': '1963',
      'Business Model': 'Party plan direct sales',
      'Products': 'Crystal, glassware, and kitchenware'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Quality crystal and kitchenware since 1963',
    faq: [
      { question: 'Does Princess House still exist?', answer: 'Yes, Princess House continues to operate with a focus on the Hispanic market in the United States.' },
      { question: 'What is the startup cost?', answer: 'Starter kits typically range from $99-$199 with product samples and business materials.' }
    ]
  },
  {
    id: '731',
    slug: 'longaberger-defunct',
    name: 'Longaberger (Defunct)',
    category: 'direct_sales',
    founded_year: 1973,
    hq_location: 'Dresden, Ohio, USA',
    website: 'https://www.longaberger.com',
    products_summary: 'Handcrafted baskets, pottery, and home decor items. Famous for American-made baskets sold through home parties. Company ceased operations in 2018.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Party plan (defunct)',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.0,
    pros: ['Quality American-made baskets', 'Strong brand loyalty historically', 'Collectible items', 'Iconic basket building headquarters'],
    cons: ['Company closed in 2018', 'Very expensive products', 'Market demand declined', 'Attempted relaunch failed', 'No longer operating'],
    quick_facts: {
      'Founded': '1973',
      'Business Model': 'Party plan (ceased 2018)',
      'Products': 'Handcrafted baskets and home decor'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Former American basket company',
    faq: [
      { question: 'Is Longaberger still in business?', answer: 'The direct sales operation ceased in 2018. There have been attempts to revive the brand, but the original party plan model is defunct.' },
      { question: 'Why did Longaberger fail?', answer: 'The company struggled with declining sales, changing consumer preferences, high product costs, and debt, leading to closure in 2018.' }
    ]
  },
  {
    id: '732',
    slug: 'southern-living-at-home-defunct',
    name: 'Southern Living At Home (Defunct)',
    category: 'direct_sales',
    founded_year: 1999,
    hq_location: 'Birmingham, Alabama, USA',
    website: 'https://www.southernlivinghome.com',
    products_summary: 'Home decor, entertaining items, and lifestyle products with Southern style. Licensed from Southern Living magazine. Closed in 2012.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Party plan (defunct)',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.0,
    pros: ['Strong brand recognition from magazine', 'Quality home decor products', 'Southern lifestyle appeal', 'Good party atmosphere'],
    cons: ['Closed in 2012', 'No longer in operation', 'Expensive products', 'Limited market beyond Southern demographic'],
    quick_facts: {
      'Founded': '1999',
      'Business Model': 'Party plan (ceased 2012)',
      'Products': 'Southern-style home decor'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Former Southern-style home decor company',
    faq: [
      { question: 'What happened to Southern Living At Home?', answer: 'The company ceased operations in 2012 due to declining sales and the challenging direct sales market.' },
      { question: 'Can I still buy Southern Living At Home products?', answer: 'The direct sales company is closed, though some vintage items may be available through resale markets.' }
    ]
  },
  {
    id: '733',
    slug: 'touchstone-crystal-swarovski',
    name: 'Touchstone Crystal (Swarovski)',
    category: 'direct_sales',
    founded_year: 2009,
    hq_location: 'Cranston, Rhode Island, USA',
    website: 'https://www.touchstonecrystal.com',
    products_summary: 'Swarovski crystal jewelry including necklaces, bracelets, earrings, and accessories. Official direct sales division of Swarovski.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.8,
    residual_rating: 2.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.0,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Backed by prestigious Swarovski brand', 'Quality crystal jewelry', 'Lower price point than main Swarovski line', 'Beautiful product demonstrations', 'Strong brand recognition'],
    cons: ['Premium pricing', 'Competition from Swarovski retail stores', 'Limited to jewelry category', 'Market saturation in some areas'],
    quick_facts: {
      'Founded': '2009',
      'Business Model': 'Party plan direct sales',
      'Products': 'Swarovski crystal jewelry'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Swarovski crystal jewelry for everyone',
    faq: [
      { question: 'Is Touchstone Crystal the same as Swarovski?', answer: 'Touchstone Crystal is the official direct sales division of Swarovski, offering exclusive designs at accessible price points.' },
      { question: 'What commission do consultants earn?', answer: 'Consultants earn 25% commission on personal sales plus bonuses for team building.' }
    ]
  },
  {
    id: '734',
    slug: 'discovery-toys',
    name: 'Discovery Toys',
    category: 'direct_sales',
    founded_year: 1978,
    hq_location: 'Livermore, California, USA',
    website: 'https://www.discoverytoys.com',
    products_summary: 'Educational toys, games, books, and learning materials for children. Focus on developmentally appropriate products that teach while entertaining.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.6,
    residual_rating: 2.0,
    simplicity_rating: 3.0,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Quality educational products', 'Long company history since 1978', 'Appeal to parents and educators', 'Safety-tested toys'],
    cons: ['Heavy competition from mass retailers', 'Premium pricing', 'Amazon dominates toy market', 'Limited exclusive products'],
    quick_facts: {
      'Founded': '1978',
      'Business Model': 'Party plan direct sales',
      'Products': 'Educational toys and games'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Play and learn together',
    faq: [
      { question: 'How much does it cost to become a Discovery Toys consultant?', answer: 'Starter kits range from $99-$199 with toy samples and business materials.' },
      { question: 'What are the ongoing requirements?', answer: 'Consultants should maintain quarterly sales activity to remain active and eligible for commissions.' }
    ]
  },
  {
    id: '735',
    slug: 'usborne-books',
    name: 'Usborne Books',
    category: 'direct_sales',
    founded_year: 1973,
    hq_location: 'Tulsa, Oklahoma, USA (US division)',
    website: 'https://www.usbornebooksandmore.com',
    products_summary: 'Children\'s books from Usborne Publishing including educational books, storybooks, activity books, and learning resources sold through home shows.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.7,
    residual_rating: 2.0,
    simplicity_rating: 3.0,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 3.0,
    pros: ['Quality children\'s books', 'Strong publisher reputation', 'Educational value appeals to parents', 'Repeat customers common', 'Good product variety'],
    cons: ['Competition from Amazon and bookstores', 'Quarterly minimums required', 'Book market highly competitive', 'Shipping costs can be high'],
    quick_facts: {
      'Founded': '1973',
      'Business Model': 'Party plan direct sales',
      'Products': 'Children\'s educational books'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Quality children\'s books for every age',
    faq: [
      { question: 'What commission do Usborne consultants earn?', answer: 'Consultants earn 25% commission on sales, with opportunities for additional bonuses.' },
      { question: 'Is there a minimum sales requirement?', answer: 'Yes, consultants must meet quarterly sales minimums to remain active (typically around $300).' }
    ]
  },
  {
    id: '736',
    slug: 'learning-tree-books',
    name: 'Learning Tree Educational Store',
    category: 'direct_sales',
    founded_year: 1985,
    hq_location: 'Various locations, USA',
    website: 'https://www.learningtree.com',
    products_summary: 'Educational books, learning materials, toys, and teaching resources. Note: This refers to various educational retail/party plan concepts, not the software training company.',
    monthly_cost_min: 0,
    monthly_cost_max: 40,
    comp_plan_type: 'Party plan',
    overall_rating: 2.5,
    residual_rating: 2.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.5,
    community_rating: 2.5,
    value_rating: 2.5,
    pros: ['Educational focus appeals to parents', 'Variety of learning products', 'Support for homeschoolers', 'Quality materials'],
    cons: ['Highly competitive market', 'Amazon dominance in books', 'Premium pricing', 'Smaller company recognition'],
    quick_facts: {
      'Founded': '1985',
      'Business Model': 'Party plan/retail hybrid',
      'Products': 'Educational books and materials'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Educational resources for growing minds',
    faq: [
      { question: 'Is Learning Tree a direct sales company?', answer: 'Some Learning Tree educational stores operated party plan models, though structures varied by location and franchise.' },
      { question: 'How does this differ from bookstores?', answer: 'Learning Tree focused on curated educational materials with consultant guidance, versus general retail bookstores.' }
    ]
  },
  {
    id: '737',
    slug: 'once-upon-child-affiliate',
    name: 'Once Upon A Child Franchise',
    category: 'direct_sales',
    founded_year: 1992,
    hq_location: 'Minneapolis, Minnesota, USA',
    website: 'https://www.onceuponachild.com',
    products_summary: 'Resale franchise for gently used children\'s clothing, toys, and baby items. Buy-sell-trade retail model (not MLM/party plan).',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Franchise (not direct sales)',
    overall_rating: 3.0,
    residual_rating: 2.5,
    simplicity_rating: 2.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['Established franchise model', 'Growing resale market', 'Sustainable business model', 'Not MLM - actual retail stores', 'Strong brand recognition'],
    cons: ['High franchise investment required ($250k+)', 'Not a home business', 'Requires retail location', 'Not direct sales/MLM'],
    quick_facts: {
      'Founded': '1992',
      'Business Model': 'Franchise retail (not MLM)',
      'Products': 'Children\'s resale clothing and items'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Buy and sell kids\' stuff',
    faq: [
      { question: 'Can I work from home with Once Upon A Child?', answer: 'No, this is a brick-and-mortar franchise requiring a retail location, not a home-based business or MLM.' },
      { question: 'How much does a franchise cost?', answer: 'Initial investment ranges from $250,000-$400,000 including franchise fees, build-out, and inventory.' }
    ]
  },
  {
    id: '738',
    slug: 'kid-to-kid-franchise',
    name: 'Kid to Kid Franchise',
    category: 'direct_sales',
    founded_year: 1992,
    hq_location: 'Salt Lake City, Utah, USA',
    website: 'https://www.kidtokid.com',
    products_summary: 'Children\'s resale franchise for clothing, toys, furniture, and baby gear. Buy-sell-trade retail stores (not MLM/party plan).',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Franchise (not direct sales)',
    overall_rating: 3.0,
    residual_rating: 2.5,
    simplicity_rating: 2.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['Proven franchise system', 'Growing sustainability trend', 'Not an MLM', 'Real retail business', 'Strong margins on resale'],
    cons: ['Significant capital required', 'Requires physical store', 'Not home-based', 'Not direct sales model', 'Location dependent'],
    quick_facts: {
      'Founded': '1992',
      'Business Model': 'Franchise retail (not MLM)',
      'Products': 'Children\'s resale items'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'The smarter way to buy and sell kids\' stuff',
    faq: [
      { question: 'Is Kid to Kid an MLM?', answer: 'No, Kid to Kid is a traditional franchise business requiring a retail storefront, not a multi-level marketing or party plan company.' },
      { question: 'What is the investment to open a store?', answer: 'Total investment typically ranges from $250,000-$450,000 including franchise fee, location, and inventory.' }
    ]
  },
  {
    id: '739',
    slug: 'norwex',
    name: 'Norwex',
    category: 'direct_sales',
    founded_year: 1994,
    hq_location: 'Oslo, Norway (US: Austin, TX)',
    website: 'https://www.norwex.com',
    products_summary: 'Microfiber cleaning products, eco-friendly household items, and chemical-free cleaning solutions. Focus on sustainable living and reducing chemicals.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.7,
    residual_rating: 2.5,
    simplicity_rating: 3.0,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.0,
    pros: ['Quality microfiber products', 'Eco-friendly mission resonates', 'Products work well', 'Growing green cleaning market', 'Strong customer loyalty'],
    cons: ['Very expensive products', 'Exaggerated antibacterial claims questioned', 'Monthly minimums required', 'High market saturation', 'Premium pricing limits market'],
    quick_facts: {
      'Founded': '1994',
      'Business Model': 'Party plan direct sales',
      'Products': 'Microfiber and eco-friendly cleaning'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Clean without chemicals',
    faq: [
      { question: 'Is Norwex really chemical-free?', answer: 'Norwex microfiber products clean with water only, though some products do contain chemicals. The BacLock antibacterial claims have been questioned.' },
      { question: 'How much do consultants earn?', answer: 'Commission starts at 20% and can increase to 35% based on sales volume and rank.' }
    ]
  },
  {
    id: '740',
    slug: 'body-shop-at-home-defunct',
    name: 'The Body Shop At Home (Defunct)',
    category: 'direct_sales',
    founded_year: 2001,
    hq_location: 'Littlehampton, UK',
    website: 'https://www.thebodyshop.com',
    products_summary: 'Natural beauty products, skincare, and cosmetics sold through party plan. Direct sales division of The Body Shop retail brand. Closed in 2017.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Party plan (defunct)',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.5,
    community_rating: 2.5,
    value_rating: 2.5,
    pros: ['Strong retail brand support', 'Quality natural products', 'Ethical sourcing mission', 'Brand recognition'],
    cons: ['Program closed in 2017', 'Retail stores undermined direct sales', 'No longer operating', 'Competed with own retail locations'],
    quick_facts: {
      'Founded': '2001',
      'Business Model': 'Party plan (ceased 2017)',
      'Products': 'Natural beauty and skincare'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Former party plan division of The Body Shop',
    faq: [
      { question: 'Can I still become a Body Shop At Home consultant?', answer: 'No, The Body Shop closed their direct sales division in 2017 to focus on retail stores and online sales.' },
      { question: 'Why did Body Shop At Home close?', answer: 'The company found the party plan model conflicted with their retail strategy and discontinued it in 2017.' }
    ]
  },
  {
    id: '741',
    slug: 'wildtree-defunct',
    name: 'Wildtree (Defunct)',
    category: 'direct_sales',
    founded_year: 2002,
    hq_location: 'Dover, New Hampshire, USA',
    website: 'https://www.wildtree.com',
    products_summary: 'All-natural food products, oils, seasonings, and meal solutions. Focus on preservative-free cooking ingredients. Company ceased operations around 2020.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Party plan (defunct)',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.0,
    pros: ['All-natural ingredients', 'Unique product line', 'Health-conscious positioning', 'Good party demonstrations'],
    cons: ['Company closed around 2020', 'No longer in operation', 'Very expensive products', 'Limited market appeal'],
    quick_facts: {
      'Founded': '2002',
      'Business Model': 'Party plan (defunct ~2020)',
      'Products': 'All-natural food products'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Former all-natural food company',
    faq: [
      { question: 'Is Wildtree still in business?', answer: 'No, Wildtree ceased operations around 2020 and is no longer accepting new representatives or orders.' },
      { question: 'What happened to Wildtree?', answer: 'The company struggled with market competition and financial challenges, ultimately closing operations.' }
    ]
  },
  {
    id: '742',
    slug: 'tomboy-tools-defunct',
    name: 'Tomboy Tools (Defunct)',
    category: 'direct_sales',
    founded_year: 2001,
    hq_location: 'Studio City, California, USA',
    website: 'https://www.tomboytools.com',
    products_summary: 'Tools and home repair products marketed to women through party plan. "Tools for women" concept. Company closed operations around 2018.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Party plan (defunct)',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.0,
    pros: ['Unique niche targeting women', 'Empowering concept', 'Educational workshops', 'Quality tool selection'],
    cons: ['Company closed around 2018', 'Limited market size', 'Expensive compared to retail', 'No longer operating', 'Concept didn\'t scale'],
    quick_facts: {
      'Founded': '2001',
      'Business Model': 'Party plan (defunct ~2018)',
      'Products': 'Tools and home repair items'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Former women-focused tool company',
    faq: [
      { question: 'What happened to Tomboy Tools?', answer: 'Tomboy Tools ceased operations around 2018 due to market challenges and limited scalability.' },
      { question: 'Can I still buy Tomboy Tools products?', answer: 'The company is no longer operating, though similar tools are available through retail hardware stores.' }
    ]
  },
  {
    id: '743',
    slug: 'duct-tape-marketing',
    name: 'Duct Tape Marketing',
    category: 'direct_sales',
    founded_year: 2003,
    hq_location: 'Kansas City, Missouri, USA',
    website: 'https://www.ducttapemarketing.com',
    products_summary: 'Marketing consulting and training services, not a product-based MLM. Offers marketing system licenses and certifications for consultants. Franchise/licensing model.',
    monthly_cost_min: 500,
    monthly_cost_max: 2000,
    comp_plan_type: 'Licensing/Franchise',
    overall_rating: 3.0,
    residual_rating: 3.0,
    simplicity_rating: 2.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.0,
    pros: ['Legitimate consulting business model', 'Not an MLM', 'Proven marketing methodology', 'Professional training and certification', 'Real business skills'],
    cons: ['High monthly licensing fees', 'Requires marketing expertise', 'Competitive consulting market', 'Not passive income', 'Significant time investment'],
    quick_facts: {
      'Founded': '2003',
      'Business Model': 'Licensing/consulting franchise',
      'Products': 'Marketing consulting and training'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Marketing system for small business consultants',
    faq: [
      { question: 'Is Duct Tape Marketing an MLM?', answer: 'No, it\'s a professional licensing and certification program for marketing consultants, not a multi-level marketing company.' },
      { question: 'What does certification cost?', answer: 'The certified consultant program involves training fees and ongoing monthly licensing fees, typically $1,000+ per month.' }
    ]
  },
  {
    id: '744',
    slug: 'home-garden-party-defunct',
    name: 'Home & Garden Party (Defunct)',
    category: 'direct_sales',
    founded_year: 1996,
    hq_location: 'Marshall, Texas, USA',
    website: 'https://www.homeandgardenparty.com',
    products_summary: 'Home decor, candles, garden accessories, and seasonal decorations sold through party plan. Company closed in 2013.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Party plan (defunct)',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.0,
    pros: ['Wide variety of home decor', 'Seasonal product appeal', 'Good party demonstrations', 'Quality decorative items'],
    cons: ['Company closed in 2013', 'No longer operating', 'Market shifted to retail', 'Competition from big box stores killed model'],
    quick_facts: {
      'Founded': '1996',
      'Business Model': 'Party plan (ceased 2013)',
      'Products': 'Home decor and garden accessories'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Former home decor party plan company',
    faq: [
      { question: 'Is Home & Garden Party still around?', answer: 'No, Home & Garden Party ceased operations in 2013 after 17 years in business.' },
      { question: 'Why did the company close?', answer: 'Competition from retail stores, online shopping, and declining party plan model led to closure in 2013.' }
    ]
  },
  {
    id: '745',
    slug: 'two-sisters-gourmet',
    name: 'Two Sisters Gourmet',
    category: 'direct_sales',
    founded_year: 1994,
    hq_location: 'Memphis, Tennessee, USA',
    website: 'https://www.twosistersgourmet.com',
    products_summary: 'Gourmet food mixes, dips, seasonings, and specialty food products. Focus on quick and easy meal solutions and entertaining products.',
    monthly_cost_min: 0,
    monthly_cost_max: 40,
    comp_plan_type: 'Party plan',
    overall_rating: 2.5,
    residual_rating: 2.0,
    simplicity_rating: 3.0,
    transparency_rating: 2.5,
    community_rating: 2.5,
    value_rating: 2.5,
    pros: ['Tasty food products', 'Good party demonstrations', 'Easy to use mixes', 'Southern recipes appeal'],
    cons: ['Small company with limited reach', 'Premium pricing', 'Competition from larger food MLMs', 'Limited product innovation'],
    quick_facts: {
      'Founded': '1994',
      'Business Model': 'Party plan direct sales',
      'Products': 'Gourmet food mixes and seasonings'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Easy gourmet cooking from two sisters',
    faq: [
      { question: 'Is Two Sisters Gourmet still in business?', answer: 'The company appears to have limited operations or may have scaled back significantly in recent years.' },
      { question: 'How much do consultants earn?', answer: 'Commission rates typically range from 20-25% on direct sales.' }
    ]
  },
  {
    id: '746',
    slug: 'homemade-gourmet-defunct',
    name: 'Homemade Gourmet (Defunct)',
    category: 'direct_sales',
    founded_year: 1998,
    hq_location: 'West Jordan, Utah, USA',
    website: 'https://www.homemadegourmet.com',
    products_summary: 'Gourmet food mixes, baking ingredients, and meal solutions for busy families. Sold through party plan. Company closed around 2012.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Party plan (defunct)',
    overall_rating: 2.0,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.0,
    pros: ['Quality food mixes', 'Good party sampling', 'Convenient meal solutions', 'Family-friendly products'],
    cons: ['Company closed around 2012', 'No longer in operation', 'Competitive gourmet food market', 'Premium pricing'],
    quick_facts: {
      'Founded': '1998',
      'Business Model': 'Party plan (defunct ~2012)',
      'Products': 'Gourmet food mixes'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Former gourmet food mix company',
    faq: [
      { question: 'What happened to Homemade Gourmet?', answer: 'Homemade Gourmet ceased operations around 2012 due to market competition and business challenges.' },
      { question: 'Can I still find the recipes?', answer: 'Some former consultants may share recipes online, but the company and products are no longer available.' }
    ]
  },
  {
    id: '747',
    slug: 'wildly-organic-affiliate',
    name: 'Wildly Organic',
    category: 'direct_sales',
    founded_year: 2000,
    hq_location: 'Mansfield, Ohio, USA',
    website: 'https://www.wildlyorganic.com',
    products_summary: 'Organic foods, coconut products, superfoods, and natural ingredients. Primarily retail with affiliate program (not traditional MLM/party plan).',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 2.8,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Quality organic products', 'No startup cost', 'Simple affiliate model', 'Not an MLM', 'Growing organic market'],
    cons: ['Low affiliate commission (typically 10%)', 'Highly competitive organic market', 'No residual income', 'Small company visibility'],
    quick_facts: {
      'Founded': '2000',
      'Business Model': 'Affiliate program (not MLM)',
      'Products': 'Organic foods and superfoods'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Organic whole foods and ingredients',
    faq: [
      { question: 'Is Wildly Organic an MLM?', answer: 'No, Wildly Organic operates primarily as a retail company with a standard affiliate program, not multi-level marketing.' },
      { question: 'How does the affiliate program work?', answer: 'Affiliates share product links and earn a commission (around 10%) on qualifying sales, with no recruiting required.' }
    ]
  },
  {
    id: '748',
    slug: 'heritage-makers',
    name: 'Heritage Makers',
    category: 'direct_sales',
    founded_year: 2001,
    hq_location: 'Provo, Utah, USA',
    website: 'https://www.heritagemakers.com',
    products_summary: 'Photo books, scrapbooking, digital design services, and personalized keepsakes. Focus on preserving family memories through custom products.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.4,
    residual_rating: 2.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.5,
    pros: ['Quality photo products', 'Emotional appeal of preserving memories', 'Digital tools provided', 'Good for families'],
    cons: ['Declining physical photo book market', 'Competition from Shutterfly, Snapfish', 'Expensive products', 'Learning curve for design software'],
    quick_facts: {
      'Founded': '2001',
      'Business Model': 'Party plan direct sales',
      'Products': 'Photo books and digital scrapbooking'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Preserve your heritage in beautiful books',
    faq: [
      { question: 'How is Heritage Makers different from Shutterfly?', answer: 'Heritage Makers uses a consultant model with personal service and design help, while Shutterfly is direct-to-consumer online only.' },
      { question: 'What does it cost to join?', answer: 'Starter kits range from $99-$199 with sample products and business materials.' }
    ]
  },
  {
    id: '749',
    slug: 'barefoot-books',
    name: 'Barefoot Books',
    category: 'direct_sales',
    founded_year: 1992,
    hq_location: 'Cambridge, Massachusetts, USA',
    website: 'https://www.barefootbooks.com',
    products_summary: 'Children\'s books with multicultural themes, diverse stories, and beautiful illustrations. Sold through independent ambassadors and retail.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Party plan',
    overall_rating: 2.8,
    residual_rating: 2.0,
    simplicity_rating: 3.0,
    transparency_rating: 3.0,
    community_rating: 3.5,
    value_rating: 3.0,
    pros: ['Beautiful quality books', 'Diverse multicultural content', 'Mission-driven company', 'Strong community of ambassadors', 'Retail presence supports brand'],
    cons: ['Competition from Amazon', 'Premium pricing', 'Quarterly minimums required', 'Limited to children\'s books', 'Market saturation in some areas'],
    quick_facts: {
      'Founded': '1992',
      'Business Model': 'Party plan direct sales',
      'Products': 'Multicultural children\'s books'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Books that open children\'s hearts and minds',
    faq: [
      { question: 'How much do Barefoot Books ambassadors earn?', answer: 'Ambassadors earn 20-25% commission on sales, with additional bonuses for team building.' },
      { question: 'What is the quarterly minimum?', answer: 'Ambassadors must maintain $300 in sales per quarter to remain active.' }
    ]
  },
  {
    id: '750',
    slug: 'paper-coterie',
    name: 'Paper Coterie',
    category: 'direct_sales',
    founded_year: 2009,
    hq_location: 'Seattle, Washington, USA',
    website: 'https://www.papercoterie.com',
    products_summary: 'Custom stationery, invitations, birth announcements, holiday cards, and personalized paper goods. Previously had consultant program (now primarily retail).',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Retail (formerly party plan)',
    overall_rating: 2.5,
    residual_rating: 1.5,
    simplicity_rating: 2.5,
    transparency_rating: 2.5,
    community_rating: 2.5,
    value_rating: 2.5,
    pros: ['High-quality custom designs', 'Beautiful personalization', 'Premium paper stock', 'Eco-friendly options'],
    cons: ['Direct sales program discontinued or limited', 'Now primarily retail', 'Premium pricing', 'Competition from online printers', 'Seasonal business'],
    quick_facts: {
      'Founded': '2009',
      'Business Model': 'Retail (former party plan)',
      'Products': 'Custom stationery and invitations'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Custom stationery beautifully designed',
    faq: [
      { question: 'Does Paper Coterie still have independent consultants?', answer: 'The company has shifted primarily to direct-to-consumer retail sales through their website.' },
      { question: 'Can I earn money with Paper Coterie?', answer: 'Any current affiliate or consultant programs would be limited compared to traditional party plan models.' }
    ]
  },
  {
    id: '751',
    slug: 'cookn-software',
    name: 'Cook\'n Recipe Software',
    category: 'direct_sales',
    founded_year: 1996,
    hq_location: 'American Fork, Utah, USA',
    website: 'https://www.dvo.com',
    products_summary: 'Recipe management software, digital cookbooks, and meal planning tools. Software product with affiliate program (not traditional MLM).',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 2.5,
    residual_rating: 1.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.0,
    community_rating: 2.0,
    value_rating: 2.5,
    pros: ['Useful software for home cooks', 'Digital product (no shipping)', 'One-time purchase product', 'Not an MLM'],
    cons: ['Niche market appeal', 'Free apps compete', 'Dated software interface', 'Low affiliate commissions', 'Limited recurring revenue'],
    quick_facts: {
      'Founded': '1996',
      'Business Model': 'Affiliate (software)',
      'Products': 'Recipe management software'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Organize your recipes digitally',
    faq: [
      { question: 'Is Cook\'n an MLM?', answer: 'No, Cook\'n is recipe software with a standard affiliate program for promoters.' },
      { question: 'How much do affiliates earn?', answer: 'Affiliates typically earn a percentage commission on software sales generated through their links.' }
    ]
  },
  {
    id: '752',
    slug: 'rada-cutlery',
    name: 'Rada Cutlery',
    category: 'direct_sales',
    founded_year: 1948,
    hq_location: 'Waverly, Iowa, USA',
    website: 'https://www.radamfg.com',
    products_summary: 'American-made kitchen knives, utensils, and cutlery. Primarily sold through fundraising programs and direct sales, manufactured in the USA.',
    monthly_cost_min: 0,
    monthly_cost_max: 30,
    comp_plan_type: 'Direct sales/Fundraising',
    overall_rating: 2.9,
    residual_rating: 2.0,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 3.0,
    value_rating: 3.5,
    pros: ['Quality American-made products', 'Affordable pricing', 'Strong fundraising program', 'Lifetime warranty', 'Simple business model', 'No MLM pressure'],
    cons: ['Limited growth potential', 'No residual income', 'Small commission margins', 'Limited product line'],
    quick_facts: {
      'Founded': '1948',
      'Business Model': 'Direct sales and fundraising',
      'Products': 'American-made cutlery'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'American-made cutlery since 1948',
    faq: [
      { question: 'Is Rada Cutlery an MLM?', answer: 'No, Rada operates primarily as a fundraising program and direct sales, without multi-level recruiting structures.' },
      { question: 'How do people earn with Rada?', answer: 'Groups use Rada for fundraising (keeping a portion of sales), or individuals can sell directly for commission.' }
    ]
  },
  {
    id: '753',
    slug: 'regal-ware',
    name: 'Regal Ware',
    category: 'direct_sales',
    founded_year: 1945,
    hq_location: 'Kewaskum, Wisconsin, USA',
    website: 'https://www.regalware.com',
    products_summary: 'Premium stainless steel cookware, kitchen products, and home goods. Sold through in-home demonstrations and direct sales representatives.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'In-home demonstrations',
    overall_rating: 2.6,
    residual_rating: 2.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.5,
    community_rating: 2.5,
    value_rating: 2.5,
    pros: ['Quality American-made cookware', 'Lifetime warranty', 'In-home cooking demonstrations work well', 'Established brand since 1945'],
    cons: ['Very expensive products ($2,000+ sets)', 'High-pressure sales tactics historically', 'Limited market (only wealthy buyers)', 'Declining in-home sales model'],
    quick_facts: {
      'Founded': '1945',
      'Business Model': 'In-home demonstration sales',
      'Products': 'Premium stainless cookware'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Premium American cookware since 1945',
    faq: [
      { question: 'Is Regal Ware worth the price?', answer: 'Regal Ware offers quality cookware with lifetime warranty, but similar quality is available at lower prices from retail brands.' },
      { question: 'How much do sales reps earn?', answer: 'Commission varies but can be substantial on high-ticket cookware sets, though closing sales is difficult.' }
    ]
  },
  {
    id: '754',
    slug: 'saladmaster',
    name: 'Saladmaster',
    category: 'direct_sales',
    founded_year: 1946,
    hq_location: 'Arlington, Texas, USA',
    website: 'https://www.saladmaster.com',
    products_summary: 'Premium stainless steel cookware, food preparation equipment, and kitchen systems. Sold through in-home cooking demonstrations.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'In-home demonstrations',
    overall_rating: 2.5,
    residual_rating: 2.0,
    simplicity_rating: 2.0,
    transparency_rating: 2.0,
    community_rating: 2.5,
    value_rating: 2.0,
    pros: ['High-quality cookware', 'Lifetime warranty', 'Waterless cooking technology', 'Long company history'],
    cons: ['Extremely expensive ($3,000-$5,000+ sets)', 'Aggressive sales tactics reported', 'MLM structure with recruiting', 'Limited customer base due to pricing'],
    quick_facts: {
      'Founded': '1946',
      'Business Model': 'In-home demonstration MLM',
      'Products': 'Premium stainless cookware'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Premium waterless cookware',
    faq: [
      { question: 'Is Saladmaster an MLM?', answer: 'Yes, Saladmaster uses multi-level marketing with recruiting and team building in addition to direct sales.' },
      { question: 'Why is Saladmaster so expensive?', answer: 'The company uses in-home demonstrations and MLM structure, adding significant costs beyond the product manufacturing.' }
    ]
  },
  {
    id: '755',
    slug: 'kirby-vacuums',
    name: 'Kirby Vacuums',
    category: 'direct_sales',
    founded_year: 1914,
    hq_location: 'Cleveland, Ohio, USA',
    website: 'https://www.kirby.com',
    products_summary: 'High-end vacuum cleaners and home cleaning systems sold through in-home demonstrations. Known for multi-surface cleaning capabilities and durability.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Door-to-door/In-home',
    overall_rating: 2.3,
    residual_rating: 1.5,
    simplicity_rating: 2.0,
    transparency_rating: 2.0,
    community_rating: 2.0,
    value_rating: 2.0,
    pros: ['Durable quality vacuums', 'Multi-surface cleaning system', 'Lifetime rebuild program', 'Long company history since 1914'],
    cons: ['Extremely expensive ($2,000-$3,000)', 'Aggressive door-to-door sales', 'High-pressure tactics common', 'Better value vacuums available retail', 'Notorious for deceptive practices'],
    quick_facts: {
      'Founded': '1914',
      'Business Model': 'Door-to-door direct sales',
      'Products': 'Premium vacuum cleaners'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Premium vacuum systems since 1914',
    faq: [
      { question: 'Are Kirby vacuums worth the price?', answer: 'While durable, Kirby vacuums are significantly overpriced compared to retail alternatives. The high cost covers commission structure, not superior value.' },
      { question: 'Is selling Kirby a good job?', answer: 'Kirby sales jobs are commission-only door-to-door positions with high turnover. Most reps struggle to earn consistent income.' }
    ]
  },
  {
    id: '756',
    slug: 'rainbow-vacuums',
    name: 'Rainbow Vacuum',
    category: 'direct_sales',
    founded_year: 1936,
    hq_location: 'Troy, Michigan, USA',
    website: 'https://www.rainbowsystem.com',
    products_summary: 'Water-filtration vacuum cleaners and home cleaning systems sold through in-home demonstrations. Uses water to trap dirt instead of bags or filters.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'In-home demonstrations',
    overall_rating: 2.4,
    residual_rating: 1.5,
    simplicity_rating: 2.0,
    transparency_rating: 2.0,
    community_rating: 2.0,
    value_rating: 2.0,
    pros: ['Unique water filtration system', 'Multi-purpose cleaning', 'Durable construction', 'Air purification feature'],
    cons: ['Very expensive ($2,000-$3,500)', 'High-pressure sales tactics', 'Heavy and bulky', 'Maintenance required', 'Overpriced for features'],
    quick_facts: {
      'Founded': '1936',
      'Business Model': 'In-home demonstration sales',
      'Products': 'Water-filtration vacuum systems'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Water-based vacuum cleaning system',
    faq: [
      { question: 'Is Rainbow vacuum an MLM?', answer: 'Rainbow uses direct sales with in-home demonstrations and has MLM elements with recruiting and team building.' },
      { question: 'Do Rainbow vacuums really work?', answer: 'The water filtration does work, but performance doesn\'t justify the premium price compared to quality retail vacuums.' }
    ]
  },
  {
    id: '757',
    slug: 'filter-queen',
    name: 'Filter Queen',
    category: 'direct_sales',
    founded_year: 1928,
    hq_location: 'North Canton, Ohio, USA',
    website: 'https://www.filterqueen.com',
    products_summary: 'Vacuum cleaners with HEPA filtration and air purification systems sold through in-home demonstrations and independent dealers.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'In-home demonstrations',
    overall_rating: 2.4,
    residual_rating: 1.5,
    simplicity_rating: 2.0,
    transparency_rating: 2.0,
    community_rating: 2.0,
    value_rating: 2.0,
    pros: ['HEPA filtration system', 'Dual function vacuum and air purifier', 'Durable metal construction', 'Long company history'],
    cons: ['Expensive ($1,500-$2,500)', 'In-home sales pressure', 'Heavy unit', 'Overpriced vs retail alternatives', 'Limited availability'],
    quick_facts: {
      'Founded': '1928',
      'Business Model': 'In-home demonstration sales',
      'Products': 'HEPA vacuum and air purifiers'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'HEPA filtration since 1928',
    faq: [
      { question: 'Is Filter Queen worth the money?', answer: 'While the product has quality filtration, similar HEPA performance is available at much lower prices through retail brands.' },
      { question: 'How do Filter Queen dealers make money?', answer: 'Dealers earn commission on direct sales, typically through in-home demonstrations and referrals.' }
    ]
  },
  {
    id: '758',
    slug: 'thermomix',
    name: 'Thermomix (Vorwerk)',
    category: 'direct_sales',
    founded_year: 1971,
    hq_location: 'Wuppertal, Germany',
    website: 'https://www.thermomix.com',
    products_summary: 'All-in-one kitchen appliances that blend, cook, steam, and process food. High-tech cooking device sold through consultants and cooking demonstrations.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'In-home demonstrations',
    overall_rating: 2.8,
    residual_rating: 2.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['High-quality German engineering', 'Multi-function device', 'Strong international brand', 'Passionate user community', 'Good demonstrations'],
    cons: ['Very expensive ($1,500+)', 'Only available through consultants', 'High-pressure sales tactics', 'Limited customer base', 'Repairs expensive'],
    quick_facts: {
      'Founded': '1971',
      'Business Model': 'Direct sales demonstrations',
      'Products': 'All-in-one cooking appliance'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'The ultimate all-in-one kitchen machine',
    faq: [
      { question: 'Is Thermomix worth $1,500?', answer: 'Thermomix is a quality product but very expensive. Similar multi-cookers are available at much lower prices, though build quality may differ.' },
      { question: 'Can I buy Thermomix in stores?', answer: 'No, Thermomix is only sold through independent consultants via in-home cooking demonstrations.' }
    ]
  },
  {
    id: '759',
    slug: 'vorwerk-direct-sales',
    name: 'Vorwerk Direct Sales',
    category: 'direct_sales',
    founded_year: 1883,
    hq_location: 'Wuppertal, Germany',
    website: 'https://www.vorwerk.com',
    products_summary: 'Thermomix cooking systems, Kobold vacuum cleaners, and home appliances. German company selling premium products through direct sales consultants.',
    monthly_cost_min: 0,
    monthly_cost_max: 50,
    comp_plan_type: 'Direct sales demonstrations',
    overall_rating: 2.7,
    residual_rating: 2.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.5,
    community_rating: 3.0,
    value_rating: 2.5,
    pros: ['Premium German quality', 'Multiple product categories', 'Strong European presence', 'Established company since 1883', 'Innovative products'],
    cons: ['Very expensive products', 'Limited US presence', 'Only through direct sales', 'High-pressure demonstrations', 'Better value alternatives exist'],
    quick_facts: {
      'Founded': '1883',
      'Business Model': 'Direct sales demonstrations',
      'Products': 'Premium home appliances'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'German premium home appliances',
    faq: [
      { question: 'What products does Vorwerk sell?', answer: 'Vorwerk\'s direct sales division primarily sells Thermomix cooking systems and Kobold vacuum cleaners in various markets.' },
      { question: 'Is Vorwerk available in the US?', answer: 'Thermomix is available in the US through consultants, though Vorwerk has stronger presence in Europe.' }
    ]
  },
  {
    id: '760',
    slug: 'le-creuset-affiliate',
    name: 'Le Creuset Affiliate',
    category: 'direct_sales',
    founded_year: 1925,
    hq_location: 'Fresnoy-le-Grand, France',
    website: 'https://www.lecreuset.com',
    products_summary: 'Premium French cookware, cast iron, and kitchen products. Retail brand with affiliate program (not MLM/party plan).',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Prestigious brand', 'Quality products', 'No startup cost', 'Simple affiliate model', 'Not an MLM', 'Strong retail presence'],
    cons: ['Low affiliate commission (3-5%)', 'High competition', 'Expensive products limit conversions', 'No residual income'],
    quick_facts: {
      'Founded': '1925',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Premium French cookware'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Iconic French cookware affiliate program',
    faq: [
      { question: 'How does Le Creuset affiliate program work?', answer: 'Affiliates share product links and earn a small commission (typically 3-5%) on qualifying purchases.' },
      { question: 'Is this an MLM?', answer: 'No, this is a traditional affiliate program with no recruiting or multi-level structure.' }
    ]
  },
  {
    id: '761',
    slug: 'lodge-cast-iron-affiliate',
    name: 'Lodge Cast Iron Affiliate',
    category: 'direct_sales',
    founded_year: 1896,
    hq_location: 'South Pittsburg, Tennessee, USA',
    website: 'https://www.lodgecastiron.com',
    products_summary: 'American-made cast iron cookware, skillets, Dutch ovens, and accessories. Retail brand with affiliate program available.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.5,
    pros: ['American-made products', 'Affordable cast iron', 'Strong brand recognition', 'No startup cost', 'Not an MLM', 'Popular products'],
    cons: ['Low commission rates', 'Wide retail availability reduces need', 'High competition', 'No residual income'],
    quick_facts: {
      'Founded': '1896',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'American cast iron cookware'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'American cast iron since 1896',
    faq: [
      { question: 'Can I earn money promoting Lodge?', answer: 'Yes, through their affiliate program you earn a commission on sales generated through your links.' },
      { question: 'Is Lodge an MLM?', answer: 'No, Lodge is a retail company with a standard affiliate program, no recruiting or multi-level marketing.' }
    ]
  },
  {
    id: '762',
    slug: 'sur-la-table-affiliate',
    name: 'Sur La Table Affiliate',
    category: 'direct_sales',
    founded_year: 1972,
    hq_location: 'Seattle, Washington, USA',
    website: 'https://www.surlatable.com',
    products_summary: 'Kitchen and cooking supplies, cookware, bakeware, and culinary tools. Retail chain with affiliate program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Well-known kitchen retailer', 'Wide product selection', 'No startup cost', 'Simple affiliate model', 'Not an MLM'],
    cons: ['Low commission (typically 2-4%)', 'Heavy competition', 'Retail stores compete with online', 'No residual income'],
    quick_facts: {
      'Founded': '1972',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Kitchen and cooking supplies'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Kitchen supplies affiliate program',
    faq: [
      { question: 'How much can I earn as a Sur La Table affiliate?', answer: 'Affiliates earn a small percentage commission (2-4%) on sales generated through their referral links.' },
      { question: 'Is this an MLM?', answer: 'No, this is a standard retail affiliate program with no recruiting or multi-level structure.' }
    ]
  },
  {
    id: '763',
    slug: 'williams-sonoma-affiliate',
    name: 'Williams Sonoma Affiliate',
    category: 'direct_sales',
    founded_year: 1956,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.williams-sonoma.com',
    products_summary: 'Premium cookware, kitchen tools, home furnishings, and gourmet foods. Upscale retail brand with affiliate program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Premium brand recognition', 'Wide quality product range', 'No startup cost', 'Not an MLM', 'Strong retail presence'],
    cons: ['Low commission rates (3-5%)', 'Expensive products', 'High market competition', 'No residual income'],
    quick_facts: {
      'Founded': '1956',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Premium cookware and home goods'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Premium kitchen and home affiliate',
    faq: [
      { question: 'How does the affiliate program work?', answer: 'Share Williams Sonoma product links and earn a commission (typically 3-5%) on qualifying purchases.' },
      { question: 'Is Williams Sonoma an MLM?', answer: 'No, it\'s a traditional retail company with a standard affiliate marketing program.' }
    ]
  },
  {
    id: '764',
    slug: 'crate-barrel-affiliate',
    name: 'Crate & Barrel Affiliate',
    category: 'direct_sales',
    founded_year: 1962,
    hq_location: 'Northbrook, Illinois, USA',
    website: 'https://www.crateandbarrel.com',
    products_summary: 'Modern furniture, home decor, kitchenware, and housewares. Contemporary home goods retailer with affiliate program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Modern aesthetic appeal', 'Quality product selection', 'Strong brand', 'No startup cost', 'Not an MLM'],
    cons: ['Low commission (2-4%)', 'Competitive market', 'No residual income', 'Retail availability reduces conversions'],
    quick_facts: {
      'Founded': '1962',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Modern home furnishings'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Modern home goods affiliate',
    faq: [
      { question: 'Can I make money with Crate & Barrel affiliate?', answer: 'Yes, through standard affiliate commissions on sales, though rates are modest (2-4%).' },
      { question: 'Is this direct sales?', answer: 'No, this is a retail affiliate program, not direct sales, MLM, or party plan.' }
    ]
  },
  {
    id: '765',
    slug: 'pottery-barn-affiliate',
    name: 'Pottery Barn Affiliate',
    category: 'direct_sales',
    founded_year: 1949,
    hq_location: 'San Francisco, California, USA',
    website: 'https://www.potterybarn.com',
    products_summary: 'Home furnishings, furniture, decor, and accessories. Classic American home goods retailer with affiliate program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Well-established brand', 'Quality home furnishings', 'No startup cost', 'Simple affiliate model', 'Not an MLM'],
    cons: ['Low commission rates', 'Expensive products', 'Competitive affiliate space', 'No residual income'],
    quick_facts: {
      'Founded': '1949',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Home furnishings and decor'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Classic home furnishings affiliate',
    faq: [
      { question: 'How much do Pottery Barn affiliates earn?', answer: 'Affiliates earn a percentage commission on sales, typically in the 2-4% range.' },
      { question: 'Is Pottery Barn an MLM?', answer: 'No, Pottery Barn is a traditional retailer with a standard affiliate program.' }
    ]
  },
  {
    id: '766',
    slug: 'bed-bath-beyond-affiliate',
    name: 'Bed Bath & Beyond Affiliate',
    category: 'direct_sales',
    founded_year: 1971,
    hq_location: 'Union, New Jersey, USA',
    website: 'https://www.bedbathandbeyond.com',
    products_summary: 'Home goods, bedding, bath items, and housewares. Major retailer (filed bankruptcy 2023, restructured). Affiliate program status uncertain.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate (uncertain)',
    overall_rating: 2.0,
    residual_rating: 1.0,
    simplicity_rating: 2.5,
    transparency_rating: 2.0,
    community_rating: 2.0,
    value_rating: 2.5,
    pros: ['Previously well-known brand', 'Wide product selection historically', 'No startup cost if program exists'],
    cons: ['Company filed bankruptcy in 2023', 'Store closures and restructuring', 'Uncertain business status', 'Affiliate program may be discontinued', 'Brand reputation damaged'],
    quick_facts: {
      'Founded': '1971',
      'Business Model': 'Retail (bankrupt 2023)',
      'Products': 'Home goods and housewares'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Home goods retailer (restructuring)',
    faq: [
      { question: 'Is Bed Bath & Beyond still in business?', answer: 'The company filed for bankruptcy in 2023. Some stores closed, and the brand was acquired. Current status and affiliate programs are uncertain.' },
      { question: 'Can I still be an affiliate?', answer: 'Given the bankruptcy and restructuring, the affiliate program status is unclear. Check their current website for updates.' }
    ]
  },
  {
    id: '767',
    slug: 'wayfair-affiliate',
    name: 'Wayfair Affiliate',
    category: 'direct_sales',
    founded_year: 2002,
    hq_location: 'Boston, Massachusetts, USA',
    website: 'https://www.wayfair.com',
    products_summary: 'Online furniture and home goods marketplace. Wide selection of furniture, decor, and housewares with affiliate program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.5,
    pros: ['Huge product selection', 'Competitive pricing', 'No startup cost', 'Growing online brand', 'Not an MLM', 'Good conversion rates'],
    cons: ['Low commission (1-3%)', 'Highly competitive', 'No residual income', 'Short cookie duration'],
    quick_facts: {
      'Founded': '2002',
      'Business Model': 'Affiliate program (e-commerce)',
      'Products': 'Online furniture and home goods'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Home goods e-commerce affiliate',
    faq: [
      { question: 'What commission does Wayfair pay affiliates?', answer: 'Wayfair typically pays 1-3% commission on qualifying purchases, varying by product category.' },
      { question: 'Is Wayfair affiliate worth it?', answer: 'Despite low commission rates, the large product selection and good conversion rates can make it viable for home decor content creators.' }
    ]
  },
  {
    id: '768',
    slug: 'overstock-affiliate',
    name: 'Overstock Affiliate',
    category: 'direct_sales',
    founded_year: 1999,
    hq_location: 'Midvale, Utah, USA',
    website: 'https://www.overstock.com',
    products_summary: 'Discount home goods, furniture, and housewares. Online retailer offering deals on furniture and home decor with affiliate program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 2.8,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Discount pricing attracts buyers', 'Wide product range', 'No startup cost', 'Not an MLM', 'Good for bargain shoppers'],
    cons: ['Low commission (1-2%)', 'Brand less prestigious than competitors', 'Competitive affiliate market', 'No residual income'],
    quick_facts: {
      'Founded': '1999',
      'Business Model': 'Affiliate program (e-commerce)',
      'Products': 'Discount home goods and furniture'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Discount home goods online',
    faq: [
      { question: 'How much do Overstock affiliates earn?', answer: 'Commission rates are typically 1-2% on qualifying sales, which is low but can add up with volume.' },
      { question: 'Is Overstock still in business?', answer: 'Yes, Overstock continues to operate as an online discount home goods retailer (now Beyond, Inc.).' }
    ]
  },
  {
    id: '769',
    slug: 'home-depot-affiliate',
    name: 'Home Depot Affiliate',
    category: 'direct_sales',
    founded_year: 1978,
    hq_location: 'Atlanta, Georgia, USA',
    website: 'https://www.homedepot.com',
    products_summary: 'Home improvement, tools, building materials, and hardware. Major retail chain with affiliate program for online purchases.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.5,
    pros: ['Trusted brand name', 'Huge product selection', 'Competitive pricing', 'No startup cost', 'Not an MLM', 'DIY content opportunities'],
    cons: ['Very low commission (1-3%)', 'Retail stores reduce online sales', 'Highly competitive', 'No residual income'],
    quick_facts: {
      'Founded': '1978',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Home improvement and tools'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Home improvement retail affiliate',
    faq: [
      { question: 'Does Home Depot have an affiliate program?', answer: 'Yes, Home Depot partners with affiliate networks to offer commission on online purchases driven by affiliates.' },
      { question: 'What is the commission rate?', answer: 'Commission rates are typically 1-3%, varying by product category and affiliate network.' }
    ]
  },
  {
    id: '770',
    slug: 'lowes-affiliate',
    name: 'Lowe\'s Affiliate',
    category: 'direct_sales',
    founded_year: 1946,
    hq_location: 'Mooresville, North Carolina, USA',
    website: 'https://www.lowes.com',
    products_summary: 'Home improvement, appliances, tools, and building supplies. Major retail chain with affiliate program for DIY and home improvement content.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 3.0,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.5,
    pros: ['Major brand recognition', 'Wide product inventory', 'Competitive prices', 'No startup cost', 'Not an MLM', 'Good for DIY content'],
    cons: ['Low commission (1-3%)', 'Physical stores compete', 'Very competitive', 'No residual income'],
    quick_facts: {
      'Founded': '1946',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Home improvement and appliances'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Home improvement affiliate program',
    faq: [
      { question: 'How does Lowe\'s affiliate program work?', answer: 'Affiliates promote Lowe\'s products through links and earn a commission (1-3%) on qualifying online purchases.' },
      { question: 'Is Lowe\'s an MLM?', answer: 'No, Lowe\'s is a traditional retailer with a standard affiliate marketing program, not multi-level marketing.' }
    ]
  },
  {
    id: '771',
    slug: 'ace-hardware-affiliate',
    name: 'Ace Hardware Affiliate',
    category: 'direct_sales',
    founded_year: 1924,
    hq_location: 'Oak Brook, Illinois, USA',
    website: 'https://www.acehardware.com',
    products_summary: 'Hardware, tools, paint, and home repair supplies. Cooperative hardware chain with affiliate program for online sales.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 2.8,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Trusted local brand', 'Helpful place positioning', 'Good for DIY content', 'No startup cost', 'Not an MLM'],
    cons: ['Lower traffic than Home Depot/Lowe\'s', 'Small commission (1-3%)', 'Limited online selection', 'No residual income'],
    quick_facts: {
      'Founded': '1924',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Hardware and home repair'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'The helpful hardware place affiliate',
    faq: [
      { question: 'Does Ace Hardware have affiliate marketing?', answer: 'Yes, Ace Hardware offers an affiliate program for promoting their online store products.' },
      { question: 'What commission does Ace pay?', answer: 'Affiliate commission rates typically range from 1-3% on qualifying purchases.' }
    ]
  },
  {
    id: '772',
    slug: 'true-value-affiliate',
    name: 'True Value Affiliate',
    category: 'direct_sales',
    founded_year: 1948,
    hq_location: 'Chicago, Illinois, USA',
    website: 'https://www.truevalue.com',
    products_summary: 'Hardware, tools, paint, and home improvement products. Cooperative hardware retailer with online affiliate program.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 2.7,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.0,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Local hardware cooperative model', 'No startup cost', 'Not an MLM', 'Community-focused brand'],
    cons: ['Limited online presence', 'Low commission', 'Less traffic than major competitors', 'No residual income', 'Smaller brand reach'],
    quick_facts: {
      'Founded': '1948',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Hardware and home improvement'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Local hardware cooperative affiliate',
    faq: [
      { question: 'Is True Value still in business?', answer: 'Yes, True Value operates as a hardware cooperative, though it has faced financial challenges and store closures in recent years.' },
      { question: 'Can I earn through True Value affiliate?', answer: 'Affiliate programs may be available through networks, though the program is less prominent than larger competitors.' }
    ]
  },
  {
    id: '773',
    slug: 'harbor-freight-affiliate',
    name: 'Harbor Freight Affiliate',
    category: 'direct_sales',
    founded_year: 1977,
    hq_location: 'Calabasas, California, USA',
    website: 'https://www.harborfreight.com',
    products_summary: 'Discount tools and equipment. Budget-friendly tool retailer offering affordable alternatives to premium tool brands.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 2.8,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.0,
    community_rating: 2.5,
    value_rating: 3.5,
    pros: ['Low prices attract buyers', 'Good for budget tool content', 'No startup cost', 'Not an MLM', 'Growing brand'],
    cons: ['Low commission rates', 'Budget brand reputation', 'Quality concerns on some items', 'No residual income'],
    quick_facts: {
      'Founded': '1977',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Discount tools and equipment'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Affordable tools for everyone',
    faq: [
      { question: 'Does Harbor Freight have affiliate marketing?', answer: 'Harbor Freight participates in affiliate networks, allowing content creators to earn commission on referred sales.' },
      { question: 'Are Harbor Freight tools good quality?', answer: 'Quality varies by product line - some tools are solid budget options, while others are best for light use only.' }
    ]
  },
  {
    id: '774',
    slug: 'northern-tool-affiliate',
    name: 'Northern Tool Affiliate',
    category: 'direct_sales',
    founded_year: 1981,
    hq_location: 'Burnsville, Minnesota, USA',
    website: 'https://www.northerntool.com',
    products_summary: 'Professional and contractor-grade tools, equipment, and machinery. Retail and online seller of tools, generators, and equipment.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 2.8,
    residual_rating: 1.5,
    simplicity_rating: 3.5,
    transparency_rating: 3.0,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Professional-grade tools', 'Good for contractor content', 'No startup cost', 'Not an MLM', 'Specialty equipment'],
    cons: ['Niche audience', 'Low commission', 'Less brand recognition than major competitors', 'No residual income'],
    quick_facts: {
      'Founded': '1981',
      'Business Model': 'Affiliate program (retail)',
      'Products': 'Professional tools and equipment'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Professional tools and equipment',
    faq: [
      { question: 'Does Northern Tool have an affiliate program?', answer: 'Yes, Northern Tool offers affiliate partnerships through various affiliate networks.' },
      { question: 'What kind of tools does Northern Tool sell?', answer: 'Northern Tool specializes in professional-grade tools, generators, air compressors, and contractor equipment.' }
    ]
  },
  {
    id: '775',
    slug: 'grainger-affiliate',
    name: 'Grainger Affiliate',
    category: 'direct_sales',
    founded_year: 1927,
    hq_location: 'Lake Forest, Illinois, USA',
    website: 'https://www.grainger.com',
    products_summary: 'Industrial and commercial supplies, tools, safety equipment, and MRO (maintenance, repair, operations) products for businesses.',
    monthly_cost_min: 0,
    monthly_cost_max: 0,
    comp_plan_type: 'Affiliate',
    overall_rating: 2.8,
    residual_rating: 1.5,
    simplicity_rating: 3.0,
    transparency_rating: 3.5,
    community_rating: 2.5,
    value_rating: 3.0,
    pros: ['Massive product catalog', 'B2B focus with higher order values', 'Trusted brand since 1927', 'No startup cost', 'Not an MLM'],
    cons: ['Very niche B2B audience', 'Low commission rates', 'Requires industry knowledge', 'No residual income', 'Business-focused not consumer'],
    quick_facts: {
      'Founded': '1927',
      'Business Model': 'Affiliate program (B2B retail)',
      'Products': 'Industrial and MRO supplies'
    },
    last_updated: new Date().toISOString(),
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    tagline: 'Industrial supplies for businesses',
    faq: [
      { question: 'Is Grainger affiliate program available?', answer: 'Grainger may offer affiliate or referral partnerships, primarily targeting B2B industrial buyers rather than consumers.' },
      { question: 'Who is Grainger for?', answer: 'Grainger primarily serves businesses, facilities managers, and industrial operations rather than residential consumers.' }
    ]
  }
];
