export interface PitfallData {
  companySlug: string;
  companyName: string;
  lastUpdated: string;
  overallRisk: 'high' | 'medium' | 'low';
  riskReason: string;
  pitfalls: Array<{
    category: string;
    severity: 'high' | 'medium' | 'low';
    title: string;
    details: string;
    sourceNote: string;
  }>;
  bottomLine: string;
  policyUrl: string;
}

export const pitfallsData: PitfallData[] = [
  {
    companySlug: 'amway',
    companyName: 'Amway',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Strict non-compete, mandatory training costs, and complex volume requirements create significant financial risk.',
    pitfalls: [
      {
        category: 'Non-Compete',
        severity: 'high',
        title: '6-month non-compete after leaving',
        details: 'If you leave Amway, you cannot solicit your former downline or customers for competing business opportunities for 6 months. This means the relationships you built belong to Amway, not you.',
        sourceNote: 'Amway Rules of Conduct, Section 7',
      },
      {
        category: 'Termination',
        severity: 'high',
        title: 'Company can terminate for policy violations and keep your downline',
        details: 'Amway can terminate your IBO agreement for violating any policy, and your entire downline organization stays with the company. You lose all future commissions from the team you built.',
        sourceNote: 'IBO Agreement, Termination Clause',
      },
      {
        category: 'Required Purchases',
        severity: 'high',
        title: 'Must maintain 100 PV monthly or earn $0',
        details: 'You must generate 100 PV (roughly $300-400 in product purchases) every month to qualify for ANY commissions. Miss one month and you earn nothing, regardless of your team size.',
        sourceNote: 'Amway Compensation Plan',
      },
      {
        category: 'Training Costs',
        severity: 'high',
        title: 'Business Support Materials (BSM) costs add up fast',
        details: 'While technically "optional," the training seminars, conferences, books, and CDs pushed by upline can cost $2,000-$7,000+ annually. Many ex-IBOs report feeling pressured to buy these materials.',
        sourceNote: 'FTC Amway Investigation Documents',
      },
      {
        category: 'Arbitration',
        severity: 'medium',
        title: 'Mandatory arbitration - you waive right to sue',
        details: 'All disputes must go through binding arbitration, not courts. This limits your legal options if something goes wrong and typically favors the company.',
        sourceNote: 'IBO Agreement, Dispute Resolution',
      },
      {
        category: 'Social Media',
        severity: 'medium',
        title: 'Strict rules on what you can post online',
        details: 'Amway has detailed policies controlling how you can market on social media. Income claims, product claims, and even certain phrases are restricted. Violations can lead to termination.',
        sourceNote: 'Amway Social Media Policy',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Cannot sell on Amazon, eBay, or other marketplaces',
        details: 'Selling Amway products on third-party platforms is prohibited. You can only sell through approved channels, limiting your sales options.',
        sourceNote: 'Amway Rules of Conduct',
      },
      {
        category: 'Buyback',
        severity: 'low',
        title: '90% buyback with conditions',
        details: 'Amway offers a 90% buyback on products purchased within 12 months, but only for marketable products and with administrative deductions. The process can be slow.',
        sourceNote: 'Amway Return Policy',
      },
    ],
    bottomLine: 'Amway\'s policies heavily favor the company over distributors. The combination of mandatory monthly purchases, expensive "optional" training, and strict non-compete clauses means you\'re building on rented land. If you leave or get terminated, you walk away with nothing from the team you built.',
    policyUrl: 'https://www.amway.com/en_US/business-opportunity',
  },
  {
    companySlug: 'herbalife',
    companyName: 'Herbalife',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'FTC settlement history, complex rank requirements, and high upfront costs create substantial risks.',
    pitfalls: [
      {
        category: 'Regulatory',
        severity: 'high',
        title: '$200M FTC settlement for deceptive practices',
        details: 'In 2016, Herbalife paid $200 million to settle FTC charges that it deceived participants about potential income. The company was required to restructure its business model. This regulatory history indicates systemic issues.',
        sourceNote: 'FTC Settlement 2016',
      },
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '$4,000 minimum to reach Supervisor rank',
        details: 'To unlock the 50% margin and royalty overrides, you must become a Supervisor - which requires $4,000 in cumulative product purchases. Many distributors buy products they can\'t sell to hit this threshold.',
        sourceNote: 'Herbalife Sales & Marketing Plan',
      },
      {
        category: 'Termination',
        severity: 'high',
        title: 'Company retains your downline if terminated',
        details: 'If Herbalife terminates your distributorship for any policy violation, your entire organization remains with the company. Years of team building can vanish overnight.',
        sourceNote: 'Herbalife Distributor Agreement',
      },
      {
        category: 'Non-Compete',
        severity: 'high',
        title: 'Cannot recruit downline to competing MLM',
        details: 'Non-solicitation clauses prohibit you from recruiting your former team members to other opportunities after leaving, even if they want to join you.',
        sourceNote: 'Herbalife Policies & Procedures',
      },
      {
        category: 'Nutrition Club',
        severity: 'medium',
        title: 'Nutrition club costs not disclosed upfront',
        details: 'Many Herbalife distributors are pushed to open "Nutrition Clubs" - physical locations that require rent, permits, inventory, and ongoing operational costs that can total thousands per month.',
        sourceNote: 'Herbalife Nutrition Club Guidelines',
      },
      {
        category: 'Arbitration',
        severity: 'medium',
        title: 'Mandatory binding arbitration',
        details: 'All disputes must be resolved through binding arbitration, waiving your right to a jury trial or class action lawsuit.',
        sourceNote: 'Herbalife Distributor Agreement',
      },
      {
        category: 'Autoship',
        severity: 'medium',
        title: '$94.10/month autoship to stay active',
        details: 'To remain active and qualify for commissions, you must maintain a monthly autoship order of at least $94.10. This adds up to over $1,100 annually before earning anything.',
        sourceNote: 'Herbalife Compensation Plan',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Restricted from selling on Amazon/eBay',
        details: 'Selling Herbalife products on third-party marketplaces is prohibited, limiting your ability to reach customers.',
        sourceNote: 'Herbalife Rules of Conduct',
      },
    ],
    bottomLine: 'Herbalife\'s $200M FTC settlement wasn\'t an accident - the business model has structural issues that make most participants unlikely to profit. The high threshold to reach Supervisor ($4,000 in purchases), combined with monthly autoship requirements and nutrition club costs, means you\'re spending heavily before seeing meaningful returns.',
    policyUrl: 'https://www.herbalife.com/en-us/business-opportunity',
  },
  {
    companySlug: 'doterra',
    companyName: 'doTERRA',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Strict health claims restrictions, mandatory LRP, and new comp plan changes increase earning difficulty.',
    pitfalls: [
      {
        category: 'Health Claims',
        severity: 'high',
        title: 'FDA warning letters for health claims',
        details: 'doTERRA has received multiple FDA warning letters for distributors making unauthorized health claims about essential oils. If you make similar claims, you could face personal legal liability and termination.',
        sourceNote: 'FDA Warning Letters 2014, 2017',
      },
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '100 LRP monthly to qualify for all bonuses',
        details: 'You must maintain 100 Loyalty Rewards Points ($100-150) monthly to qualify for unilevel commissions. Miss a month and you lose bonus eligibility.',
        sourceNote: 'doTERRA Compensation Plan',
      },
      {
        category: 'Comp Plan Changes',
        severity: 'high',
        title: 'June 2025 "Elevated" plan requires ongoing recruitment',
        details: 'The new Elevated compensation plan requires "Team Growth Volume" from recent enrollees to unlock deeper commission levels. This increases recruitment pressure even if you just want to sell products.',
        sourceNote: 'doTERRA Elevated Plan Announcement',
      },
      {
        category: 'Termination',
        severity: 'high',
        title: 'Account can be suspended or terminated for policy violations',
        details: 'doTERRA actively enforces policies. Making health claims, cross-line recruiting, or selling on unauthorized platforms can result in immediate suspension and loss of your organization.',
        sourceNote: 'doTERRA Policies & Procedures',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation of downline after leaving',
        details: 'You cannot solicit your former team members to join another opportunity for a period after leaving doTERRA.',
        sourceNote: 'Wellness Advocate Agreement',
      },
      {
        category: 'Third-Party Sales',
        severity: 'high',
        title: 'Selling on Amazon/eBay is prohibited and enforced',
        details: 'doTERRA actively monitors and takes action against unauthorized marketplace sales. Violations can result in termination.',
        sourceNote: 'doTERRA Marketplace Policy',
      },
      {
        category: 'Income Reality',
        severity: 'medium',
        title: 'Typical Wellness Advocate earns $0-100/month',
        details: 'According to income disclosures, the vast majority of Wellness Advocates earn minimal commissions, with many earning nothing after factoring in required LRP purchases.',
        sourceNote: 'doTERRA Income Disclosure Statement',
      },
      {
        category: 'Arbitration',
        severity: 'medium',
        title: 'Disputes resolved through arbitration',
        details: 'The Wellness Advocate Agreement includes mandatory arbitration provisions, limiting legal recourse.',
        sourceNote: 'Wellness Advocate Agreement',
      },
    ],
    bottomLine: 'doTERRA\'s strict enforcement of health claims policies puts distributors at risk - many have been terminated for statements that seemed harmless. The 2025 comp plan changes increase recruitment requirements, making it harder to earn from product sales alone. The monthly LRP requirement means you\'re a customer first, seller second.',
    policyUrl: 'https://www.doterra.com/US/en/join',
  },
  {
    companySlug: 'young-living',
    companyName: 'Young Living',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Aggressive enforcement, complex rank maintenance, and FDA compliance issues create multiple risk vectors.',
    pitfalls: [
      {
        category: 'Health Claims',
        severity: 'high',
        title: 'FDA warning letters for therapeutic claims',
        details: 'Young Living has received FDA warning letters for distributors promoting essential oils as treatments for diseases. Making such claims can result in your termination and potential personal legal consequences.',
        sourceNote: 'FDA Warning Letters',
      },
      {
        category: 'Non-Compete',
        severity: 'high',
        title: '6-month waiting period to join doTERRA specifically',
        details: 'Young Living\'s policies specifically target their main competitor. If you leave for doTERRA, you face additional restrictions and cannot bring your organization.',
        sourceNote: 'Young Living Policies & Procedures',
      },
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '100 PV monthly minimum to stay qualified',
        details: 'You must maintain 100 PV (roughly $100) in monthly purchases to remain qualified for any commissions. This is true even if you have a large organization.',
        sourceNote: 'Young Living Compensation Plan',
      },
      {
        category: 'Rank Maintenance',
        severity: 'high',
        title: 'Lose rank if you miss volume requirements',
        details: 'Your rank isn\'t permanent - if you fail to meet the Organizational Group Volume (OGV) requirements for your rank, you will be demoted and lose associated bonuses.',
        sourceNote: 'Young Living Rank Advancement',
      },
      {
        category: 'Household Policy',
        severity: 'medium',
        title: 'Only one account per household',
        details: 'Young Living restricts each household to one distributor account. If your spouse already has an account, you cannot create your own, limiting household income opportunities.',
        sourceNote: 'Young Living Enrollment Policies',
      },
      {
        category: 'Termination',
        severity: 'high',
        title: 'Downline stays with company upon termination',
        details: 'If terminated for policy violations, your entire organization remains with Young Living. There is no option to transfer or keep the business you built.',
        sourceNote: 'Young Living Distributor Agreement',
      },
      {
        category: 'Income Reality',
        severity: 'medium',
        title: '94% of business builders earn median of $4/year',
        details: 'Income disclosure shows the vast majority of participants who try to build a business earn almost nothing, with median annual earnings of just $4.',
        sourceNote: 'Young Living Income Disclosure Statement',
      },
      {
        category: 'Arbitration',
        severity: 'medium',
        title: 'Mandatory binding arbitration',
        details: 'All disputes are subject to binding arbitration, waiving your right to jury trial or class action participation.',
        sourceNote: 'Young Living Distributor Agreement',
      },
    ],
    bottomLine: 'Young Living\'s policies protect the company, not you. The specific targeting of doTERRA in non-compete provisions shows how seriously they take distributor retention - but that energy isn\'t matched by distributor earnings. With 94% of business builders earning $4/year median, the math doesn\'t work for most participants.',
    policyUrl: 'https://www.youngliving.com/en_US/opportunity',
  },
  {
    companySlug: 'mary-kay',
    companyName: 'Mary Kay',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Inventory purchasing pressure, car co-pay penalties, and chargeback policies create substantial financial exposure.',
    pitfalls: [
      {
        category: 'Inventory',
        severity: 'high',
        title: 'Pressure to purchase inventory upfront',
        details: 'While Mary Kay claims inventory purchases are optional, the culture and upline pressure to "invest in your business" leads many consultants to buy thousands in inventory they struggle to sell.',
        sourceNote: 'Mary Kay Consultant Agreement, Industry Reports',
      },
      {
        category: 'Car Penalty',
        severity: 'high',
        title: 'Pink Cadillac co-pay if you miss volume',
        details: 'The famous Pink Cadillac isn\'t free - if you fall below required team production, you must make a co-payment of $300-900/month. Many consultants have been surprised by these charges.',
        sourceNote: 'Mary Kay Career Car Program',
      },
      {
        category: 'Chargebacks',
        severity: 'high',
        title: 'Directors face chargebacks when recruits return products',
        details: 'If someone you recruited returns their inventory, you may face chargebacks on the commission you earned from their initial order. This creates financial volatility.',
        sourceNote: 'Mary Kay Director Agreement',
      },
      {
        category: 'Required Purchases',
        severity: 'medium',
        title: '$225 wholesale minimum every 2 months',
        details: 'To remain an "active" consultant, you must purchase at least $225 wholesale in Section 1 products every 2 months. That\'s $1,350/year minimum before earning anything.',
        sourceNote: 'Mary Kay Activity Requirements',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Unit stays with company if you leave or are terminated',
        details: 'The team (unit) you build belongs to Mary Kay, not you. Leave or get terminated and your organization continues without you.',
        sourceNote: 'Mary Kay Consultant Agreement',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation of team members',
        details: 'You cannot recruit your former team members to competing cosmetics MLMs after leaving Mary Kay.',
        sourceNote: 'Mary Kay Consultant Agreement',
      },
      {
        category: 'Buyback',
        severity: 'low',
        title: '90% buyback available but with conditions',
        details: 'Mary Kay offers a 90% buyback on products purchased within 12 months. However, there may be delays and the process isn\'t always smooth according to former consultants.',
        sourceNote: 'Mary Kay Return Policy',
      },
      {
        category: 'Income Reality',
        severity: 'medium',
        title: 'Directors average $19,658/year in Canada (2024)',
        details: 'Even at the Director level, average annual income is under $20,000 - and that\'s before expenses like inventory, samples, and events.',
        sourceNote: 'Mary Kay Income Disclosure (Canada)',
      },
    ],
    bottomLine: 'Mary Kay\'s glamorous image masks real financial risks. The pressure to buy inventory, combined with car co-pay penalties and director chargebacks, means you can end up owing money while appearing successful. The business culture celebrates achievement but doesn\'t adequately warn about the downside risks.',
    policyUrl: 'https://www.marykay.com/en-us/tips-and-trends/beauty-entrepreneur',
  },
  {
    companySlug: 'monat-global',
    companyName: 'MONAT Global',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Multiple product liability lawsuits, high refund rates, and 41% zero-earners indicate structural problems.',
    pitfalls: [
      {
        category: 'Product Liability',
        severity: 'high',
        title: 'Class action lawsuits over hair loss claims',
        details: 'MONAT has faced multiple lawsuits from customers claiming the products caused hair loss, scalp irritation, and other issues. While MONAT disputes these claims, the legal history is extensive.',
        sourceNote: 'Florida Class Action Lawsuit, BBB Complaints',
      },
      {
        category: 'Income Reality',
        severity: 'high',
        title: '41% of Market Partners earned $0 in 2024',
        details: 'According to MONAT\'s own income disclosure, 41% of Market Partners earned zero commissions. The average earner made just $758/year before expenses.',
        sourceNote: 'MONAT Income Disclosure Statement 2024',
      },
      {
        category: 'Non-Compete',
        severity: 'high',
        title: '6-month waiting period to change sponsors or rejoin',
        details: 'If you leave MONAT, you cannot rejoin under a different sponsor or compete with your former organization for 6 months.',
        sourceNote: 'MONAT Policies & Procedures',
      },
      {
        category: 'Termination',
        severity: 'high',
        title: 'Organization retained by company upon termination',
        details: 'MONAT keeps your entire organization if you\'re terminated. Policy violations, including social media missteps, can trigger termination.',
        sourceNote: 'MONAT Market Partner Agreement',
      },
      {
        category: 'Social Media',
        severity: 'medium',
        title: 'Strict social media policies',
        details: 'MONAT has detailed rules about what Market Partners can post. Making income claims or product claims that violate FDA guidelines can result in warnings or termination.',
        sourceNote: 'MONAT Social Media Guidelines',
      },
      {
        category: 'Required Activity',
        severity: 'medium',
        title: 'Must maintain activity to keep rank and commissions',
        details: 'Rank is not guaranteed - you must continue meeting sales and team volume requirements or face demotion.',
        sourceNote: 'MONAT Compensation Plan',
      },
      {
        category: 'Refund Issues',
        severity: 'medium',
        title: 'BBB complaints cite refund difficulties',
        details: 'The BBB shows numerous complaints about difficulty obtaining refunds for products and the VIP subscription program.',
        sourceNote: 'BBB Business Profile',
      },
      {
        category: 'Arbitration',
        severity: 'medium',
        title: 'Mandatory arbitration for disputes',
        details: 'The Market Partner Agreement requires binding arbitration, eliminating class action and jury trial options.',
        sourceNote: 'MONAT Market Partner Agreement',
      },
    ],
    bottomLine: 'MONAT\'s product liability lawsuits should give anyone pause. When 41% of participants earn nothing and the company faces ongoing legal challenges over product safety, the risk profile is significant. The income disclosure shows the opportunity rarely pays off for most participants.',
    policyUrl: 'https://monatglobal.com/opportunity/',
  },
  {
    companySlug: 'nu-skin-enterprises',
    companyName: 'Nu Skin Enterprises',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'History of regulatory issues, declining revenue, and complex block-based compensation make success difficult.',
    pitfalls: [
      {
        category: 'Regulatory',
        severity: 'high',
        title: 'Multiple regulatory investigations globally',
        details: 'Nu Skin has faced FTC scrutiny in the US, regulatory challenges in China, and settlements related to improper income and product claims across multiple countries.',
        sourceNote: 'FTC Records, International News Reports',
      },
      {
        category: 'Income Reality',
        severity: 'high',
        title: 'Only 24.67% of Brand Affiliates were "Active" in 2024',
        details: 'Three-quarters of Brand Affiliates don\'t meet the activity threshold. Among those who do, average monthly earnings are just $178.35.',
        sourceNote: 'Nu Skin Income Disclosure 2024',
      },
      {
        category: 'Financial Decline',
        severity: 'high',
        title: 'Net income dropped from $124.7M (2021) to $54.3M (2024)',
        details: 'Nu Skin\'s profitability has declined significantly, which could signal challenges ahead for distributor earnings.',
        sourceNote: 'Nu Skin Annual Reports',
      },
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '100 PSV monthly minimum',
        details: 'You must maintain 100 Personal Sales Volume (roughly $100) monthly to qualify for any commissions beyond basic retail profit.',
        sourceNote: 'Nu Skin Sales Performance Plan',
      },
      {
        category: 'Comp Plan Complexity',
        severity: 'medium',
        title: 'Block-based system is difficult to understand',
        details: 'Nu Skin\'s compensation plan uses 500-point "blocks" that determine commissions. This complexity makes it hard to predict or understand your earnings.',
        sourceNote: 'Nu Skin Compensation Plan',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization retained upon termination',
        details: 'Like other MLMs, your downline stays with Nu Skin if your agreement ends for any reason.',
        sourceNote: 'Nu Skin Brand Affiliate Agreement',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation provisions apply after leaving',
        details: 'You cannot recruit your former team to competing opportunities for a period after your agreement ends.',
        sourceNote: 'Nu Skin Policies & Procedures',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Marketplace sales prohibited',
        details: 'Selling Nu Skin products on Amazon, eBay, or similar platforms is against policy and can result in termination.',
        sourceNote: 'Nu Skin Rules of Conduct',
      },
    ],
    bottomLine: 'Nu Skin\'s global regulatory troubles and declining financial performance should raise red flags. With only 1 in 4 affiliates meeting "active" status and average earnings under $200/month, the opportunity doesn\'t deliver for most. The complex block system makes it even harder to build predictable income.',
    policyUrl: 'https://www.nuskin.com/en_US/opportunity',
  },
  {
    companySlug: 'avon-products',
    companyName: 'Avon Products',
    lastUpdated: '2026-03-20',
    overallRisk: 'medium',
    riskReason: 'Recent restructuring and low per-campaign minimums make it more accessible, though income remains limited.',
    pitfalls: [
      {
        category: 'Comp Plan Changes',
        severity: 'high',
        title: 'Major compensation restructure in January 2025',
        details: 'Avon completely restructured its compensation plan in early 2025. While designed to improve accessibility, any major change creates uncertainty for existing representatives.',
        sourceNote: 'Avon 2025 Compensation Guide',
      },
      {
        category: 'Variable Earnings',
        severity: 'medium',
        title: 'Commission rates now vary per campaign',
        details: 'Under the new structure, your commission rate changes based on that specific 2-week campaign\'s sales volume. This makes income less predictable.',
        sourceNote: 'Avon 2025 Career & Compensation Guide',
      },
      {
        category: 'Minimum Order',
        severity: 'medium',
        title: '$40 minimum order required to earn commission',
        details: 'You must reach at least $40 in orders per campaign to earn any commission for that cycle. Below that, you earn nothing.',
        sourceNote: 'Avon Compensation Plan',
      },
      {
        category: 'Category Differences',
        severity: 'low',
        title: 'Different rates for different product categories',
        details: 'Beauty and Jewelry items earn 25% base commission while Home and Fashion earn 20%. Your product mix affects earnings.',
        sourceNote: 'Avon Compensation Plan',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation provisions exist',
        details: 'Standard provisions prevent recruiting your team to competing opportunities after leaving.',
        sourceNote: 'Avon Representative Agreement',
      },
      {
        category: 'Team Building Required',
        severity: 'medium',
        title: 'Star Promoter bonuses require recruitment',
        details: 'To access team-based bonuses, you must recruit others. Retail-only representatives have limited earnings potential.',
        sourceNote: 'Avon Star Promoter Program',
      },
      {
        category: 'Brand Perception',
        severity: 'low',
        title: 'Brand seen as outdated by some demographics',
        details: 'While Avon has a long history, some potential customers perceive the brand as dated, which can affect sales.',
        sourceNote: 'Industry Analysis',
      },
    ],
    bottomLine: 'Avon\'s 2025 restructuring is a double-edged sword. The lower minimums ($40/campaign) and variable commission structure may be more accessible, but also make income less predictable. The brand\'s legacy is both a strength and challenge depending on your target market.',
    policyUrl: 'https://www.avon.com/becomearep',
  },
  {
    companySlug: 'primerica',
    companyName: 'Primerica',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Licensing costs, captive agent restrictions, and low starting commissions create barriers to profitability.',
    pitfalls: [
      {
        category: 'Licensing Costs',
        severity: 'high',
        title: 'Must pay $200-500+ for insurance licensing',
        details: 'Before earning anything, you must obtain a state insurance license. This costs $200-500 or more including exam fees, background checks, and continuing education.',
        sourceNote: 'State Insurance Requirements',
      },
      {
        category: 'Captive Agent',
        severity: 'high',
        title: 'Can only sell Primerica products',
        details: 'As a Primerica representative, you\'re a captive agent. You cannot sell competing insurance or financial products, even if they would better serve your client.',
        sourceNote: 'Primerica Representative Agreement',
      },
      {
        category: 'Low Starting Commission',
        severity: 'high',
        title: 'New reps earn only 25% commission',
        details: 'Entry-level representatives earn 25% commission on sales, while the company and upline keep 75%. You must advance through ranks to earn more.',
        sourceNote: 'Primerica Compensation Plan',
      },
      {
        category: 'Client Ownership',
        severity: 'high',
        title: 'Clients belong to Primerica, not you',
        details: 'If you leave Primerica, your clients stay with the company. You cannot take your book of business to another insurance agency.',
        sourceNote: 'Primerica Representative Agreement',
      },
      {
        category: 'Securities Requirements',
        severity: 'medium',
        title: 'Additional licenses needed for investment products',
        details: 'To sell investment products, you must pass Series 6 and other securities exams. More time and money invested before full earnings potential.',
        sourceNote: 'FINRA Requirements',
      },
      {
        category: 'Startup Costs',
        severity: 'medium',
        title: '$99 startup fee plus licensing costs',
        details: 'The $99 fee is just the beginning. With licensing, training materials, and other costs, new reps often invest $500+ before making their first sale.',
        sourceNote: 'Primerica Enrollment',
      },
      {
        category: 'Income Reality',
        severity: 'medium',
        title: 'Average rep earned $8,199 in 2025',
        details: 'The average annual earnings of $8,199 is before expenses and doesn\'t reflect the significant investment in licensing and training.',
        sourceNote: 'Primerica Income Disclosure',
      },
      {
        category: 'Non-Compete',
        severity: 'high',
        title: 'Cannot compete or solicit clients after leaving',
        details: 'Non-compete provisions prevent you from approaching your former clients or team members for a period after leaving.',
        sourceNote: 'Primerica Representative Agreement',
      },
    ],
    bottomLine: 'Primerica adds professional licensing requirements on top of MLM challenges. The captive agent model means you can\'t serve clients with the best products available - only Primerica products. Combined with low starting commissions (25%) and the inability to keep your clients if you leave, the structure heavily favors the company.',
    policyUrl: 'https://www.primerica.com/public/opportunity.html',
  },
  {
    companySlug: 'melaleuca',
    companyName: 'Melaleuca',
    lastUpdated: '2026-03-20',
    overallRisk: 'medium',
    riskReason: 'Monthly purchase requirements and low per-customer earnings limit income potential despite product-focused model.',
    pitfalls: [
      {
        category: 'Income Reality',
        severity: 'high',
        title: '82% of members earned $0 in commissions',
        details: 'According to Melaleuca\'s own income disclosure, the vast majority of participants earn no commissions at all.',
        sourceNote: 'Melaleuca Income Statistics',
      },
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '35 Product Points (~$55-70) monthly minimum',
        details: 'To remain qualified for any commissions, you must maintain 35 Product Points monthly through personal or customer orders.',
        sourceNote: 'Melaleuca Marketing Executive Agreement',
      },
      {
        category: 'Autoship Difficulty',
        severity: 'medium',
        title: 'Canceling autoship can be complicated',
        details: 'Some members report difficulty canceling their monthly autoship orders, leading to unwanted charges.',
        sourceNote: 'Customer Reviews, BBB Complaints',
      },
      {
        category: 'Low Ongoing Earnings',
        severity: 'medium',
        title: 'Only 7% commission on ongoing customer orders',
        details: 'After the first-month 50% bonus, ongoing commission drops to just 7% per customer. You need many active customers to earn meaningful income.',
        sourceNote: 'Melaleuca Compensation Plan',
      },
      {
        category: 'Product Advocate Reality',
        severity: 'medium',
        title: 'Product Advocates average $110-510/year',
        details: 'Even at the Product Advocate level, annual earnings are modest, averaging between $110 and $510 before expenses.',
        sourceNote: 'Melaleuca Income Disclosure',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Cannot recruit members to competing businesses',
        details: 'Standard non-solicitation provisions prevent recruiting your team to other opportunities.',
        sourceNote: 'Melaleuca Policies & Procedures',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization stays with Melaleuca upon termination',
        details: 'Like other MLMs, your customer and team organization remains with the company if you leave.',
        sourceNote: 'Melaleuca Agreement',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Products cannot be sold through third-party channels',
        details: 'Melaleuca prohibits selling through Amazon, eBay, or other unauthorized channels.',
        sourceNote: 'Melaleuca Policies & Procedures',
      },
    ],
    bottomLine: 'Melaleuca positions itself as different from traditional MLMs, but the numbers tell a familiar story. With 82% earning nothing and ongoing commissions of just 7%, you need a large customer base to earn meaningful income. The monthly purchase requirement means you\'re spending money every month regardless of earnings.',
    policyUrl: 'https://www.melaleuca.com/productstore/marketing-executive',
  },
  {
    companySlug: 'usana-health-sciences',
    companyName: 'USANA Health Sciences',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Binary compensation complexity, declining company profits, and balance requirements make earnings unpredictable.',
    pitfalls: [
      {
        category: 'Financial Decline',
        severity: 'high',
        title: 'Net income dropped significantly from 2021 to 2024',
        details: 'USANA\'s net income fell from $124.7M in 2021 to $54.3M in 2024, signaling potential challenges for distributor earnings.',
        sourceNote: 'USANA Annual Reports',
      },
      {
        category: 'Binary Complexity',
        severity: 'high',
        title: 'Must balance two legs to maximize earnings',
        details: 'USANA\'s binary compensation plan pays 20% of the lesser leg volume. If your legs are unbalanced (e.g., 1000/100), you only earn on the smaller side. Volume doesn\'t carry over proportionally.',
        sourceNote: 'USANA Compensation Plan',
      },
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '100 PSV per rolling 4-week period',
        details: 'You must maintain 100 Personal Sales Volume (roughly $100 in products) every 4 weeks to qualify for commissions.',
        sourceNote: 'USANA Sales Performance Plan',
      },
      {
        category: 'Minimum Volume',
        severity: 'medium',
        title: '125 SVP minimum to earn commissions',
        details: 'You need at least 125 Sales Volume Points in your team before earning any Building Bonus commissions.',
        sourceNote: 'USANA Compensation Plan',
      },
      {
        category: 'Comp Plan Changes',
        severity: 'medium',
        title: 'October 2025 plan adds new requirements',
        details: 'The updated compensation plan introduces new Fast Start bonuses and Milestone requirements. Changes to comp plans can affect existing distributors\' earnings.',
        sourceNote: 'USANA October 2025 Updates',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation of associates and customers',
        details: 'You cannot recruit your team members or customers to competing opportunities after leaving USANA.',
        sourceNote: 'USANA Associate Agreement',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization remains with company upon termination',
        details: 'Your downline stays with USANA if you leave or are terminated for any reason.',
        sourceNote: 'USANA Associate Agreement',
      },
      {
        category: 'Premium Pricing',
        severity: 'low',
        title: 'Products priced significantly above retail alternatives',
        details: 'USANA\'s premium pricing can make customer acquisition challenging in a competitive supplement market.',
        sourceNote: 'Product Pricing Analysis',
      },
    ],
    bottomLine: 'USANA\'s binary plan looks attractive on paper but is difficult in practice. Balancing two legs while maintaining personal volume requirements is a constant challenge. With the company\'s declining profitability, the economics may get harder rather than easier.',
    policyUrl: 'https://www.usana.com/ux/dotcom/en_US/business-opportunity',
  },
  {
    companySlug: 'isagenix',
    companyName: 'Isagenix',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Binary structure, rank advancement pressures, and high product prices create typical MLM challenges.',
    pitfalls: [
      {
        category: 'Binary Complexity',
        severity: 'high',
        title: 'Must build two legs for cycle bonuses',
        details: 'Isagenix\'s binary structure pays $54 per cycle when you accumulate 600 BV on one leg and 300 BV on the other. Unbalanced growth means leaving money on the table.',
        sourceNote: 'Isagenix Compensation Plan',
      },
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '100 BV monthly to stay qualified',
        details: 'You must maintain 100 Business Volume (roughly $100-150 in products) monthly to qualify for any commissions beyond retail profit.',
        sourceNote: 'Isagenix Compensation Plan',
      },
      {
        category: 'Rank Pressure',
        severity: 'medium',
        title: 'Rank advancement bonuses encourage rapid growth',
        details: 'Bonuses of $50 to $3,000 for hitting ranks quickly can encourage aggressive recruiting and product purchasing to meet short-term goals.',
        sourceNote: 'Isagenix Rank Advancement Program',
      },
      {
        category: 'Premium Pricing',
        severity: 'medium',
        title: 'Products are expensive compared to retail alternatives',
        details: 'Isagenix\'s cleanse and weight loss products are premium-priced, making customer acquisition and retention challenging.',
        sourceNote: 'Product Pricing Comparison',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation of downline after leaving',
        details: 'Standard provisions prevent recruiting your team to competing opportunities after your agreement ends.',
        sourceNote: 'Isagenix Associate Agreement',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization stays with Isagenix upon termination',
        details: 'Your team and customer organization remains with the company if you leave for any reason.',
        sourceNote: 'Isagenix Associate Agreement',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Cannot sell on Amazon, eBay, or similar',
        details: 'Marketplace sales are prohibited, limiting your sales channels.',
        sourceNote: 'Isagenix Policies & Procedures',
      },
      {
        category: 'Arbitration',
        severity: 'medium',
        title: 'Disputes resolved through binding arbitration',
        details: 'The Associate Agreement includes mandatory arbitration, limiting legal options.',
        sourceNote: 'Isagenix Associate Agreement',
      },
    ],
    bottomLine: 'Isagenix\'s binary structure has the same balance challenges as other binary MLMs. Combined with premium-priced products and monthly purchase requirements, you need strong sales and recruiting skills to make the math work. The rank bonus structure can encourage behaviors that aren\'t sustainable long-term.',
    policyUrl: 'https://www.isagenix.com/en-us/become-an-associate',
  },
  {
    companySlug: 'rodan-fields',
    companyName: 'Rodan + Fields',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Ended MLM model completely in 2024, demonstrating how quickly MLM income can disappear.',
    pitfalls: [
      {
        category: 'Model Change',
        severity: 'high',
        title: 'MLM model ended September 1, 2024',
        details: 'Rodan + Fields completely eliminated their MLM structure and transitioned to a single-level affiliate model. Consultants who had built downline organizations lost that recurring income overnight.',
        sourceNote: 'R+F Official Announcement August 2024',
      },
      {
        category: 'Lost Income',
        severity: 'high',
        title: 'Multi-level downline income eliminated',
        details: 'Consultants who had built teams earning override commissions saw that income disappear. There was no compensation for lost downline income.',
        sourceNote: 'R+F Business Changes Blog Post',
      },
      {
        category: 'Lesson Learned',
        severity: 'high',
        title: 'Demonstrates MLM income is never truly passive or secure',
        details: 'R+F proves that even well-established MLMs can change their model and eliminate multi-level income at any time. Years of team building can become worthless with a corporate decision.',
        sourceNote: 'Industry Analysis',
      },
      {
        category: 'New Model',
        severity: 'medium',
        title: 'Now single-level 30% affiliate commission',
        details: 'Under the new model, affiliates earn 30% on personal sales only. While simpler, there\'s no leverage from team building.',
        sourceNote: 'R+F Affiliate Program 2024',
      },
      {
        category: 'Annual Fee',
        severity: 'low',
        title: '$9.99 annual affiliate fee',
        details: 'The new affiliate program costs $9.99/year, down from the previous $75 consultant starter kit.',
        sourceNote: 'R+F Affiliate Enrollment',
      },
      {
        category: 'Historical Issues',
        severity: 'medium',
        title: 'Prior MLM had standard non-compete and termination clauses',
        details: 'Under the former MLM model, consultants faced typical restrictions including non-solicitation of downline and loss of organization upon termination.',
        sourceNote: 'Former R+F Consultant Agreement',
      },
    ],
    bottomLine: 'Rodan + Fields is the clearest example of why MLM "residual income" is never secure. When the company decided to change its business model, thousands of consultants lost their downline income with no recourse. This can happen to ANY MLM - your income depends on corporate decisions you don\'t control.',
    policyUrl: 'https://www.rodanandfields.com/en-us/become-a-consultant',
  },
  {
    companySlug: 'lularoe',
    companyName: 'LuLaRoe',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'History of lawsuits, inventory risks, and buyback policy failures make this a cautionary tale.',
    pitfalls: [
      {
        category: 'Inventory Risk',
        severity: 'high',
        title: '$499 minimum inventory purchase to start',
        details: 'LuLaRoe requires purchasing an initial inventory package of 65 pieces for $499. This is your money at risk if you can\'t sell the products.',
        sourceNote: 'LuLaRoe Enrollment Requirements',
      },
      {
        category: 'Legal History',
        severity: 'high',
        title: 'Multiple state attorney general settlements',
        details: 'LuLaRoe has faced lawsuits and settlements with multiple state attorneys general over its business practices, refund policies, and income claims.',
        sourceNote: 'Washington State AG Settlement',
      },
      {
        category: 'Buyback Problems',
        severity: 'high',
        title: 'History of not honoring buyback policies',
        details: 'LuLaRoe faced significant legal action over failing to properly buy back inventory from departing retailers, leaving many with unsellable merchandise.',
        sourceNote: 'Class Action Lawsuits, Documentary Coverage',
      },
      {
        category: 'Income Disparity',
        severity: 'high',
        title: 'Median earnings only $1,046/year (2024)',
        details: 'While average gross profit is $10,897, the median is just $1,046 - meaning top sellers dramatically skew the average. Most retailers earn very little.',
        sourceNote: 'LuLaRoe Income Disclosure Statement',
      },
      {
        category: 'Inventory Accumulation',
        severity: 'medium',
        title: 'Pressure to continuously buy new inventory',
        details: 'To stay competitive and offer customers variety, retailers face ongoing pressure to purchase new inventory beyond their initial investment.',
        sourceNote: 'Retailer Testimonials',
      },
      {
        category: 'Quality Issues',
        severity: 'medium',
        title: 'Product quality complaints',
        details: 'LuLaRoe has faced numerous complaints about inconsistent product quality, including leggings that tear easily, affecting retailer reputation.',
        sourceNote: 'BBB Complaints, Customer Reviews',
      },
      {
        category: 'Leadership Program',
        severity: 'medium',
        title: 'Only 9.63% participated in Leadership Program in 2024',
        details: 'The vast majority of retailers don\'t advance to leadership levels where team-based income is available.',
        sourceNote: 'LuLaRoe Income Disclosure Statement',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization retained by company upon termination',
        details: 'If you leave LuLaRoe, any team you\'ve built stays with the company.',
        sourceNote: 'LuLaRoe Retailer Agreement',
      },
    ],
    bottomLine: 'LuLaRoe\'s troubled history is well-documented in lawsuits and even a documentary. The inventory-based model puts your money at risk, and the company\'s past failures to honor buyback policies left many retailers with thousands in unsellable clothing. The median earnings of $1,046/year tell the real story.',
    policyUrl: 'https://www.lularoe.com/join',
  },
  {
    companySlug: 'plexus-worldwide',
    companyName: 'Plexus Worldwide',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Zero commission below 100 PV, tiered rates that require high volume, and health claim risks.',
    pitfalls: [
      {
        category: 'Zero Earnings Tier',
        severity: 'high',
        title: 'Earn 0% commission if under 100 PV monthly',
        details: 'Unlike most MLMs that pay reduced commissions, Plexus pays absolutely nothing if you don\'t hit 100 PV in a month. Fall short and you earn zero.',
        sourceNote: 'Plexus Compensation Plan',
      },
      {
        category: 'Tiered Commission',
        severity: 'high',
        title: 'Must reach $500+ PV for 25% commission rate',
        details: 'The commission structure is heavily tiered: 0% under 100 PV, 15% at 100-499 PV, and 25% only at 500+ PV. Reaching the top tier requires significant sales.',
        sourceNote: 'Plexus Compensation Plan',
      },
      {
        category: 'Health Claims Risk',
        severity: 'high',
        title: 'Weight loss and health claims create legal risk',
        details: 'Plexus products are promoted for weight loss and health benefits. Making unauthorized claims can result in FDA issues and termination.',
        sourceNote: 'FDA Regulations, Plexus Policies',
      },
      {
        category: 'Membership Fee',
        severity: 'medium',
        title: 'Plexus Annual Membership (PAM) required',
        details: 'Ambassadors must pay an annual membership fee to remain qualified for commissions.',
        sourceNote: 'Plexus Enrollment Requirements',
      },
      {
        category: 'Car Bonus Requirements',
        severity: 'medium',
        title: 'Jewel Car Bonus requires high rank achievement',
        details: 'The car bonus ($600-1,450/month) requires reaching and maintaining high ranks with substantial team volume. Miss requirements and you lose the bonus.',
        sourceNote: 'Plexus Compensation Plan',
      },
      {
        category: 'Income Reality',
        severity: 'medium',
        title: 'Active Ambassador average: $2,952/year',
        details: 'Average annual earnings for Active Ambassadors is $2,952 before expenses - about $246/month.',
        sourceNote: 'Plexus Income Disclosure',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation of downline',
        details: 'Standard provisions prevent recruiting your team to competing opportunities.',
        sourceNote: 'Plexus Ambassador Agreement',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization retained upon termination',
        details: 'Your team and customer organization stays with Plexus if you leave.',
        sourceNote: 'Plexus Ambassador Agreement',
      },
    ],
    bottomLine: 'Plexus\'s tiered commission structure is particularly harsh - earn literally nothing if you don\'t hit 100 PV monthly. Combined with health product claim risks and the high volume needed for meaningful commission rates, most ambassadors struggle to profit.',
    policyUrl: 'https://www.plexusworldwide.com/join',
  },
  {
    companySlug: 'forever-living-products',
    companyName: 'Forever Living Products',
    lastUpdated: '2026-03-20',
    overallRisk: 'medium',
    riskReason: 'Case credit requirements and discount tier system create familiar MLM income barriers.',
    pitfalls: [
      {
        category: 'Tiered Discounts',
        severity: 'high',
        title: 'Only 5% discount at entry level',
        details: 'New Preferred Customers start with just 5% discount. To reach the 30% wholesale level, you must purchase 2 Case Credits within 2 months - a significant initial investment.',
        sourceNote: 'Forever Living Marketing Plan',
      },
      {
        category: 'Case Credit Requirements',
        severity: 'high',
        title: '2CC in 2 months to reach wholesale pricing',
        details: 'The "Wholesale Qualified" level requires purchasing 2 Case Credits in your first 2 months. This creates pressure for upfront inventory purchases.',
        sourceNote: 'Forever Living Marketing Plan',
      },
      {
        category: 'Niche Products',
        severity: 'medium',
        title: 'Aloe vera products have limited market appeal',
        details: 'Forever Living focuses on aloe vera products, which appeals to a niche market. This can make customer acquisition more challenging than with broader product lines.',
        sourceNote: 'Product Line Analysis',
      },
      {
        category: 'Manager Requirements',
        severity: 'medium',
        title: 'Manager rank requires significant organization',
        details: 'To earn Manager overrides (18% on Manager volume plus generation bonuses), you need a substantial team with consistent volume.',
        sourceNote: 'Forever Living Compensation Plan',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Cannot solicit downline to competing businesses',
        details: 'Standard non-solicitation provisions apply to your team members and customers.',
        sourceNote: 'Forever Living FBO Agreement',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization retained by company upon termination',
        details: 'Your organization stays with Forever Living if you leave or are terminated.',
        sourceNote: 'Forever Living FBO Agreement',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Marketplace sales prohibited',
        details: 'Products cannot be sold on Amazon, eBay, or similar platforms.',
        sourceNote: 'Forever Living Policies & Procedures',
      },
      {
        category: 'Income Estimate',
        severity: 'low',
        title: 'Estimated 35% commission payout ($595M annually)',
        details: 'Forever Living pays approximately 35% of revenue in commissions. While substantial overall, individual earnings vary dramatically.',
        sourceNote: 'Industry Estimates',
      },
    ],
    bottomLine: 'Forever Living\'s tiered discount system means you start earning very little (5%) until you invest significantly in product purchases. The aloe vera niche may limit your customer base compared to more mainstream product categories.',
    policyUrl: 'https://www.foreverliving.com/usa/en-us/opportunity/default',
  },
  {
    companySlug: 'scentsy',
    companyName: 'Scentsy',
    lastUpdated: '2026-03-20',
    overallRisk: 'medium',
    riskReason: 'Increased PRV requirements in 2025 and durable product challenges affect recurring income potential.',
    pitfalls: [
      {
        category: 'Requirement Increase',
        severity: 'high',
        title: 'April 2025: Active status now requires 250 PRV (up from 200)',
        details: 'Scentsy increased the monthly requirement to maintain Active status by 25%. This means higher sales needed just to remain qualified for full commissions.',
        sourceNote: 'Scentsy April 2025 Updates',
      },
      {
        category: 'Below Threshold Penalty',
        severity: 'high',
        title: 'Only 20% commission if under 250 PRV',
        details: 'Fall below 250 PRV monthly and you earn only 20% commission with no access to bonuses. The penalty for missing the threshold is significant.',
        sourceNote: 'Scentsy Compensation Plan',
      },
      {
        category: 'Durable Products',
        severity: 'medium',
        title: 'Wax warmers are durable goods with limited repeat purchases',
        details: 'Unlike consumables, wax warmers last for years. This limits repeat customer purchases and requires constantly finding new customers.',
        sourceNote: 'Product Category Analysis',
      },
      {
        category: 'Volume Bonus Changes',
        severity: 'medium',
        title: 'Monthly Sales Award now requires 2,500 PRV (up from 2,000)',
        details: 'The threshold for sales award bonuses increased by 25%, making these bonuses harder to earn.',
        sourceNote: 'Scentsy April 2025 Updates',
      },
      {
        category: 'Commission Range',
        severity: 'medium',
        title: 'Wide commission range: 10% to 36%',
        details: 'Your commission rate varies dramatically based on your monthly PRV and rank. New or lower-volume consultants earn far less per sale.',
        sourceNote: 'Scentsy Compensation Plan',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation provisions apply',
        details: 'Standard provisions prevent recruiting your downline to competing home fragrance or party plan companies.',
        sourceNote: 'Scentsy Consultant Agreement',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization retained by Scentsy upon termination',
        details: 'Your team and customer organization stays with the company if you leave.',
        sourceNote: 'Scentsy Consultant Agreement',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Cannot sell through unauthorized channels',
        details: 'Products cannot be sold on Amazon, eBay, or at unauthorized events.',
        sourceNote: 'Scentsy Policies & Procedures',
      },
    ],
    bottomLine: 'Scentsy\'s 2025 requirement increases make earning harder. The durable nature of wax warmers (their primary product) means limited repeat purchases compared to consumables. You need a constant stream of new customers to maintain volume.',
    policyUrl: 'https://scentsy.com/join',
  },
  {
    companySlug: 'pampered-chef',
    companyName: 'Pampered Chef',
    lastUpdated: '2026-03-20',
    overallRisk: 'low',
    riskReason: 'Lower activity requirements and durable kitchen products, though limited repeat sales remain a challenge.',
    pitfalls: [
      {
        category: 'Durable Products',
        severity: 'medium',
        title: 'Kitchen tools are durable goods with limited repeat purchases',
        details: 'Once customers buy quality cookware, they don\'t need to replace it for years. This limits recurring customer orders compared to consumable products.',
        sourceNote: 'Product Category Analysis',
      },
      {
        category: 'Income Reality',
        severity: 'medium',
        title: 'Typical Active Consultant earned $0-262 annually (Canada 2024)',
        details: 'Most Active Consultants earn very modest amounts. Significant income requires substantial sales volume and team building.',
        sourceNote: 'Pampered Chef Income Disclosure (Canada)',
      },
      {
        category: 'Inactive Rate',
        severity: 'medium',
        title: '28% of consultants were not Active and earned $0',
        details: 'Over a quarter of consultants don\'t meet minimum activity requirements and earn nothing.',
        sourceNote: 'Pampered Chef Income Disclosure',
      },
      {
        category: 'Startup Costs',
        severity: 'low',
        title: 'Starter kits range $70-320',
        details: 'Unlike some MLMs, Pampered Chef offers multiple kit options starting at $70. However, the most complete kit costs $320.',
        sourceNote: 'Pampered Chef Enrollment Options',
      },
      {
        category: 'Activity Minimum',
        severity: 'low',
        title: 'Only $30 in sales every 6 months to stay active',
        details: 'Pampered Chef has one of the lowest activity minimums in the MLM industry. This makes it accessible but also means many consultants earn very little.',
        sourceNote: 'Pampered Chef Consultant Agreement',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation of team members',
        details: 'You cannot recruit your team to competing kitchen/party plan companies after leaving.',
        sourceNote: 'Pampered Chef Consultant Agreement',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization retained upon termination',
        details: 'Your team stays with Pampered Chef if you leave or are terminated.',
        sourceNote: 'Pampered Chef Consultant Agreement',
      },
    ],
    bottomLine: 'Pampered Chef is more accessible than many MLMs with low minimums ($30 every 6 months) and reasonable starter kits. The main challenge is the durable nature of kitchen tools - customers don\'t need repeat purchases frequently, limiting recurring income potential.',
    policyUrl: 'https://www.pamperedchef.com/join-pampered-chef',
  },
  {
    companySlug: 'arbonne-international',
    companyName: 'Arbonne International',
    lastUpdated: '2026-03-20',
    overallRisk: 'medium',
    riskReason: 'High PQV requirements and tiered client commissions create barriers to profitability.',
    pitfalls: [
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '150 PQV monthly required for most qualifications',
        details: 'Most rank qualifications require 150 Personal Qualifying Volume monthly. This translates to roughly $150 or more in product purchases or sales.',
        sourceNote: 'Arbonne Compensation Plan',
      },
      {
        category: 'Override Requirements',
        severity: 'high',
        title: '500 PQV required for paid-as overrides',
        details: 'To actually receive override commissions on your team\'s sales, you must personally generate 500 PQV - significantly higher than basic qualification.',
        sourceNote: 'Arbonne Compensation Plan',
      },
      {
        category: 'Commission Tiers',
        severity: 'medium',
        title: 'Preferred Clients earn you only 15% (vs 35% for regular Clients)',
        details: 'The Preferred Client program that offers customers a discount means lower commissions for you - 15% vs 35% on regular client orders.',
        sourceNote: 'Arbonne Compensation Plan',
      },
      {
        category: 'Premium Pricing',
        severity: 'medium',
        title: 'Vegan/clean beauty positioning limits market',
        details: 'Arbonne\'s premium vegan positioning appeals to a specific demographic but can limit your potential customer base compared to mainstream beauty brands.',
        sourceNote: 'Market Analysis',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation of organization members',
        details: 'Standard provisions prevent recruiting your team to competing health/beauty MLMs.',
        sourceNote: 'Arbonne Independent Consultant Agreement',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization retained by Arbonne upon termination',
        details: 'Your team and customer organization stays with the company if you leave.',
        sourceNote: 'Arbonne Independent Consultant Agreement',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Cannot sell through unauthorized channels',
        details: 'Products cannot be sold on Amazon, eBay, or similar marketplaces.',
        sourceNote: 'Arbonne Policies & Procedures',
      },
      {
        category: 'Arbitration',
        severity: 'medium',
        title: 'Disputes resolved through arbitration',
        details: 'The Consultant Agreement includes mandatory arbitration provisions.',
        sourceNote: 'Arbonne Independent Consultant Agreement',
      },
    ],
    bottomLine: 'Arbonne\'s dual PQV requirements (150 for basic, 500 for overrides) mean you need substantial personal volume to earn team commissions. The two-tier client system where Preferred Clients earn you less creates an awkward dynamic between customer savings and your earnings.',
    policyUrl: 'https://www.arbonne.com/us/en/join',
  },
  {
    companySlug: 'four-life-research',
    companyName: '4Life Research',
    lastUpdated: '2026-03-20',
    overallRisk: 'medium',
    riskReason: 'First-order bonuses drop significantly for ongoing orders, and niche products limit market appeal.',
    pitfalls: [
      {
        category: 'Income Drop',
        severity: 'high',
        title: 'Ongoing Level 1 commissions drop to just 2%',
        details: 'While Rapid Rewards pays 25% on first orders, ongoing commissions at Level 1 drop to only 2%. The dramatic difference between new and repeat customer earnings is significant.',
        sourceNote: '4Life Compensation Plan',
      },
      {
        category: 'Power Pool Requirements',
        severity: 'medium',
        title: 'Power Pool requires 3 new distributors with 100 LP for 2 months',
        details: 'To access the 3% company-wide Power Pool, you must recruit 3 new distributors who each maintain 100 LP for 2 consecutive months. A specific and challenging requirement.',
        sourceNote: '4Life Life Rewards Plan',
      },
      {
        category: 'Required Purchases',
        severity: 'medium',
        title: '100 LP monthly to qualify for commissions',
        details: 'You must maintain 100 Life Points (roughly $100 in products) monthly to qualify for commissions beyond basic retail profit.',
        sourceNote: '4Life Compensation Plan',
      },
      {
        category: 'Niche Products',
        severity: 'medium',
        title: 'Transfer Factor products are specialized immune support',
        details: '4Life focuses on Transfer Factor immune support supplements, a niche category that may be unfamiliar to many potential customers.',
        sourceNote: 'Product Line Analysis',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-solicitation of downline',
        details: 'Standard provisions prevent recruiting your team to competing supplement MLMs.',
        sourceNote: '4Life Affiliate Agreement',
      },
      {
        category: 'Termination',
        severity: 'medium',
        title: 'Organization retained by 4Life upon termination',
        details: 'Your team and customer organization stays with the company if you leave.',
        sourceNote: '4Life Affiliate Agreement',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Cannot sell through unauthorized channels',
        details: 'Products cannot be sold on Amazon, eBay, or similar marketplaces.',
        sourceNote: '4Life Policies & Procedures',
      },
      {
        category: 'Market Size',
        severity: 'low',
        title: 'Estimated $300M revenue suggests smaller opportunity',
        details: 'With estimated 2024 revenue of $300M, 4Life is smaller than major MLM competitors, potentially limiting earning opportunities.',
        sourceNote: 'Industry Revenue Estimates',
      },
    ],
    bottomLine: '4Life\'s dramatic drop from 25% first-order bonus to 2% ongoing commissions means you constantly need new customers to maintain income. The specialized Transfer Factor product line may limit your market compared to more mainstream supplement brands.',
    policyUrl: 'https://www.4life.com/corp/opportunity',
  },
  {
    companySlug: 'livegood',
    companyName: 'LiveGood',
    lastUpdated: '2026-03-20',
    overallRisk: 'high',
    riskReason: 'Forced matrix heavily favors early joiners, no income disclosure, and tiny per-member earnings.',
    pitfalls: [
      {
        category: 'Matrix Structure',
        severity: 'high',
        title: 'Forced 2x15 matrix heavily favors early joiners',
        details: 'LiveGood\'s forced matrix means your position is everything. Early joiners automatically get spillover from the entire upline. Late joiners must fill their matrix from scratch with no structural advantage.',
        sourceNote: 'LiveGood Compensation Plan',
      },
      {
        category: 'Low Per-Member Earnings',
        severity: 'high',
        title: 'Only $0.25-0.50 per member per month',
        details: 'At 2.5% of a $9.95 membership, you earn about $0.25 per member per month. Even with hundreds of people in your matrix, earnings are minimal.',
        sourceNote: 'LiveGood Compensation Plan',
      },
      {
        category: 'No Income Disclosure',
        severity: 'high',
        title: 'No published income disclosure statement',
        details: 'As of 2026, LiveGood has not published an income disclosure statement. This lack of transparency makes it impossible to know what typical members actually earn.',
        sourceNote: 'LiveGood Website Review',
      },
      {
        category: 'Membership Costs',
        severity: 'medium',
        title: '$9.95 monthly before earning anything',
        details: 'You must pay $9.95/month to participate in the income opportunity. That\'s $119.40/year before earning a single commission.',
        sourceNote: 'LiveGood Enrollment',
      },
      {
        category: 'Spillover Uncertainty',
        severity: 'medium',
        title: 'Matrix spillover is unpredictable',
        details: 'Spillover from your upline sounds appealing but depends entirely on your position and your upline\'s activity. It\'s not guaranteed or predictable.',
        sourceNote: 'LiveGood Compensation Structure',
      },
      {
        category: 'Fast Growth Risk',
        severity: 'medium',
        title: 'Fast-growth companies often see slowdowns',
        details: 'LiveGood\'s recent rapid growth may not continue. Matrix-based companies often experience saturation effects where growth slows significantly.',
        sourceNote: 'MLM Industry Analysis',
      },
      {
        category: 'Massive Team Required',
        severity: 'high',
        title: 'Need 4,000+ members for $1,000/month',
        details: 'At $0.25/member/month, you need 4,000 active paying members to earn $1,000 monthly. The theoretical maximum requires a full 2^15 (32,768) member matrix.',
        sourceNote: 'LiveGood Compensation Math',
      },
    ],
    bottomLine: 'LiveGood\'s forced matrix is mathematically designed to favor early joiners. With earnings of only ~$0.25 per member per month, the numbers require thousands of people in your matrix to generate meaningful income. The lack of income disclosure is a red flag - transparent companies publish this data.',
    policyUrl: 'https://www.livegood.com/opportunity',
  },
];

// Helper to get pitfalls data by company slug
export function getPitfallsBySlug(slug: string): PitfallData | undefined {
  return pitfallsData.find(p => p.companySlug === slug);
}

// Helper to check if a company has pitfalls data
export function hasPitfalls(slug: string): boolean {
  return pitfallsData.some(p => p.companySlug === slug);
}

// Get all pitfall slugs for static generation
export function getAllPitfallSlugs(): string[] {
  return pitfallsData.map(p => p.companySlug);
}

// Get pitfalls sorted by risk level (high first)
export function getPitfallsSortedByRisk(): PitfallData[] {
  const riskOrder = { high: 0, medium: 1, low: 2 };
  return [...pitfallsData].sort((a, b) => riskOrder[a.overallRisk] - riskOrder[b.overallRisk]);
}
