export interface PitfallData {
  companySlug: string;
  companyName: string;
  lastUpdated: string;
  overallRisk: 'high' | 'medium' | 'low';
  riskReason: string;
  pitfalls: Array<{
    category: string;
    severity: 'high' | 'medium' | 'low';
    title: string;
    details: string;
    sourceNote: string;
  }>;
  bottomLine: string;
  policyUrl: string;
}

export const pitfallsData: PitfallData[] = [
  {
    companySlug: 'amway',
    companyName: 'Amway',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: '6-month non-compete, 12-month non-solicitation of IBOs, Line of Sponsorship treated as trade secret, and mandatory binding arbitration.',
    pitfalls: [
      {
        category: 'Non-Compete',
        severity: 'high',
        title: '6-month non-compete after leaving',
        details: 'Per Rule 6.2, for 6 months following expiration or termination, former IBOs agree not to own, manage, operate, consult for, or participate as an independent distributor in any direct sales program using a multilevel or network marketing structure, or any enterprise marketing products functionally interchangeable with Amway\'s.',
        sourceNote: 'Amway Rules of Conduct, Rule 6.2 (amway.com/rules-of-conduct)',
      },
      {
        category: 'Non-Solicitation',
        severity: 'high',
        title: '12-month non-solicitation of IBOs',
        details: 'Per Rule 6.2, for 12 months after leaving, former IBOs cannot encourage, solicit, or attempt to recruit any IBO or anyone who was an IBO within the past 12 months to participate in competing direct sales programs. This covenant survives termination.',
        sourceNote: 'Amway Rules of Conduct, Rule 6.2 (amway.com/rules-of-conduct)',
      },
      {
        category: 'Downline Ownership',
        severity: 'high',
        title: 'Line of Sponsorship is Amway\'s trade secret',
        details: 'Amway treats Line of Sponsorship (LOS) information as a "trade secret" and proprietary information. Upon termination, you must "promptly return any and all LOS Information to Amway and immediately discontinue any further use thereof." You don\'t own your downline - you have a revocable license to access it.',
        sourceNote: 'Amway IBO Registration Agreement, LOS Information Section',
      },
      {
        category: 'Arbitration',
        severity: 'high',
        title: 'Mandatory binding arbitration - class action waiver',
        details: 'The IBO agreement states: "THIS AGREEMENT IS SUBJECT TO BINDING ARBITRATION AND A WAIVER OF CLASS ACTION RIGHTS AS DETAILED IN SECTION 11." Arbitration is final and binding, governed by Michigan law and the Federal Arbitration Act. Demand must be made within 2 years.',
        sourceNote: 'Amway IBO Registration Agreement, Section 11; Rules of Conduct Rule 11.5',
      },
      {
        category: 'Customer Requirements',
        severity: 'medium',
        title: '70% customer sales requirement with verification',
        details: 'Per Rule 4.12, at least 70% of your Personal Volume must be from customer sales (not personal/family use), with 60% minimum from Verified Customer Sales. Per Rule 4.13, you need either 50 PV from customers or sales to 10 different customers monthly to earn Performance Bonus on downline volume.',
        sourceNote: 'Amway Rules of Conduct, Rules 4.12 and 4.13',
      },
      {
        category: 'Sponsor Change',
        severity: 'medium',
        title: '6-month inactivity required to change sponsors',
        details: 'To change sponsors, you must terminate your IBO contract, remain inactive for 6 consecutive months, then reapply as a new IBO. Additional restrictions: you cannot be sponsored by anyone in your former upline (up to first Platinum) or downline (down to first Platinum) unless 2 years have elapsed.',
        sourceNote: 'Amway Six Month Inactivity Rule (Rules of Conduct)',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Amazon, eBay, and third-party sales prohibited',
        details: 'Amway explicitly states: "unauthorized internet selling is prohibited." Only registered IBOs can sell through in-person sales or their Amway MyShop. Amway has taken legal action against unauthorized sellers and warns products on third-party sites "could be out-of-date, spoiled, altered or even counterfeit."',
        sourceNote: 'Amway Global FAQ (amwayglobal.com/answers)',
      },
      {
        category: 'Contract Amendments',
        severity: 'medium',
        title: '30-day comment period for rule changes',
        details: 'Amway posts proposed changes on their website, opens a 30-day comment period, then changes become effective 15 days after the comment period ends. For Rule 11 (arbitration), IBOAI Board agreement is required. For all other rules, "final decision-making authority rests with Amway."',
        sourceNote: 'Amway Rules of Conduct, Rule 10 (Modification)',
      },
      {
        category: 'BSM Costs',
        severity: 'medium',
        title: 'Business Support Materials costs add up',
        details: 'While BSM purchase is "purely voluntary" and free for first-year IBOs, ongoing costs for seminars, books, and materials from Approved Providers can accumulate. BSM has a 180-day buyback at 90% (100% for first 90 days). Costs must be "reasonably related to sales volume and profits."',
        sourceNote: 'Amway Rules of Conduct, Rule 7 (Business Support Materials)',
      },
      {
        category: 'Buyback',
        severity: 'low',
        title: '90% buyback on unused products within 180 days',
        details: 'Rule 4.10 provides departing IBOs a 90% refund (10% service charge) on unused, currently marketable Amway products returned within 180 days. Products must be unopened, unused, with undamaged packaging. 100% refund on registration costs within first 90 days.',
        sourceNote: 'Amway Rules of Conduct, Rule 4.10; Return Policy',
      },
    ],
    bottomLine: 'Amway\'s Rules of Conduct treat your Line of Sponsorship as their "trade secret" with a revocable license. Post-departure restrictions include 6-month non-compete and 12-month non-solicitation of IBOs. Mandatory binding arbitration waives class action rights. You must meet 70% customer sales requirements with 60% verified to earn full bonuses.',
    policyUrl: 'https://www.amway.com/rules-of-conduct',
  },
  {
    companySlug: 'herbalife',
    companyName: 'Herbalife',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: '$200M FTC settlement history, mandatory arbitration, and strict non-solicitation of downline create substantial risks.',
    pitfalls: [
      {
        category: 'Regulatory',
        severity: 'high',
        title: '$200M FTC settlement for deceptive practices',
        details: 'In 2016, Herbalife paid $200 million to settle FTC charges that it deceived participants about potential income. In 2024, a $17.5M pyramid scheme lawsuit settlement was reached.',
        sourceNote: 'FTC Settlement 2016; Class Action Settlement 2024',
      },
      {
        category: 'Arbitration',
        severity: 'high',
        title: 'Mandatory binding arbitration - no class actions',
        details: 'The distributor agreement requires binding arbitration for all disputes, waiving your right to sue in court or join class action lawsuits. Arbitration occurs in Los Angeles County under AAA rules.',
        sourceNote: 'GoHerbalife Subscription Agreement, Arbitration Section (effective September 2013)',
      },
      {
        category: 'Downline Ownership',
        severity: 'high',
        title: 'Cannot keep downline if you change sponsors',
        details: 'If Herbalife approves a sponsor change, you lose your entire downline organization. Sponsorship changes are "discouraged" and only permitted "at the sole and absolute discretion of Herbalife."',
        sourceNote: 'Herbalife Rules of the Road, May 2025',
      },
      {
        category: 'Non-Solicitation',
        severity: 'high',
        title: 'Cannot recruit downline to competing MLMs',
        details: 'Distributors may not promote other business opportunities to Distributors or Preferred Members. Lineage Reports are proprietary trade secrets for Herbalife business use only.',
        sourceNote: 'Herbalife Rules of the Road, May 2025',
      },
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '$4,000 cumulative purchases for Supervisor rank',
        details: 'To unlock 50% margin and royalty overrides, you must become a Supervisor - requiring approximately $4,000 in cumulative product purchases. This threshold drives inventory loading.',
        sourceNote: 'Herbalife Sales & Marketing Plan',
      },
      {
        category: 'Termination Appeals',
        severity: 'medium',
        title: 'Review Committee decides termination appeals internally',
        details: 'Terminated distributors can appeal to an internal Review Committee (Sales, Distributor Relations, Legal). The company decides if its own termination was justified.',
        sourceNote: 'Herbalife Distributor Policies, Termination Appeal Process',
      },
      {
        category: 'Third-Party Sales',
        severity: 'medium',
        title: 'Cannot sell online except through Herbalife platforms',
        details: 'Distributors may only sell products online using platforms created by Herbalife. Selling on Amazon, eBay, or independent websites is prohibited.',
        sourceNote: 'Herbalife Rules of the Road, May 2025',
      },
      {
        category: 'Waiting Period',
        severity: 'medium',
        title: '90-day waiting period for Preferred Members',
        details: 'Preferred Members must complete a 90-day waiting period from their last order before making certain account changes.',
        sourceNote: 'Herbalife Rules of the Road, May 2025',
      },
    ],
    bottomLine: 'Herbalife\'s $200M FTC settlement and 2024 class action demonstrate ongoing structural issues. The mandatory arbitration clause removes your ability to sue or join class actions. Your downline belongs to Herbalife - you lose it if you change sponsors or leave.',
    policyUrl: 'https://www.herbalife.com/en-us/business-opportunity',
  },
  {
    companySlug: 'doterra',
    companyName: 'doTERRA',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: '12-month non-solicitation after termination, cross-company recruiting ban for 1 year, and 12-month account suspension period.',
    pitfalls: [
      {
        category: 'Non-Solicitation',
        severity: 'high',
        title: '1-year cross-company recruiting ban after leaving',
        details: 'Appearing in, being referenced in, or allowing your name in promotional/recruiting materials for another direct selling company counts as "Cross-Company Recruiting" for one year after termination.',
        sourceNote: 'doTERRA Policy Manual Section 17 E and F (Voluntary Termination Form)',
      },
      {
        category: 'Re-enrollment Waiting',
        severity: 'high',
        title: '6-12 month wait to rejoin after termination',
        details: 'Premier rank or lower: 6-month wait from last activity. Silver rank or higher: 12-month wait before re-enrolling as a Wellness Advocate.',
        sourceNote: 'doTERRA Policy Manual (Voluntary Termination Form)',
      },
      {
        category: 'Account Suspension',
        severity: 'high',
        title: '12-month suspension period - no roll-up of downline',
        details: 'Terminated accounts are suspended for 12 months before actual removal from genealogy. During suspension, volume compresses past you but your downline stays in place.',
        sourceNote: 'doTERRA Policy Manual, Account Termination Section',
      },
      {
        category: 'Health Claims',
        severity: 'high',
        title: 'FDA warning letters for health claims',
        details: 'doTERRA has received multiple FDA warning letters for distributors making unauthorized health claims. Making similar claims risks personal legal liability and termination.',
        sourceNote: 'FDA Warning Letters 2014, 2017',
      },
      {
        category: 'Agreement Amendments',
        severity: 'medium',
        title: 'Company can amend contract with 30 days notice',
        details: 'doTERRA may amend the Contract, including compensation plan, at sole discretion with 30 days notice on website. Continuing business constitutes acceptance.',
        sourceNote: 'doTERRA Policy Manual May 2025',
      },
      {
        category: 'Surviving Obligations',
        severity: 'medium',
        title: 'Confidentiality and non-solicitation survive termination',
        details: 'All obligations regarding confidentiality and Wellness Advocate network (Sections 12 and 17) survive termination of the Contract indefinitely.',
        sourceNote: 'doTERRA Policy Manual, Section 17',
      },
      {
        category: 'Third-Party Sales',
        severity: 'high',
        title: 'Unauthorized marketplace sales enforced',
        details: 'doTERRA actively monitors and terminates accounts for selling on Amazon, eBay, or unauthorized platforms.',
        sourceNote: 'doTERRA Marketplace Policy',
      },
      {
        category: 'Enrollment Fee',
        severity: 'low',
        title: '$35 application fee required',
        details: 'New Wellness Advocates must pay a $35 application fee to enroll, either online or via paper agreement.',
        sourceNote: 'doTERRA Policy Manual May 2025',
      },
    ],
    bottomLine: 'doTERRA\'s Policy Manual creates strict post-termination restrictions: 1-year ban on appearing in competitor materials and 6-12 month waiting periods to rejoin. Confidentiality and non-solicitation obligations explicitly "survive termination" indefinitely. The 12-month account suspension means you can\'t immediately rejoin under a different sponsor.',
    policyUrl: 'https://www.doterra.com/US/en/join',
  },
  {
    companySlug: 'young-living',
    companyName: 'Young Living',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: '12-month non-solicitation of downline/upline, violation equals automatic voluntary termination, and forfeiture of all commissions.',
    pitfalls: [
      {
        category: 'Non-Solicitation',
        severity: 'high',
        title: '12-month ban on recruiting YL members after leaving',
        details: 'For 12 months post-termination, you cannot recruit anyone in your former downline, upline, or anyone you contacted during your YL agreement to competing business ventures.',
        sourceNote: 'U.S. Policies and Procedures Section 3.11.1, Effective January 11, 2025',
      },
      {
        category: 'Automatic Termination',
        severity: 'high',
        title: 'Violation of non-solicitation = automatic voluntary termination',
        details: 'Violating any non-solicitation provision "constitutes your voluntary termination of this Agreement, effective as of the date of the violation" - plus forfeiture of all commissions.',
        sourceNote: 'U.S. Policies and Procedures Section 3.11.1, Effective January 11, 2025',
      },
      {
        category: 'Competing Products',
        severity: 'high',
        title: '12-month ban on soliciting competing products',
        details: 'For 12 months after termination, you cannot offer non-YL products, services, or competing business ventures to anyone you had contact with during your YL agreement.',
        sourceNote: 'U.S. Policies and Procedures Section 3.11.1, Effective January 11, 2025',
      },
      {
        category: 'Confidential Information',
        severity: 'high',
        title: 'Must destroy confidential information upon termination',
        details: 'Upon termination, you must discontinue use of Confidential Information and destroy or return any such information in your possession. This includes downline/customer lists.',
        sourceNote: 'U.S. Policies and Procedures, Confidentiality Section, January 2025',
      },
      {
        category: 'Rank Exceptions',
        severity: 'medium',
        title: 'Associate through Platinum can join non-competing MLMs',
        details: 'Brand Partners at Associate through Platinum rank may join other MLMs if they don\'t have essential oil or nutritional supplement products competing with YL.',
        sourceNote: 'U.S. Policies and Procedures Section 3.11.1, January 2025',
      },
      {
        category: 'Agreement Amendments',
        severity: 'medium',
        title: '30 days notice for policy changes',
        details: 'Young Living may amend the Agreement at any time. Changes become effective 30 days after publication through official YL materials.',
        sourceNote: 'U.S. Policies and Procedures, January 2025',
      },
      {
        category: 'Account Sale',
        severity: 'medium',
        title: 'YL can sell your terminated account to anyone',
        details: 'Any terminated Brand Partner account may be sold by Young Living to any qualified candidate, determined by Young Living at its discretion.',
        sourceNote: 'U.S. Policies and Procedures, January 2025',
      },
      {
        category: 'Surviving Provisions',
        severity: 'medium',
        title: 'Non-solicitation and confidentiality survive termination',
        details: 'The Non-Solicitation, Non-Competition, and Confidentiality provisions explicitly survive termination of the Agreement indefinitely.',
        sourceNote: 'U.S. Policies and Procedures, January 2025',
      },
    ],
    bottomLine: 'Young Living\'s January 2025 Policies make violations extremely costly: non-solicitation violations trigger "automatic voluntary termination" plus forfeiture of all commissions. The 12-month post-termination restrictions cover anyone you contacted during your agreement. Your terminated account can be sold to anyone YL chooses.',
    policyUrl: 'https://www.youngliving.com/en_US/opportunity',
  },
  {
    companySlug: 'mary-kay',
    companyName: 'Mary Kay',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: 'Chargebacks on recruit returns, 90% buyback bans future re-enrollment, and display restrictions survive termination.',
    pitfalls: [
      {
        category: 'Chargebacks',
        severity: 'high',
        title: 'Chargebacks deducted when recruits return products',
        details: 'Anyone who received commission on inventory being returned to Mary Kay will be charged back. Deducted from next commission check, or billed directly if no commissions owed.',
        sourceNote: 'Mary Kay Consultant Agreement, Commission Chargeback Policy',
      },
      {
        category: 'Buyback Consequence',
        severity: 'high',
        title: 'Using 90% buyback bans future re-enrollment',
        details: 'If you return a Starter Kit or Section 1 products for the 90% repurchase, you are "no longer eligible to become a Mary Kay Independent Beauty Consultant in the future."',
        sourceNote: 'Mary Kay Product Repurchase Policy',
      },
      {
        category: 'Termination',
        severity: 'high',
        title: '30 days notice by either party to terminate',
        details: 'Agreement can be terminated by either party for breach or with 30 days written notice at any time. Your unit stays with Mary Kay.',
        sourceNote: 'Independent Beauty Consultant Agreement',
      },
      {
        category: 'Surviving Restrictions',
        severity: 'high',
        title: 'Sales restrictions survive termination',
        details: 'Prohibition on selling through retail establishments, eBay, Amazon, and similar websites survives termination of the Agreement.',
        sourceNote: 'Independent Beauty Consultant Agreement',
      },
      {
        category: 'Customer Lists',
        severity: 'medium',
        title: 'Customer names are consultant property',
        details: 'The consultant agreement states customer names and addresses are the "property" of the consultant. Company cannot use them without consent, even after termination.',
        sourceNote: 'Independent Beauty Consultant Agreement',
      },
      {
        category: 'Non-Compete',
        severity: 'medium',
        title: 'Non-compete clause covers similar cosmetic products',
        details: 'Mary Kay has enforced non-compete provisions prohibiting consultants from "participating in selling cosmetic products similar to Mary Kay\'s line."',
        sourceNote: 'Mary Kay v. Dunlap litigation',
      },
      {
        category: 'Buyback',
        severity: 'low',
        title: '90% buyback within 12 months of purchase',
        details: 'Upon termination, Mary Kay repurchases original unused Section 1 products at 90% of original net cost if purchased within 12 months.',
        sourceNote: 'Independent Beauty Consultant Agreement, Repurchase Policy',
      },
      {
        category: 'Chargeback Duration',
        severity: 'medium',
        title: 'Chargeback liability extends 12 months',
        details: 'You can be charged back commissions for up to 12 months after recruit\'s order, matching the 1-year return window. Bills may be sent to terminated consultants.',
        sourceNote: 'Mary Kay Commission Chargeback Policy',
      },
    ],
    bottomLine: 'Mary Kay\'s 90% buyback comes with a permanent cost: use it and you\'re banned from ever rejoining. Commission chargebacks can follow you for 12 months after a recruit\'s order. The sales restrictions (no eBay/Amazon) explicitly survive termination, limiting how you can use remaining inventory.',
    policyUrl: 'https://www.marykay.com/en-us/tips-and-trends/beauty-entrepreneur',
  },
  {
    companySlug: 'monat-global',
    companyName: 'MONAT Global',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: '6-12 month non-compete after leaving, 1-year cross-company recruiting ban, downline rolls up upon cancellation.',
    pitfalls: [
      {
        category: 'Non-Compete',
        severity: 'high',
        title: '6-12 month non-compete after termination',
        details: 'Below Market Mentor rank: 6-month restriction post-termination. Market Mentor and above: 12-month restriction on competing direct selling ventures.',
        sourceNote: 'MONAT Policies & Procedures, May 30, 2025',
      },
      {
        category: 'Downline Roll-Up',
        severity: 'high',
        title: 'Downline rolls up to upline upon cancellation',
        details: 'Upon cancellation, "their downline will roll up to the upline and will not be replaced." You lose your entire organization permanently.',
        sourceNote: 'MONAT Policies & Procedures, May 30, 2025',
      },
      {
        category: 'Competing Products',
        severity: 'high',
        title: 'Market Mentor+ cannot join other direct selling businesses',
        details: 'Market Partners at Market Mentor rank and above are "completely prohibited from participating in other direct selling businesses" while active.',
        sourceNote: 'MONAT Policies & Procedures, May 30, 2025',
      },
      {
        category: 'Social Media Monitoring',
        severity: 'high',
        title: 'MONAT uses monitoring software for compliance',
        details: 'MONAT "uses monitoring software to review compliance" of social media posts. Prohibited: stock photos, medical claims, income guarantees.',
        sourceNote: 'MONAT Policies & Procedures, Social Media Section',
      },
      {
        category: 'Social Media Sales',
        severity: 'medium',
        title: 'No product sales or enrollments on social media',
        details: '"No product sales or enrollments may occur on any social media site." Testimonials must disclose usage duration and be truthful.',
        sourceNote: 'MONAT Policies & Procedures, May 30, 2025',
      },
      {
        category: 'Amendment Notice',
        severity: 'medium',
        title: '30 days notice for policy amendments',
        details: 'Amendments become effective 30 days after publication via website, email, back office, company periodicals, or special mailings.',
        sourceNote: 'MONAT Policies & Procedures, May 30, 2025',
      },
      {
        category: 'Income Claims',
        severity: 'medium',
        title: 'Strict income claim restrictions',
        details: 'Claims must be "truthful, accurate and represent what the typical earner is likely to achieve." Prohibited: "financial freedom," "time freedom," "guaranteed."',
        sourceNote: 'MONAT Policies & Procedures, May 30, 2025',
      },
      {
        category: 'Product Liability',
        severity: 'high',
        title: 'Class action lawsuits over hair loss claims',
        details: 'MONAT has faced multiple lawsuits from customers claiming products caused hair loss and scalp irritation. Legal history is extensive.',
        sourceNote: 'Florida Class Action Lawsuit, BBB Complaints',
      },
    ],
    bottomLine: 'MONAT\'s May 2025 Policies explicitly state your downline "rolls up" when you leave - you cannot take them with you. The 6-12 month non-compete (rank-dependent) locks you out of competing opportunities. Active monitoring software reviews your social media posts for compliance violations.',
    policyUrl: 'https://monatglobal.com/policies-procedures/',
  },
  {
    companySlug: 'nu-skin-enterprises',
    companyName: 'Nu Skin Enterprises',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: 'Mandatory binding arbitration, 30-day amendment notice, downline can be reassigned as remedial action.',
    pitfalls: [
      {
        category: 'Arbitration',
        severity: 'high',
        title: 'Mandatory binding arbitration - final and non-appealable',
        details: '"Mandatory and binding arbitration is the sole means to resolve disputes which arbitration shall be final and non-appealable." Policy effective April 1, 1994.',
        sourceNote: 'Nu Skin Policies & Procedures, Section 30(B)',
      },
      {
        category: 'Non-Solicitation',
        severity: 'high',
        title: 'Cannot solicit distributors you didn\'t personally sponsor',
        details: 'Distributors cannot "solicit or entice any other Distributor whom she did not personally sponsor to sell or purchase products" beyond company offerings.',
        sourceNote: 'Nu Skin Policies & Procedures, Section 4(C)',
      },
      {
        category: 'Downline Reassignment',
        severity: 'high',
        title: 'Company can reassign your downline as remedial action',
        details: 'Nu Skin may "reassign part or all of the Downline Organization to a different Sponsor" as disciplinary action for policy violations.',
        sourceNote: 'Nu Skin Policies & Procedures, Section 6(A)(6)',
      },
      {
        category: 'Income Claims',
        severity: 'high',
        title: 'No income guarantees or bonus check displays',
        details: '"No unreasonable, misleading, or unrepresentative earnings claims may be made. No income guarantees of any kind. Exhibiting actual or facsimile Bonus checks is prohibited."',
        sourceNote: 'Nu Skin Policies & Procedures, Section 4(B)(2)',
      },
      {
        category: 'Advertising Ban',
        severity: 'medium',
        title: 'Prohibited from using media advertising',
        details: 'Distributors are "expressly prohibited from using any form of media advertising to promote products or services. Products may be promoted only by personal contact."',
        sourceNote: 'Nu Skin Policies & Procedures, Section 20(A)',
      },
      {
        category: 'Website Restrictions',
        severity: 'medium',
        title: 'Must use company-produced websites only',
        details: 'Distributors must "only use Company produced Distributor web sites." Independent sites only allowed for Blue Diamond/Presidential Director level.',
        sourceNote: 'Nu Skin Policies & Procedures, Section 20(H)',
      },
      {
        category: 'Amendment Notice',
        severity: 'medium',
        title: '30 days notice for contract modifications',
        details: '"The Company expressly reserves the right to make any modifications to the Contract upon thirty days prior written notice" via publications, mailings, or websites.',
        sourceNote: 'Nu Skin Policies & Procedures, Section 23',
      },
      {
        category: 'Sponsor Change',
        severity: 'medium',
        title: 'Forbidden from assisting sponsor changes',
        details: 'Distributors are forbidden from "encourage[ing], entice[ing], or otherwise assist[ing] another Distributor to transfer to a different Sponsor."',
        sourceNote: 'Nu Skin Policies & Procedures, Section 3(F)',
      },
    ],
    bottomLine: 'Nu Skin\'s Policies explicitly allow reassigning your downline to another sponsor as a remedial action. The mandatory arbitration policy (since 1994) is "final and non-appealable." Media advertising is prohibited - only personal contact allowed. Your website must be company-produced unless you reach Blue Diamond level.',
    policyUrl: 'https://www.nuskin.com/global/library/policies/Policies_Proced_US.html',
  },
  {
    companySlug: 'avon-products',
    companyName: 'Avon Products',
    lastUpdated: '2026-03-22',
    overallRisk: 'medium',
    riskReason: 'Binding JAMS arbitration, plans subject to change at any time, independent contractor status.',
    pitfalls: [
      {
        category: 'Arbitration',
        severity: 'high',
        title: 'Binding JAMS arbitration - no jury trial',
        details: 'All claims "shall be exclusively resolved by binding arbitration before one neutral arbitrator and administered by the Judicial Arbitration and Mediation Service (JAMS)."',
        sourceNote: 'Independent Sales Representative Terms and Conditions, 2025',
      },
      {
        category: 'Comp Plan Changes',
        severity: 'high',
        title: 'Compensation plans subject to change at any time',
        details: '"Avon\'s compensation plans, including the Leadership program, are subject to change at any time at Avon\'s sole discretion."',
        sourceNote: 'Avon 2026 Career & Compensation Guide',
      },
      {
        category: 'Policy Priority',
        severity: 'medium',
        title: 'Website policies override all other sources',
        details: '"In the event of a conflict between these policies and information provided by the Care Center, Account Executive, or any other source, the information on Avon.com will control."',
        sourceNote: 'Business Policies and Procedures for Avon Independent Ambassadors',
      },
      {
        category: 'Disqualification',
        severity: 'medium',
        title: 'Avon can disqualify for program intent violations',
        details: 'Avon reserves the right to "disqualify or remove any Ambassador it determines has violated principles of fairness, program intent, or any violation of the Contract."',
        sourceNote: 'Avon 2026 Career & Compensation Guide',
      },
      {
        category: 'Independent Contractor',
        severity: 'medium',
        title: 'Independent contractor - no employee benefits',
        details: 'Ambassadors are "self-employed, non-exclusive independent contractors" with no employment benefits, insurance, or employer tax contributions.',
        sourceNote: 'Independent Sales Representative Terms and Conditions, 2025',
      },
      {
        category: 'Variable Commission',
        severity: 'medium',
        title: 'Commission rates vary by campaign and category',
        details: 'Under the 2026 structure, commission rate changes based on each 2-week campaign volume. Beauty/Jewelry: 25% base; Home/Fashion: 20%.',
        sourceNote: 'Avon 2026 Career & Compensation Guide',
      },
      {
        category: 'Minimum Order',
        severity: 'low',
        title: '$40 minimum order required per campaign',
        details: 'You must reach at least $40 in orders per campaign to earn any commission for that cycle.',
        sourceNote: 'Avon 2026 Compensation Guide',
      },
      {
        category: 'PSA Deadline',
        severity: 'low',
        title: 'Annual PSA order deadline',
        details: 'PSA orders must be placed and billed by 5:00 PM EST 12/01/2026 to count toward 2026 requirements.',
        sourceNote: 'Avon 2026 Career & Compensation Guide',
      },
    ],
    bottomLine: 'Avon\'s 2025 Terms require binding JAMS arbitration, eliminating jury trials. The compensation plan "is subject to change at any time at Avon\'s sole discretion." Website policies override anything reps are told by Care Center or their upline. More accessible minimums but unpredictable income structure.',
    policyUrl: 'https://www.avon.com/becomearep',
  },
  {
    companySlug: 'primerica',
    companyName: 'Primerica',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: '$99 startup plus $200-500 licensing costs, $25/month subscription fee, captive agent restrictions.',
    pitfalls: [
      {
        category: 'Startup Costs',
        severity: 'high',
        title: '$99 initial fee plus ongoing monthly costs',
        details: '$99 USD ($103.95 CAD) initial fee for Independent Business Application. Plus Primerica Online (POL) subscription: $25/month (US) or $28/month (Canada) for Full-Service.',
        sourceNote: 'Primerica Important Disclosures, 2025',
      },
      {
        category: 'Licensing Costs',
        severity: 'high',
        title: 'State licensing required before selling',
        details: '"Representatives must obtain required licenses before they may sell those products." Licensing costs $200-500+ including exams, background checks, continuing education.',
        sourceNote: 'Primerica Important Disclosures, 2025',
      },
      {
        category: 'Income Reality',
        severity: 'high',
        title: 'Average $8,199 in 2025 - "extraordinary" and "not typical"',
        details: 'Primerica paid life-licensed sales force average of $8,199 in 2025. This average "reflects an extraordinary level of success that is not typical of the sales force."',
        sourceNote: 'Primerica Important Disclosures, 2025',
      },
      {
        category: 'Ongoing Expenses',
        severity: 'high',
        title: 'Personal expenses not covered by company',
        details: 'Representatives "may incur ongoing personal expenses to conduct business." These are separate from required licensing and subscription costs.',
        sourceNote: 'Primerica Important Disclosures, 2025',
      },
      {
        category: 'Independent Contractor',
        severity: 'medium',
        title: 'Independent contractor - no employee benefits',
        details: '"Sales representatives are independent contractors, not employees." Earnings are entirely commission-based with no salary, benefits, or guarantees.',
        sourceNote: 'Primerica Important Disclosures, 2025',
      },
      {
        category: 'Ownership Program',
        severity: 'medium',
        title: 'Ownership Program governed by separate documents',
        details: 'References to "Ownership" refer to qualified representatives under separate Ownership Program policies. POL for Ownership "controls in all respects."',
        sourceNote: 'Primerica POL Agreement',
      },
      {
        category: 'Compliance',
        severity: 'medium',
        title: 'Must comply with Basic Agreement requirements',
        details: 'Representatives must "comply with all other contractual and Company requirements that govern your conduct, such as your Basic Agreement."',
        sourceNote: 'Primerica POL Agreement',
      },
      {
        category: 'Business Use Only',
        severity: 'low',
        title: 'POL application restricted to Primerica business',
        details: 'Must use the POL Application "only as necessary to conduct Primerica business" - no personal or other commercial use.',
        sourceNote: 'Primerica POL Agreement',
      },
    ],
    bottomLine: 'Primerica\'s own disclosures state the $8,199 average income "reflects an extraordinary level of success that is not typical." Before earning anything: $99 startup + $200-500 licensing + $25/month ongoing subscription. As independent contractors, you receive no employee benefits or income guarantees.',
    policyUrl: 'https://www.primerica.com/public/primerica_disclosures.html',
  },
  {
    companySlug: 'melaleuca',
    companyName: 'Melaleuca',
    lastUpdated: '2026-03-22',
    overallRisk: 'medium',
    riskReason: 'Permanent loss of rights upon termination, 30-day amendment notice, 100% end-consumer purchase requirement.',
    pitfalls: [
      {
        category: 'Termination Consequence',
        severity: 'high',
        title: 'Permanent loss of all rights upon cancellation',
        details: '"If the agreement is canceled or terminated at any time for any reason, the Marketing Executive permanently loses all rights, and agrees to waive all rights and claims to their Marketing Organization."',
        sourceNote: 'Melaleuca Statement of Policies, Policy 20 (March 2025)',
      },
      {
        category: 'Non-Solicitation',
        severity: 'high',
        title: 'Cannot recruit Melaleuca members to other businesses',
        details: 'Marketing Executives and Immediate Household are "prohibited from directly, indirectly or through a third party recruiting any Melaleuca Customers or Marketing Executives to participate in any other business ventures."',
        sourceNote: 'Melaleuca Statement of Policies, Policy 20',
      },
      {
        category: 'Consumer Purchases',
        severity: 'high',
        title: '100% of volume must be end-consumer purchases',
        details: '"100% of monthly Marketing Organization Product Points must be purchased by End Consumers each month. Marketing Executives cannot purchase products solely for the purpose of qualifying."',
        sourceNote: 'Melaleuca Independent Marketing Executive Agreement, March 2025',
      },
      {
        category: 'Amendment Notice',
        severity: 'medium',
        title: '30 days notice for policy changes - only remedy is to quit',
        details: 'Melaleuca may amend Compensation Plan, Policies, and Agreement with 30 days notice. "Marketing Executives agree to abide by any such amendments and their only remedy for not accepting is to immediately terminate."',
        sourceNote: 'Melaleuca Independent Marketing Executive Agreement, March 2025',
      },
      {
        category: 'One Account',
        severity: 'medium',
        title: 'Only one Independent Melaleuca Business allowed',
        details: '"Marketing Executives may only have ownership or ownership affiliation in one Independent Melaleuca Business" per Statement of Policies #15.',
        sourceNote: 'Melaleuca Statement of Policies',
      },
      {
        category: 'Required Purchases',
        severity: 'medium',
        title: '35 Product Points monthly for Preferred Customer status',
        details: 'A Preferred Customer is defined as someone "committed to purchase at least 35 Product Points per month" to receive 30-50% product discounts.',
        sourceNote: 'Melaleuca Customer Agreement',
      },
      {
        category: 'No Reselling',
        severity: 'medium',
        title: 'Melaleuca does not permit product reselling',
        details: '"Melaleuca does not permit anyone to sell or resell its products, either directly or through another party. Instead, Melaleuca sells its products directly to each end-consumer."',
        sourceNote: 'Melaleuca Statement of Policies',
      },
      {
        category: 'Independent Contractor',
        severity: 'low',
        title: 'Success depends on own efforts - no guarantees',
        details: '"Marketing Executives are independent contractors, not agents or employees. Success as a Marketing Executive depends upon one\'s own efforts, skills, and productivity."',
        sourceNote: 'Melaleuca Independent Marketing Executive Agreement, March 2025',
      },
    ],
    bottomLine: 'Melaleuca\'s Agreement is clear: termination means you "permanently lose all rights" to your Marketing Organization and waive all claims. The 30-day amendment notice gives you only one remedy if you disagree - immediately quit. 100% of volume must come from end-consumers, not self-purchases.',
    policyUrl: 'https://www.melaleuca.com/productstore/marketing-executive',
  },
  {
    companySlug: 'usana-health-sciences',
    companyName: 'USANA Health Sciences',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: '5-year non-compete on competing products, no Leadership/Elite bonuses if in other MLMs, AAA mediation required.',
    pitfalls: [
      {
        category: 'Non-Compete',
        severity: 'high',
        title: '5-year non-compete after termination',
        details: 'During agreement term and "for a period of five (5) years after the termination," Associates face restrictions on competitive activities.',
        sourceNote: 'USANA Policies & Procedures',
      },
      {
        category: 'Competing Products',
        severity: 'high',
        title: 'Any dietary supplement is "competing" with USANA',
        details: '"Any product or service in the same generic category as a USANA product is deemed to be competing (e.g., any dietary supplement is in the same generic category as USANA\'s dietary supplements)."',
        sourceNote: 'USANA Policies & Procedures',
      },
      {
        category: 'MLM Restrictions',
        severity: 'high',
        title: 'No Leadership/Elite Bonus if in other MLMs',
        details: '"Associates who participate in other MLM ventures may not participate in USANA\'s Leadership or Elite Bonus programs." Accepting bonuses while in another MLM is a material breach.',
        sourceNote: 'USANA Policies & Procedures',
      },
      {
        category: 'Termination Refunds',
        severity: 'high',
        title: 'Commissions deducted from refunds on returns',
        details: '"The Company will adjust the appropriate Associate\'s sales volume, and USANA may deduct from the amount of the refund any commissions or bonuses the Associate may have received."',
        sourceNote: 'USANA Policies & Procedures',
      },
      {
        category: 'Dispute Resolution',
        severity: 'medium',
        title: 'AAA mediation required before arbitration',
        details: 'Disputes require mediation per AAA Commercial Financial Dispute rules. If parties can\'t agree on mediator, AAA appoints one. Mediation within 60 days; costs split equally.',
        sourceNote: 'USANA Policies & Procedures',
      },
      {
        category: 'Disciplinary Actions',
        severity: 'medium',
        title: 'Warnings, fines, probation, or termination',
        details: 'For policy violations, USANA may take actions "including warnings, fines, probation, withdrawing or denying awards, suspending privileges, withholding commissions, or termination."',
        sourceNote: 'USANA Policies & Procedures',
      },
      {
        category: 'Commission Errors',
        severity: 'medium',
        title: '30 days to report commission errors',
        details: '"An Associate must review his/her commissions and report any errors or discrepancies to USANA within 30 days from the date of the commission check." After 30 days, errors won\'t be addressed.',
        sourceNote: 'USANA Policies & Procedures',
      },
      {
        category: 'Voluntary Cancellation',
        severity: 'low',
        title: 'Returns over $100 constitute Voluntary Cancellation',
        details: '"If an Associate returns their Starter Kit and/or merchandise equal to or exceeding $100.00 US for a refund, the return constitutes a Voluntary Cancellation of the Associate Agreement."',
        sourceNote: 'USANA Policies & Procedures',
      },
    ],
    bottomLine: 'USANA\'s 5-year post-termination non-compete is one of the longest in the industry. Participating in any other MLM disqualifies you from Leadership/Elite Bonus programs. Even returning $100+ in products triggers "Voluntary Cancellation" of your agreement.',
    policyUrl: 'https://usana.com/media/File/Training%20page/BDS%20files/policies%20and%20pro/EN-PoliciesProcedures.pdf',
  },
  {
    companySlug: 'isagenix',
    companyName: 'Isagenix',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: '1-year non-solicitation after termination, JAMS binding arbitration, 24-month wait for Directors+ to re-enroll.',
    pitfalls: [
      {
        category: 'Non-Solicitation',
        severity: 'high',
        title: '1-year non-solicitation survives termination',
        details: '"During the term of your relationship with Isagenix and for one year thereafter, you agree that you will not solicit or encourage any Associate or Customer to join another network marketing, multi-level marketing, or direct selling company."',
        sourceNote: 'Isagenix Policies & Procedures, Non-Solicitation Section',
      },
      {
        category: 'Arbitration',
        severity: 'high',
        title: 'JAMS binding arbitration for disputes over $100K',
        details: '"Any complaint, dispute, or disagreement shall be resolved exclusively by final and confidential binding arbitration administered by JAMS" using Streamlined or Comprehensive Rules depending on amount.',
        sourceNote: 'Isagenix Policies & Procedures, Section 9.10',
      },
      {
        category: 'Re-enrollment Wait',
        severity: 'high',
        title: '24-month wait for Director+ to re-enroll',
        details: '"Associates who have ever achieved the rank of Director or above may reapply 24 months from the date of their last Qualifying Activity, and neither they nor their spouse are eligible to re-earn any Rank Advancement Bonuses previously earned."',
        sourceNote: 'Isagenix Policies & Procedures, Reenrollment Section',
      },
      {
        category: 'Sponsor Changes',
        severity: 'high',
        title: 'Forbidden to solicit sponsor changes',
        details: '"It is a violation of your Agreement to solicit or encourage any Associate, Brand Partner, or Preferred Customer to change Marketing Organizations/Sponsors."',
        sourceNote: 'Isagenix Policies & Procedures',
      },
      {
        category: 'Surviving Obligations',
        severity: 'medium',
        title: 'Non-solicitation and arbitration survive termination',
        details: '"Provisions relating to confidentiality, non-solicitation, resale of products, including prohibitions of online sales, arbitration, and other provisions will survive the termination of your relationship."',
        sourceNote: 'Isagenix Policies & Procedures',
      },
      {
        category: 'Amendment Notice',
        severity: 'medium',
        title: '30 days to accept or leave upon amendments',
        details: '"Isagenix will provide 30 days\' advance notice of any such amendment via electronic mail. You must accept the terms of any amendment within 30 days of receiving notice."',
        sourceNote: 'Isagenix Policies & Procedures',
      },
      {
        category: 'Irreparable Harm',
        severity: 'medium',
        title: 'Breach causes "irreparable harm" per agreement',
        details: '"A breach of these provisions would cause Isagenix irreparable harm" - this language supports the company seeking injunctive relief against departing Associates.',
        sourceNote: 'Isagenix Policies & Procedures, Non-Solicitation Section',
      },
      {
        category: 'Qualifying Activity',
        severity: 'low',
        title: '100 BV order counts as Qualifying Activity',
        details: 'Qualifying Activity includes: placing 100 BV+ product orders, earning commission, attending incentive trip, enrolling a Member, or any solicitation/prospecting activity.',
        sourceNote: 'Isagenix Policies & Procedures, Reenrollment Section',
      },
    ],
    bottomLine: 'Isagenix\'s non-solicitation clause explicitly survives termination for one year. Directors and above face a 24-month wait to re-enroll and cannot re-earn previous Rank Advancement Bonuses. The agreement states that breach causes "irreparable harm" - language designed to support injunctions against departing Associates.',
    policyUrl: 'https://www.isagenix.com/en-us/become-an-associate',
  },
  {
    companySlug: 'rodan-fields',
    companyName: 'Rodan + Fields',
    lastUpdated: '2026-03-22',
    overallRisk: 'medium',
    riskReason: 'Transitioned to 30% affiliate model Sept 2024 - no MLM recruitment, 30-day amendment notice, annual renewal required.',
    pitfalls: [
      {
        category: 'Business Model Change',
        severity: 'high',
        title: 'No new MLM Consultant Applications after Sept 1, 2024',
        details: '"As of September 1, 2024, Rodan + Fields no longer accepts new Consultant Applications." Only existing Consultants in good standing may continue.',
        sourceNote: 'Rodan + Fields Policies & Procedures Version 22, September 1, 2025',
      },
      {
        category: 'Commission Structure',
        severity: 'medium',
        title: '30% affiliate commission replaces MLM structure',
        details: '"Brand Consultants now earn a 30% affiliate commission on all sales, with no limit. Additionally, Brand Consultants enjoy a 30% discount on all products."',
        sourceNote: 'Rodan + Fields Business Changes Announcement, 2024',
      },
      {
        category: 'No Downline Commissions',
        severity: 'medium',
        title: 'Recruitment commissions eliminated',
        details: '"Recruitment and commissions Consultants receive through product sales by those they have recruited will no longer be a component of Rodan + Fields\'s model."',
        sourceNote: 'Rodan + Fields Business Changes Announcement, 2024',
      },
      {
        category: 'Agreement Requirements',
        severity: 'medium',
        title: 'Annual Renewal Fee required to maintain status',
        details: 'To remain a Consultant after September 2024, you must have been "in good standing on August 31, 2024, pay and continue to pay the annual Renewal Fee, and comply with Policies and Procedures."',
        sourceNote: 'Rodan + Fields Policies & Procedures Version 22, September 1, 2025',
      },
      {
        category: 'Amendment Notice',
        severity: 'medium',
        title: '30 days notice for policy amendments',
        details: '"Amended Policies and Procedures will become effective thirty (30) days after notice is provided, or as of the Effective Date appearing on the Table of Contents, whichever is later."',
        sourceNote: 'Rodan + Fields Policies & Procedures Version 22, September 1, 2025',
      },
      {
        category: 'Agreement Components',
        severity: 'low',
        title: 'Policies & Procedures form integral part of agreement',
        details: 'The "Consultant Agreement" consists of: (i) properly completed and submitted Consultant Application accepted by R+F; (ii) Policies and Procedures; and, if applicable, (iii) Business Entity Registration Form.',
        sourceNote: 'Rodan + Fields Policies & Procedures Version 22, September 1, 2025',
      },
      {
        category: 'Earnings Impact',
        severity: 'low',
        title: '90% have higher earning potential under new model',
        details: 'Per company statement, "over 90% [of Consultants will have] higher earning potential based on their current sales performance" under the affiliate model.',
        sourceNote: 'Rodan + Fields Business Changes Announcement, 2024',
      },
    ],
    bottomLine: 'Rodan + Fields fundamentally changed in September 2024 - no new MLM Consultants, no downline commissions. The 30% affiliate commission model is simpler but caps income potential. Existing Consultants must pay annual Renewal Fees to continue. Company claims 90%+ have higher earning potential under new model.',
    policyUrl: 'https://www.rodanandfields.com/en-us/assets/us/policies-procedures-v22-090125-us.pdf',
  },
  {
    companySlug: 'lularoe',
    companyName: 'LuLaRoe',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: 'Company can cancel IFR Agreement at sole discretion, $4.75M WA settlement for pyramid scheme allegations, policy updates via Back Office only.',
    pitfalls: [
      {
        category: 'Agreement Cancellation',
        severity: 'high',
        title: 'Company can cancel agreement at sole discretion',
        details: 'The Company may "in its sole discretion, consider the IFR Agreement of a dissolving or discontinuing Business Entity canceled and null and void." No claim to genealogical IFR Line or products.',
        sourceNote: 'LuLaRoe Policies and Procedures Rev.020124.001',
      },
      {
        category: 'Legal Settlement',
        severity: 'high',
        title: '$4.75M Washington State settlement for pyramid scheme claims',
        details: 'In 2021, LuLaRoe settled with Washington AG for $4.75M. "Every Washington retailer who lost money under LuLaRoe\'s pyramid structure will receive restitution."',
        sourceNote: 'Washington State AG Settlement 2021',
      },
      {
        category: 'Non-Disparagement',
        severity: 'high',
        title: 'Cannot disparage company, products, comp plan, or other IFRs',
        details: '"IFRs may not disparage, demean, or make negative statements, comments, or remarks about the Company, its employees or representatives, LLR Products, the Leadership Compensation Plan, or other IFRs."',
        sourceNote: 'LuLaRoe Policies and Procedures Rev.020124.001',
      },
      {
        category: 'Policy Updates',
        severity: 'medium',
        title: 'Policy updates via Back Office only - no direct notification required',
        details: '"Publishing and making restatements or amendments available in the Back Office (without further notification) is deemed a reasonable method of notifying IFRs of new restatements or amendments."',
        sourceNote: 'LuLaRoe Policies and Procedures Rev.020124.001',
      },
      {
        category: 'Buyback History',
        severity: 'high',
        title: '90% buyback replaced 100% guarantee in 2017',
        details: 'In September 2017, LuLaRoe rescinded its 100% buyback guarantee. New policy offers only 90% buyback with restrictions, putting consultants at financial risk.',
        sourceNote: 'LuLaRoe Policy Change 2017; Class Action Lawsuits',
      },
      {
        category: 'Inventory Risk',
        severity: 'high',
        title: '$499 minimum inventory purchase required',
        details: 'The LuLaRoe Retailer Business Pack costs $499 and includes 33 pieces of clothing. This is "the only purchase required to become a LuLaRoe Retailer."',
        sourceNote: 'LuLaRoe Enrollment Requirements',
      },
      {
        category: 'Income Disparity',
        severity: 'medium',
        title: 'Median earnings significantly below average',
        details: 'Top sellers dramatically skew averages. Most retailers earn modest amounts while a small percentage earn substantial income.',
        sourceNote: 'LuLaRoe Income Disclosure Statement',
      },
      {
        category: 'Product Definitions',
        severity: 'low',
        title: 'IFR status tied to product availability',
        details: '"LLR Products" means all products made available by the Company for retail sale by IFRs, including clothing, garments, apparel, shoes, or accessories.',
        sourceNote: 'LuLaRoe Policies and Procedures Rev.020124.001',
      },
    ],
    bottomLine: 'LuLaRoe\'s $4.75M Washington settlement confirms the risk. The company can cancel IFR Agreements "at sole discretion" with no claim to your organization. Policy updates happen through the Back Office without direct notification. The 2017 change from 100% to 90% buyback left many retailers financially exposed.',
    policyUrl: 'https://d1lmfvj4ldun6m.cloudfront.net/exigo/llrAdmin/documents/LLR_P&Ps.pdf',
  },
  {
    companySlug: 'plexus-worldwide',
    companyName: 'Plexus Worldwide',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: '1-year post-termination recruiting ban, Emerald+ cannot participate in competing MLMs, Arizona arbitration required.',
    pitfalls: [
      {
        category: 'Cross-Recruiting Ban',
        severity: 'high',
        title: '1-year ban on recruiting Brand Ambassadors after leaving',
        details: '"A Brand Ambassador is prohibited, during the term of the Agreement and for a period one (1) year following the date of termination, from Recruiting a Brand Ambassador to sell or purchase products or services other than those offered by Plexus."',
        sourceNote: 'Plexus Brand Ambassador Policies and Procedures USA, July 15, 2025',
      },
      {
        category: 'Leadership Restrictions',
        severity: 'high',
        title: 'Emerald+ cannot participate in competing MLMs',
        details: '"Brand Ambassadors at the rank of Emerald or above may not participate or promote, directly or indirectly, any competing network marketing business." Emerald+ are "high-profile, leadership positions."',
        sourceNote: 'Plexus Brand Ambassador Policies and Procedures USA, July 15, 2025',
      },
      {
        category: 'Competing Products',
        severity: 'high',
        title: 'Cannot promote ingestible/topical products with same IP',
        details: '"A Brand Ambassador is prohibited during the term of the Agreement from promoting or selling in any Authorized Country any non-Company brand ingestible or topical products, which have the same core intellectual properties."',
        sourceNote: 'Plexus Brand Ambassador Policies and Procedures USA, July 15, 2025',
      },
      {
        category: 'Arbitration',
        severity: 'high',
        title: 'Arizona arbitration required - injunctive relief clause',
        details: 'Disputes resolved through arbitration under Arizona law. "Such injunctive relief may extend the post-termination period of this restriction for up to one (1) year from the date of the last violation."',
        sourceNote: 'Plexus Brand Ambassador Policies and Procedures USA, July 15, 2025',
      },
      {
        category: 'Trade Secret Claim',
        severity: 'medium',
        title: 'Recruiting constitutes "misappropriation of trade secrets"',
        details: '"The Brand Ambassador stipulates and agrees that Recruiting constitutes an unreasonable and unwarranted interference with the contractual relationship between the Company and its Brand Ambassadors, conversion of the Company\'s property, and misappropriation of the Company\'s trade secrets."',
        sourceNote: 'Plexus Brand Ambassador Policies and Procedures USA, July 15, 2025',
      },
      {
        category: 'Confidentiality',
        severity: 'medium',
        title: 'Confidentiality survives termination - injunctive relief available',
        details: '"Plexus and its Brand Ambassadors will be entitled to injunctive relief to prevent breach of confidentiality provisions. The confidentiality obligations and related remedies survive the termination of the relationship with Plexus."',
        sourceNote: 'Plexus Brand Ambassador Policies and Procedures USA, July 15, 2025',
      },
      {
        category: 'Zero Earnings Tier',
        severity: 'high',
        title: 'Earn 0% commission if under 100 PV monthly',
        details: 'Unlike most MLMs that pay reduced commissions, Plexus pays nothing if you don\'t hit 100 PV in a month.',
        sourceNote: 'Plexus Compensation Plan',
      },
      {
        category: 'Irreparable Harm',
        severity: 'medium',
        title: 'Violation causes "immediate and irreparable harm"',
        details: '"The Brand Ambassador further agrees that any violation of this rule will inflict immediate and irreparable harm on the Company" - legal language supporting injunctive relief.',
        sourceNote: 'Plexus Brand Ambassador Policies and Procedures USA, July 15, 2025',
      },
    ],
    bottomLine: 'Plexus July 2025 Policies are aggressive: 1-year cross-recruiting ban, Emerald+ banned from competing MLMs, and recruiting is deemed "misappropriation of trade secrets." Violations trigger claims of "irreparable harm" supporting injunctive relief. Arizona arbitration with potential 1-year extension of restrictions.',
    policyUrl: 'https://static.plexusworldwide.com/assets/us-vo/plexus-policies-and-procedures-en-us.pdf',
  },
  {
    companySlug: 'forever-living-products',
    companyName: 'Forever Living Products',
    lastUpdated: '2026-03-22',
    overallRisk: 'medium',
    riskReason: 'Management Committee termination decisions are final, fraudulent sponsoring triggers termination, 30-day dispute resolution notice.',
    pitfalls: [
      {
        category: 'Termination Authority',
        severity: 'high',
        title: 'Management Committee decisions are final',
        details: '"The Management/Executive Committee\'s decision to terminate a Forever Business or to disallow, realign or adjust Bonuses, Case Credits, compensation or any incentive awards shall be final."',
        sourceNote: 'Forever Living Company Policies and Procedures, February 2023',
      },
      {
        category: 'Suspension',
        severity: 'high',
        title: 'Suspended status blocks orders, payments, and sponsoring',
        details: '"Until investigations are completed, the FBO will be held under \'suspended\' status which will prohibit them from placing orders and may prohibit them from receiving profits and bonus payments, and sponsoring other FBOs."',
        sourceNote: 'Forever Living Company Policies and Procedures, February 2023',
      },
      {
        category: 'Fraudulent Sponsoring',
        severity: 'high',
        title: 'Phantom sponsoring triggers termination and liability',
        details: '"Prohibited activities causing grounds for termination and liability for any damages include fraudulent sponsoring - an FBO/Preferred Customer is prohibited from sponsoring individuals without their knowledge or sponsoring non-existent individuals as phantoms to qualify for commissions."',
        sourceNote: 'Forever Living Company Policies and Procedures, February 2023',
      },
      {
        category: 'Trademark Termination',
        severity: 'high',
        title: 'Policy violations terminate trademark license',
        details: '"Any acts or lack of action, which results in a misuse, misrepresentation or violation of the Company Policies may cause termination of the license granted to use FLP\'s registered trademarks, service marks, and other marks."',
        sourceNote: 'Forever Living Company Policies and Procedures, February 2023',
      },
      {
        category: 'Rank Retention',
        severity: 'medium',
        title: 'Rank lost only through termination or re-sponsoring',
        details: '"There is no re-qualifying for a Sales Level once it is earned unless the Forever Business is terminated or the FBO is Re-sponsored." Rank is retained but commission qualification is monthly.',
        sourceNote: 'Forever Living Company Policies and Procedures, February 2023',
      },
      {
        category: 'Case Credit System',
        severity: 'medium',
        title: 'Case credits calculated monthly - not cumulative',
        details: '"All Case Credits are calculated on a Month by Month basis. Active Case Credits include Personal Case Credits plus Preferred Customer Case Credits."',
        sourceNote: 'Forever Living Company Policies and Procedures, February 2023',
      },
      {
        category: 'Dispute Resolution',
        severity: 'medium',
        title: '30-day notice before policy changes apply',
        details: '"Any revision, modification, amendment to, or termination of the Dispute Resolution/Waiver of Jury Trial agreement shall not apply to a dispute of which the Company has actual notice prior to the effective date. The effective date shall be 30 days after revision is posted."',
        sourceNote: 'Forever Living Company Policies and Procedures, February 2023',
      },
      {
        category: 'Sponsor Credit',
        severity: 'low',
        title: 'Full case credits until Manager level achieved',
        details: '"A Sponsor receives full case credits of any personally-sponsored Preferred Customer and ensuing Downline group until that Preferred Customer achieves the Manager level."',
        sourceNote: 'Forever Living Company Policies and Procedures, February 2023',
      },
    ],
    bottomLine: 'Forever Living\'s Management Committee has final authority on termination and compensation decisions. Investigations result in "suspended status" blocking all activity. Fraudulent sponsoring (including phantom accounts) triggers termination plus liability for damages. Policy violations terminate your trademark license.',
    policyUrl: 'https://cdn.foreverliving.com/content/MarketingConfigurableContent/USA/Company%20Policy%20/Company%20Policies%20and%20Procedures%20English%20(US%20&%20Can%20-%20February%202023).pdf',
  },
  {
    companySlug: 'scentsy',
    companyName: 'Scentsy',
    lastUpdated: '2026-03-22',
    overallRisk: 'medium',
    riskReason: '200 PRV minimum every 12 months or cancellation, 2-year wait to rejoin as new consultant, contract canceled on 13th inactive month.',
    pitfalls: [
      {
        category: 'Activity Requirement',
        severity: 'high',
        title: '200 PRV in one month required every 12 months',
        details: '"Scentsy Consultants must generate sales resulting in 200 points or more in PRV in at least one month within any contiguous four-month period." In the US, 200 PRV is generally equal to $200.',
        sourceNote: 'Scentsy Compensation and Income Disclosure, April 2025',
      },
      {
        category: 'Cancellation',
        severity: 'high',
        title: 'Contract canceled on first of 13th inactive month',
        details: '"If you go twelve months in a row without having a 200-month, your consultant contract will be canceled on the first of the thirteenth month."',
        sourceNote: 'Scentsy Consultant FAQ',
      },
      {
        category: 'Rejoin Wait',
        severity: 'medium',
        title: '2-year wait to rejoin as new consultant',
        details: '"If it\'s been more than two years since you were a Scentsy Consultant, you\'re eligible to Rejoin as a New Consultant." Before 2 years, you must request reinstatement.',
        sourceNote: 'Scentsy Consultant FAQ',
      },
      {
        category: 'Below Active Commission',
        severity: 'high',
        title: '20% commission on first 1,000 PRV lifetime if not Active',
        details: '"Consultants earn 20% on their Personal Retail Volume (PRV) as commission on their first 1,000 PRV of lifetime sales and each subsequent month they do not reach Active status (250+PRV)."',
        sourceNote: 'Scentsy Compensation and Income Disclosure, April 2025',
      },
      {
        category: 'Active Bonus',
        severity: 'medium',
        title: 'Up to 9% bonus requires rank and 2,500 PRV threshold',
        details: '"Consultants can earn up to 9% bonus on Personal Wholesale Volume based on rank and a 5% bonus when monthly sales exceed 2,500 points in PRV."',
        sourceNote: 'Scentsy Compensation and Income Disclosure, April 2025',
      },
      {
        category: 'Reinstatement',
        severity: 'low',
        title: 'No cost to reinstate after cancellation',
        details: '"When you\'re ready to try again after cancellation, you can request a reinstatement by contacting Account Services. There is no cost to return, and when your request is granted, you\'ll be given a time frame to submit a qualified party."',
        sourceNote: 'Scentsy Consultant FAQ',
      },
      {
        category: 'Starter Kit',
        severity: 'low',
        title: 'Starter Kit purchase required to join',
        details: '"You must accept the Independent Consultant Agreement (ICA) and purchase the Starter Kit to become a consultant."',
        sourceNote: 'Scentsy Consultant FAQ',
      },
      {
        category: 'Durable Products',
        severity: 'medium',
        title: 'Wax warmers are durable goods with limited repeat purchases',
        details: 'Unlike consumables, wax warmers last for years. This limits repeat customer purchases and requires constantly finding new customers.',
        sourceNote: 'Product Category Analysis',
      },
    ],
    bottomLine: 'Scentsy\'s April 2025 Compensation Plan requires 200 PRV in a single month every 12 months minimum - miss it and your contract is canceled on the 13th month. Below Active status (250+ PRV), you only earn 20% commission. There\'s a 2-year wait before you can rejoin as a "new" consultant.',
    policyUrl: 'https://scentsy.com/join/compensation-and-income-disclosure',
  },
  {
    companySlug: 'pampered-chef',
    companyName: 'Pampered Chef',
    lastUpdated: '2026-03-22',
    overallRisk: 'low',
    riskReason: 'Company can terminate with or without cause immediately, product exclusivity while active, 30-day amendment notice.',
    pitfalls: [
      {
        category: 'Termination',
        severity: 'high',
        title: 'Company can terminate immediately with or without cause',
        details: '"The Company may terminate the Agreement with or without cause, effective immediately at the time notice is given to the Consultant."',
        sourceNote: 'Pampered Chef Independent Consultant Agreement',
      },
      {
        category: 'Auto-Termination',
        severity: 'high',
        title: 'Agreement terminates after 6 months inactive',
        details: '"The Independent Consultant Agreement is effective for 6 months from the date of acceptance. It is automatically renewed for additional terms of 6 months, but the agreement automatically terminates after a consultant is inactive for 6 consecutive months."',
        sourceNote: 'Pampered Chef Terms & Conditions',
      },
      {
        category: 'Product Exclusivity',
        severity: 'medium',
        title: 'Cannot sell other products as part of your PC business',
        details: '"Consultants agree they will not demonstrate or sell any other services and/or products, including any products made personally by me, as part of my Pampered Chef business." Directors must give up other direct sales businesses.',
        sourceNote: 'Pampered Chef Consultant Policy Guide',
      },
      {
        category: 'Buyback',
        severity: 'low',
        title: '90% buyback on unused products within 12 months',
        details: '"Upon termination of the Agreement, the Company will refund to the consultant 90 percent of the consultant\'s purchase price on any unused and re-saleable product samples or inventory purchased within 12 months."',
        sourceNote: 'Pampered Chef Independent Consultant Agreement',
      },
      {
        category: 'Amendment Notice',
        severity: 'medium',
        title: '30 days notice for commission and requirement changes',
        details: '"The Company may change commissions, overrides, incentive program rules, and active sales requirements at any time with thirty (30) days\' notice."',
        sourceNote: 'Pampered Chef Independent Consultant Agreement',
      },
      {
        category: 'Non-Disparagement',
        severity: 'medium',
        title: 'Cannot make disparaging remarks about company',
        details: '"Consultants agree not to make disparaging remarks regarding the Company to any person, through any means." Includes social media, weblogs, and oral conversation.',
        sourceNote: 'Pampered Chef Independent Consultant Agreement',
      },
      {
        category: 'Activity Minimum',
        severity: 'low',
        title: '$150 in sales monthly to be "active"',
        details: '"A consultant is active in the month in which they submit $150 or more in product sales." Active status unlocks additional awards and privileges.',
        sourceNote: 'Pampered Chef Independent Consultant Agreement',
      },
      {
        category: 'Confidential Information',
        severity: 'medium',
        title: 'Customer lists and downline info are confidential',
        details: '"Confidential information includes, but is not limited to, customer lists, information that identifies customers, sales data, and information regarding the Consultant\'s Personal Team, downline, and upline."',
        sourceNote: 'Pampered Chef Independent Consultant Agreement',
      },
    ],
    bottomLine: 'Pampered Chef can terminate consultants "with or without cause, effective immediately." The agreement auto-terminates after 6 consecutive inactive months. Directors must give up other direct sales businesses for product exclusivity. The 90% buyback within 12 months is a positive feature.',
    policyUrl: 'https://www.pamperedchef.com/view/AgreementModalsController/termsandconditions',
  },
  {
    companySlug: 'arbonne-international',
    companyName: 'Arbonne International',
    lastUpdated: '2026-03-22',
    overallRisk: 'medium',
    riskReason: '150 PQV monthly required to qualify for overrides/bonuses, 1200 PQV over 12 months for consultant status, annual renewal required.',
    pitfalls: [
      {
        category: 'Required Purchases',
        severity: 'high',
        title: '150 PQV monthly to qualify for overrides and bonuses',
        details: '"At all levels of the SuccessPlan, you need to achieve Qualified Status by accumulating 150 Personal Qualifying Volume (PQV) each month to receive overrides, bonuses and other incentives and to qualify for a promotion."',
        sourceNote: 'Arbonne SuccessPlan, January 2018',
      },
      {
        category: 'Consultant Maintenance',
        severity: 'high',
        title: '1200 PQV over 12 months to maintain consultant status',
        details: '"Maintaining your status as Consultant requires getting 1200 PQV over 12 months." This averages to 100 PQV/month minimum.',
        sourceNote: 'Arbonne Policies & Procedures',
      },
      {
        category: 'Self-Purchases',
        severity: 'medium',
        title: 'Many end up buying products to meet requirements',
        details: '"Many consultants end up buying products themselves to meet these requirements." PQV includes purchases under your own Arbonne ID.',
        sourceNote: 'Arbonne PQV FAQ Document',
      },
      {
        category: 'Annual Renewal',
        severity: 'medium',
        title: 'Annual agreement renewal required',
        details: '"The term of the Agreement is one year. Each Arbonne Independent Consultant must renew his or her Agreement with Arbonne every year prior to the end of his or her anniversary month."',
        sourceNote: 'Arbonne Independent Consultant Agreement',
      },
      {
        category: 'Override Requirements',
        severity: 'high',
        title: '500 PQV unlocks 6% override on recruit sales',
        details: '"After reaching 500 Personal Qualifying Volume (PQV), you earn an additional 6% override on sales volume from consultants you recruit."',
        sourceNote: 'Arbonne SuccessPlan, January 2018',
      },
      {
        category: 'PQV Definition',
        severity: 'low',
        title: 'PQV includes personal purchases',
        details: '"PQV includes the Qualifying Volume (QV) from sales to an Arbonne Independent Consultant\'s registered Clients and Preferred Clients and sales and purchases under an Arbonne Independent Consultant\'s own Arbonne ID."',
        sourceNote: 'Arbonne PQV FAQ Document',
      },
      {
        category: 'Premium Pricing',
        severity: 'medium',
        title: 'Vegan/clean beauty positioning limits market',
        details: 'Arbonne\'s premium vegan positioning appeals to a specific demographic but can limit potential customer base compared to mainstream beauty brands.',
        sourceNote: 'Market Analysis',
      },
      {
        category: 'Commission Tiers',
        severity: 'medium',
        title: 'Preferred Clients earn you 15% (vs 35% for regular Clients)',
        details: 'The Preferred Client program that offers customers a discount means lower commissions for you - 15% vs 35% on regular client orders.',
        sourceNote: 'Arbonne Compensation Plan',
      },
    ],
    bottomLine: 'Arbonne requires 150 PQV monthly for Qualified Status to earn overrides/bonuses, plus 1200 PQV over 12 months to maintain consultant status. PQV includes your own purchases, and "many consultants end up buying products themselves to meet requirements." Annual agreement renewal is mandatory.',
    policyUrl: 'https://www.arbonne.com/us/en/join',
  },
  {
    companySlug: 'four-life-research',
    companyName: '4Life Research',
    lastUpdated: '2026-03-22',
    overallRisk: 'medium',
    riskReason: '12-month non-solicitation after termination, Utah arbitration required, amendment via official materials only.',
    pitfalls: [
      {
        category: 'Non-Solicitation',
        severity: 'high',
        title: '12-month social media non-solicitation after termination',
        details: '"During the term of the Agreement and for a period of twelve (12) calendar months thereafter, an Affiliate may not use any Social Media site on which he or she discusses or promotes the 4Life business to directly or indirectly solicit 4Life Affiliates for another company."',
        sourceNote: '4Life Policies & Procedures Section 3.18, April 15, 2021',
      },
      {
        category: 'Arbitration',
        severity: 'high',
        title: 'Utah arbitration - survives termination',
        details: '"The agreement to arbitrate shall survive any termination or expiration of the Agreement. The parties consent to jurisdiction and venue before any federal or state court in Salt Lake County, State of Utah."',
        sourceNote: '4Life Policies & Procedures, April 15, 2021',
      },
      {
        category: 'Amendment Notice',
        severity: 'medium',
        title: 'Amendments via Official 4Life Materials only',
        details: '"4Life reserves the right to amend the Agreement and the prices in its Product Price List in its sole and absolute discretion. Notification of amendments shall appear in Official 4Life Materials."',
        sourceNote: '4Life Policies & Procedures, April 15, 2021',
      },
      {
        category: 'Independent Contractor',
        severity: 'medium',
        title: 'Independent contractor - extension of 4Life',
        details: '"As an Affiliate, you are an independent contractor—not an agent, employee, or franchisee of the Company." However, "you are an extension of 4Life. That means you must comply with these regulations."',
        sourceNote: '4Life Affiliate Agreement',
      },
      {
        category: 'LP Requirements',
        severity: 'medium',
        title: '125 LP required for Loyalty Points bonus product',
        details: '"Distributors and Preferred Customers must maintain a monthly 125 LP Loyalty Program order to receive the Bonus Product of the Month." Standard Loyalty Points earned on orders of 50 LP or more.',
        sourceNote: '4Life Loyalty Program Terms',
      },
      {
        category: 'Loyalty Points',
        severity: 'low',
        title: '150 LP by 20th for 35 bonus Loyalty Points',
        details: '"Loyalty Program orders of 150 LP or more processed on or before the 20th of the month will receive 35 Bonus Loyalty Points." Maximum 75 Loyalty Points per month.',
        sourceNote: '4Life Loyalty Program Terms',
      },
      {
        category: 'Redemption Wait',
        severity: 'low',
        title: '60-day wait before redeeming Loyalty Points',
        details: '"Existing Affiliates and Preferred Customers may begin to redeem Loyalty Points 60 days after their first Loyalty Program order ships."',
        sourceNote: '4Life Loyalty Program Terms',
      },
      {
        category: 'Niche Products',
        severity: 'medium',
        title: 'Transfer Factor products are specialized immune support',
        details: '4Life focuses on Transfer Factor immune support supplements, a niche category that may be unfamiliar to many potential customers.',
        sourceNote: 'Product Line Analysis',
      },
    ],
    bottomLine: '4Life\'s Policies & Procedures include a 12-month social media non-solicitation clause for any site where you\'ve promoted 4Life. Utah arbitration survives termination of your agreement. Amendments appear in "Official 4Life Materials" only - check regularly or miss changes.',
    policyUrl: 'https://media2.4life.com/document/Policies-and-Procedures-US-04.15.2021.pdf',
  },
  {
    companySlug: 'livegood',
    companyName: 'LiveGood',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: 'DSSRC recommends termination for non-compliant income claims, 2x15 forced matrix, $9.95/mo + $40 affiliate fee.',
    pitfalls: [
      {
        category: 'Compliance Issues',
        severity: 'high',
        title: 'DSSRC recommends termination for income claim violations',
        details: '"DSSRC recommended that LiveGood pursue appropriate enforcement mechanisms, including the termination or suspension of the individuals\' account if the posts were made by active salesforce members, for any salesforce member that is unresponsive to LiveGood\'s takedown requests."',
        sourceNote: 'BBB National Programs DSSRC Case #210-2025, May 13, 2025',
      },
      {
        category: 'Non-Compliance',
        severity: 'high',
        title: 'LiveGood did not indicate intent to comply with DSSRC',
        details: '"This was the second inquiry into LiveGood, and LiveGood did not provide a Company statement indicating an intent to comply with DSSRC\'s recommendations."',
        sourceNote: 'BBB National Programs DSSRC Case #210-2025, May 13, 2025',
      },
      {
        category: 'Income Claims',
        severity: 'high',
        title: '18 earnings claims found problematic by DSSRC',
        details: '"The inquiry included 18 earnings claims and six product performance claims. DSSRC was concerned that the subject claims communicated the message that LiveGood salesforce members can generally expect to earn significant income."',
        sourceNote: 'BBB National Programs DSSRC Case #210-2025, May 13, 2025',
      },
      {
        category: 'Matrix Structure',
        severity: 'high',
        title: '2x15 forced matrix heavily favors early joiners',
        details: '"Members get placed in a 2x15 Matrix. As new members join, they fill positions beneath you." Early joiners get spillover advantage; late joiners start from scratch.',
        sourceNote: 'LiveGood Compensation Plan',
      },
      {
        category: 'Low Per-Member Earnings',
        severity: 'high',
        title: 'Matrix commissions start at 2.5% of $9.95 membership',
        details: '"Affiliates earn a percentage of their monthly membership fees (starting at 2.5% depending on rank)." At base level, this equals ~$0.25 per member per month.',
        sourceNote: 'LiveGood Compensation Plan',
      },
      {
        category: 'Membership Costs',
        severity: 'medium',
        title: '$9.95/month plus $40 affiliate signup',
        details: '"The membership fee is $9.95, and the affiliate sign-up fee is $40." Unlike traditional MLMs, no product purchase required, but ongoing fee creates baseline cost.',
        sourceNote: 'LiveGood FAQ',
      },
      {
        category: 'Customer Acquisition',
        severity: 'low',
        title: '10% bonus on customer first product orders',
        details: '"Additional income streams include a customer acquisition bonus of 10% on a customer\'s first product order." One-time bonus on initial orders only.',
        sourceNote: 'LiveGood Compensation Plan',
      },
      {
        category: 'Matching Bonus',
        severity: 'low',
        title: '50% matching bonus on matrix commissions',
        details: '"50% of Matrix commissions are paid as a matching bonus." This requires active recruiting to benefit from.',
        sourceNote: 'LiveGood Compensation Plan',
      },
    ],
    bottomLine: 'LiveGood has been subject to TWO DSSRC inquiries for problematic income claims, and "did not provide a Company statement indicating intent to comply." DSSRC recommends "termination or suspension" for non-compliant members. The 2x15 forced matrix mathematically favors early joiners. $9.95/mo + $40 to start.',
    policyUrl: 'https://bbbprograms.org/programs/advertising/dssrc/cases/livegood',
  },
  {
    companySlug: 'five-rings-financial',
    companyName: 'Five Rings Financial',
    lastUpdated: '2026-03-22',
    overallRisk: 'medium',
    riskReason: 'Insurance licensing requirements, captive agent restrictions, and MLM recruiting dynamics create moderate risk profile.',
    pitfalls: [
      {
        category: 'Non-Compete',
        severity: 'high',
        title: 'Non-compete/non-solicitation clauses typical of financial services MLMs',
        details: 'Financial services MLMs typically include non-compete provisions that restrict your ability to work with competing companies or contact former clients after leaving.',
        sourceNote: 'Industry Standard - Financial Services MLM Contracts',
      },
      {
        category: 'Licensing',
        severity: 'high',
        title: 'State insurance license tied to company — leaving means re-licensing hassle',
        details: 'Your insurance license is typically contracted through Five Rings Financial. Leaving the company may require transferring or re-establishing your license with a new agency, adding cost and friction.',
        sourceNote: 'State Insurance Licensing Requirements',
      },
      {
        category: 'Client Ownership',
        severity: 'high',
        title: 'Clients belong to the company, not you — lose them if you leave',
        details: 'The book of business you build typically remains with Five Rings Financial, not with you personally. If you leave, you may lose access to clients and future renewal commissions.',
        sourceNote: 'Financial Services MLM Ownership Terms',
      },
      {
        category: 'Income Uncertainty',
        severity: 'medium',
        title: 'No guaranteed income despite "career" framing',
        details: 'Despite positioning as a career opportunity, income is entirely commission-based with no salary, benefits, or guarantee. This creates significant income uncertainty.',
        sourceNote: 'Five Rings Financial Compensation Structure',
      },
      {
        category: 'Termination',
        severity: 'high',
        title: 'Termination can remove your book of business',
        details: 'If terminated for policy violations, you risk losing your entire book of business and future renewal commissions with no recourse.',
        sourceNote: 'Financial Services MLM Termination Policies',
      },
      {
        category: 'Social Media',
        severity: 'medium',
        title: 'Social media restrictions on income claims (financial services regulations)',
        details: 'Financial services companies face strict regulatory requirements on income claims and advertising. Violations can result in termination and potential regulatory action.',
        sourceNote: 'FINRA/State Insurance Compliance Requirements',
      },
    ],
    bottomLine: 'Five Rings Financial combines MLM recruiting dynamics with insurance sales licensing requirements. The captive agent model means your clients and license work for the company, not you. If you leave or are terminated, you may lose everything you built. Consider whether an independent agency might offer better long-term control.',
    policyUrl: 'https://fiveringsfinancial.com',
  },
  {
    companySlug: 'mwr-financial',
    companyName: 'MWR Financial (MWR Life)',
    lastUpdated: '2026-03-22',
    overallRisk: 'high',
    riskReason: 'Binary compensation complexity, rebranding history, and subscription requirements create elevated risk profile.',
    pitfalls: [
      {
        category: 'Required Purchases',
        severity: 'high',
        title: 'Monthly subscription required — miss a month, lose commission qualification',
        details: 'To earn commissions, you must maintain an active Financial Edge subscription. Missing a payment can disqualify you from earning that month.',
        sourceNote: 'MWR Financial Compensation Plan',
      },
      {
        category: 'Binary Structure',
        severity: 'high',
        title: 'Binary structure creates predictable commission breakage',
        details: 'Binary plans pay on the lesser leg volume. If your left leg has $10,000 volume and right leg has $2,000, you only earn on $2,000. The $8,000 excess is "breakage" — commission that goes to the company, not you.',
        sourceNote: 'MWR Financial Binary Compensation Structure',
      },
      {
        category: 'Stability',
        severity: 'high',
        title: 'Company rebranding history means stability not guaranteed',
        details: 'MWR Financial has operated under multiple names since 2013, pivoting from travel savings (MWR Life) to financial services. Multiple rebrands suggest business model instability.',
        sourceNote: 'BehindMLM MWR Life Review August 2025',
      },
      {
        category: 'Comp Plan Changes',
        severity: 'medium',
        title: 'Compensation plan changes can reduce income with little notice',
        details: 'Companies that rebrand frequently may also change compensation structures. There is no guarantee your current earning potential remains stable.',
        sourceNote: 'MWR Financial Company History',
      },
      {
        category: 'Product Value',
        severity: 'medium',
        title: 'Travel Advantage product difficult to independently verify value',
        details: 'The Travel Advantage travel savings claims are hard to verify against direct booking prices. Value may vary significantly by destination and timing.',
        sourceNote: 'MWR Financial Product Analysis',
      },
      {
        category: 'Termination',
        severity: 'high',
        title: 'No long-term contractual protection for your downline',
        details: 'If terminated or if the company changes direction again, your downline organization may not be protected. You could lose years of team-building work.',
        sourceNote: 'MLM Contract Standard Terms',
      },
    ],
    bottomLine: 'MWR Financial\'s binary compensation structure means predictable commission loss (breakage) when your legs are unbalanced. The company\'s history of rebranding from MWR Life suggests ongoing business model uncertainty. Required monthly subscriptions to earn commissions add ongoing costs regardless of income.',
    policyUrl: 'https://mwrfinancial.com',
  },
  {
    companySlug: 'unicity-international',
    companyName: 'Unicity International',
    lastUpdated: '2026-03-22',
    overallRisk: 'medium',
    riskReason: 'Undisclosed compensation details, premium pricing, and typical MLM restrictions create moderate risk.',
    pitfalls: [
      {
        category: 'Required Purchases',
        severity: 'medium',
        title: 'Auto-order recommended to qualify for commissions — ongoing expense',
        details: 'To maintain commission qualification, auto-order (autoship) is recommended. This creates an ongoing monthly expense regardless of your sales activity.',
        sourceNote: 'Unicity International Compensation Plan',
      },
      {
        category: 'Transparency',
        severity: 'high',
        title: 'Compensation plan not disclosed — can change without full transparency',
        details: 'Unicity does not fully disclose its compensation plan publicly. This lack of transparency makes it difficult to evaluate the opportunity and compare to alternatives.',
        sourceNote: 'Unicity International Public Materials',
      },
      {
        category: 'Non-Disparagement',
        severity: 'medium',
        title: 'Non-disparagement clauses typical of Utah MLMs',
        details: 'Utah-based MLMs commonly include non-disparagement provisions that limit your ability to speak negatively about the company, even after leaving.',
        sourceNote: 'Utah MLM Contract Standards',
      },
      {
        category: 'Pricing',
        severity: 'medium',
        title: 'Products have premium pricing that makes retail selling challenging',
        details: 'Unicity products are priced significantly above retail alternatives, making customer acquisition more difficult without the MLM discount structure.',
        sourceNote: 'Unicity Product Pricing Analysis',
      },
      {
        category: 'International',
        severity: 'low',
        title: 'International operations mean compliance requirements vary',
        details: 'As an international company, Unicity operates under varying regulations by country. This can create complexity for distributors working across borders.',
        sourceNote: 'Unicity International Operations',
      },
    ],
    bottomLine: 'Unicity International\'s undisclosed compensation plan is the primary concern — you cannot fully evaluate the opportunity without knowing the exact commission structure. Premium product pricing makes retail sales challenging. The auto-order recommendation creates ongoing costs that may exceed your commissions.',
    policyUrl: 'https://unicity.com/usa/en/opportunity',
  },
];

// Helper to get pitfalls data by company slug
export function getPitfallsBySlug(slug: string): PitfallData | undefined {
  return pitfallsData.find(p => p.companySlug === slug);
}

// Helper to check if a company has pitfalls data
export function hasPitfalls(slug: string): boolean {
  return pitfallsData.some(p => p.companySlug === slug);
}

// Get all pitfall slugs for static generation
export function getAllPitfallSlugs(): string[] {
  return pitfallsData.map(p => p.companySlug);
}

// Get pitfalls sorted by risk level (high first)
export function getPitfallsSortedByRisk(): PitfallData[] {
  const riskOrder = { high: 0, medium: 1, low: 2 };
  return [...pitfallsData].sort((a, b) => riskOrder[a.overallRisk] - riskOrder[b.overallRisk]);
}
